import type { Metadata } from 'next';
import { getCanonicalUrl } from '@/lib/seo';

export type IntentProduct = 'notice_only' | 'complete_pack';

export interface IntentPageConfig {
  slug: string;
  title: string;
  description: string;
  h1: string;
  heroSubheadline: string;
  heroCta: string;
  primaryProduct: IntentProduct;
  primarySrc: string;
  secondaryCta?: { label: string; product: IntentProduct; src: string };
  proofBullets: string[];
  icon: string;
  keyword: string;
  problemIntro: string;
  intentDeepDive: string;
  landlordScenarios: string[];
  mistakeRisks: string[];
  templateRisks: string[];
  solicitorPositioning: string;
  whyLandlordHeaven: string[];
  howItWorks: string[];
  included: string[];
  compliance: string[];
  comparisons: Array<{ point: string; landlordHeaven: string; alternative: string }>;
  faqs: Array<{ question: string; answer: string }>;
  relatedLinks: Array<{ href: string; label: string }>;
  finalCta: string;
  lastUpdated?: string;
}

const noticeWizard = (src: string) => `https://landlordheaven.co.uk/wizard/flow?type=eviction&jurisdiction=england&product=notice_only&src=${src}&topic=eviction`;
const completeWizard = (src: string) => `https://landlordheaven.co.uk/wizard/flow?type=eviction&jurisdiction=england&product=complete_pack&src=${src}&topic=eviction`;

export const INTENT_PAGES: Record<string, IntentPageConfig> = {
  'section-21-notice-generator': {
    slug: 'section-21-notice-generator',
    title: 'Section 21 Notice Generator | Form 6A for Landlords',
    description: 'Generate a Section 21 notice (Form 6A) with guided checks for compliance blockers, date logic, and service steps. Built for landlords in England.',
    h1: 'Serve the Right Section 21 Notice',
    heroSubheadline: 'Need to start a no-fault eviction in England? Build your Form 6A with practical checks so you avoid invalid paperwork and delays.',
    heroCta: 'Start your Section 21 notice →',
    primaryProduct: 'notice_only',
    primarySrc: 'section_21_notice_generator',
    proofBullets: ['Checks common Section 21 compliance blockers first', 'Preview before paying', 'Unlimited regenerations if details change'],
    icon: '/images/wizard-icons/13-section-21.png',
    keyword: 'section 21 notice generator',
    problemIntro: 'Section 21 looks simple until one missing compliance item ruins the notice. If your tenant stays put and your notice is invalid, you lose weeks and usually have to start again.',
    intentDeepDive: 'This page is for landlords who already know they want the no-fault route and need to get it right first time. The practical challenge is not finding Form 6A; it is avoiding invalid timing, service, and compliance mistakes that push possession back by months.',
    landlordScenarios: [
      'Your fixed term has ended, the tenant will not leave, and you want a clean no-fault route without a paperwork restart.',
      'You are unsure whether your compliance record is complete enough to serve safely right now.',
      'You need to act this week and want a guided workflow instead of editing generic templates manually.',
    ],
    mistakeRisks: ['Serving Form 6A with the wrong dates or notice period', 'Missing pre-conditions like deposit protection, EPC, gas safety, or How to Rent evidence', 'Serving before your tenancy timing allows it', 'No clear proof of service when you move to court'],
    templateRisks: ['Generic template sites often use stale wording or old form versions', 'Most do not check whether Section 21 is even available for your case', 'You are usually left to calculate dates manually', 'No practical guidance on service evidence or next steps'],
    solicitorPositioning: 'Solicitors are valuable for defended, unusual, or high-conflict possession cases. But for straightforward early-stage Form 6A drafting, many landlords want a faster and cheaper guided DIY route first.',
    whyLandlordHeaven: ['You get route guidance, not just a blank document', 'The flow is built around landlord mistakes that commonly invalidate notices', 'You can fix details and regenerate instantly instead of paying again', 'The output is designed for practical next steps, not just download-and-guess'],
    howItWorks: ['Answer case questions in plain English', 'The wizard validates route and notice details', 'Preview your notice pack before purchase', 'Download and follow included service guidance'],
    included: ['Section 21 notice (Form 6A) generated from your case facts', 'Service instructions and proof prompts', 'Validity checklist to reduce avoidable errors', 'Downloadable pack stored in your account'],
    compliance: ['Deposit protection and prescribed information checks', 'Gas safety, EPC, and How to Rent reminder checks', 'Timing and notice-period sanity checks', 'Service workflow reminders before court stage'],
    comparisons: [
      { point: 'Price', landlordHeaven: 'Low one-time DIY cost', alternative: 'Solicitor drafting usually costs far more' },
      { point: 'Speed', landlordHeaven: 'Start now and generate quickly', alternative: 'Waiting on appointments and back-and-forth' },
      { point: 'Guidance', landlordHeaven: 'Step-by-step route prompts', alternative: 'Generic template download with minimal support' },
      { point: 'Error prevention', landlordHeaven: 'Built-in compliance and date checks', alternative: 'Manual edits increase invalid-notice risk' },
    ],
    faqs: [
      { question: 'Can a Section 21 notice be invalid?', answer: 'Yes. Wrong dates, wrong service, missing compliance pre-conditions, or the wrong route can all make a Section 21 notice unusable at court.' },
      { question: 'Do I always need a solicitor for Section 21?', answer: 'Not always. For straightforward document preparation, many landlords use guided generation tools. Complex or defended cases may still need legal advice.' },
      { question: 'Is Form 6A the correct form for Section 21?', answer: 'In England, yes. Section 21 notices must use Form 6A with the right details and timing for your tenancy.' },
      { question: 'What if I spot a mistake after generating?', answer: 'Update your answers and regenerate so your pack stays consistent with your current case facts.' },
    ],
    relatedLinks: [
      { href: '/section-8-notice-generator', label: 'Need a Section 8 notice instead?' },
      { href: '/section-21-vs-section-8', label: 'Compare Section 21 vs Section 8' },
      { href: '/section-21-court-pack', label: 'Going to court? See the Section 21 court pack' },
    ],
    finalCta: 'Start your Section 21 notice now',
  },
  'section-8-notice-generator': {
    slug: 'section-8-notice-generator',
    title: 'Section 8 Notice Generator | Form 3 for Rent Arrears',
    description: 'Generate a Section 8 notice (Form 3) for rent arrears or breaches with guided grounds, notice period support, and service-ready outputs.',
    h1: 'Generate a Practical Section 8 Notice',
    heroSubheadline: 'If your tenant is in arrears or breaching terms, build the right Form 3 fast with guided checks so you can move without guesswork.',
    heroCta: 'Start your Section 8 notice →',
    primaryProduct: 'notice_only',
    primarySrc: 'section_8_notice_generator',
    proofBullets: ['Built for rent arrears and breach-based routes', 'Preview before paying', 'Unlimited regenerations included'],
    icon: '/images/wizard-icons/14-section-8.png',
    keyword: 'section 8 notice generator',
    problemIntro: 'When rent arrears build up, landlords need action quickly. The problem is Section 8 relies on grounds, dates, and evidence alignment. Get that wrong and possession is delayed.',
    intentDeepDive: 'This page targets landlords dealing with arrears or breach who need the grounds-based route done properly. Section 8 speed only helps if the paperwork and chronology are coherent. The goal is to avoid avoidable delays caused by incorrect grounds framing or service admin gaps.',
    landlordScenarios: [
      'Rent arrears are rising monthly and you need to serve a valid notice before losses compound.',
      'You have breach evidence, but you are unsure how to line it up with the correct grounds and dates.',
      'You need a practical route now without waiting on expensive solicitor drafting for straightforward prep.',
    ],
    mistakeRisks: ['Citing the wrong grounds for the situation', 'Using the wrong notice period for selected grounds', 'Mismatched arrears figures and dates', 'Poor service records that weaken your case'],
    templateRisks: ['Many form sites just hand over Form 3 with no route logic', 'No guardrails around grounds selection', 'No workflow tying notice details to likely court next steps', 'You carry the whole legal admin burden manually'],
    solicitorPositioning: 'Solicitors can help in disputed or defended arrears claims. But for straightforward arrears cases, lots of landlords want a guided DIY start before paying high drafting fees.',
    whyLandlordHeaven: ['Guided inputs help you choose and complete the right grounds route', 'The workflow reduces obvious date and detail mistakes', 'You can iterate quickly when arrears figures change', 'The pack is built for real landlord use, not just legal theory'],
    howItWorks: ['Select your Section 8 scenario and grounds context', 'Enter tenancy, arrears, and service details', 'Preview your generated pack', 'Download and serve using included guidance'],
    included: ['Section 8 notice (Form 3) tailored to your case details', 'Service and validity checklist', 'Practical landlord guidance for the next stage', 'Regeneration support when facts change'],
    compliance: ['Ground and notice-period alignment prompts', 'Arrears detail consistency checks', 'Core service proof reminders', 'Practical preparation notes for possession stage'],
    comparisons: [
      { point: 'Ground selection support', landlordHeaven: 'Guided journey', alternative: 'Blank template with no route support' },
      { point: 'Time to first draft', landlordHeaven: 'Immediate', alternative: 'Manual drafting or waiting for appointments' },
      { point: 'Update workflow', landlordHeaven: 'Quick regeneration', alternative: 'Manual rework and version confusion' },
      { point: 'Court readiness mindset', landlordHeaven: 'Built around next-step workflow', alternative: 'Forms-only approach' },
    ],
    faqs: [
      { question: 'Is Section 8 mainly for rent arrears?', answer: 'It is commonly used for arrears, but Section 8 also covers other tenancy breaches depending on the grounds you rely on.' },
      { question: 'Can I use Section 8 and Section 21 together?', answer: 'Sometimes, yes. Many landlords serve one or both depending on eligibility and strategy. If unsure, get legal advice for your specific case.' },
      { question: 'Do generic Form 3 templates reduce risk?', answer: 'Not by themselves. A form is only part of the job. Route choice, grounds, dates, and service all matter.' },
      { question: 'When should I speak to a solicitor?', answer: 'If your case is unusual, defended, or high value, legal advice can be worth it. For straightforward starts, guided DIY generation is often enough.' },
    ],
    relatedLinks: [
      { href: '/section-21-notice-generator', label: 'Need no-fault route? See Section 21 generator' },
      { href: '/section-21-vs-section-8', label: 'Compare Section 21 vs Section 8 routes' },
      { href: '/section-8-court-pack', label: 'Need court forms too? View Section 8 court pack' },
    ],
    finalCta: 'Build your Section 8 notice',
  },
  'eviction-notice-england': {
    slug: 'eviction-notice-england',
    title: 'Eviction Notice England | Choose Section 21 or 8',
    description: 'Understand which eviction notice route fits your case in England. Compare Section 21 and Section 8 and start the correct notice workflow.',
    h1: 'Eviction Notice England: Start the Right Route',
    heroSubheadline: 'Not sure whether you need Section 21 or Section 8? Use a guided landlord workflow that helps you choose correctly and avoid expensive resets.',
    heroCta: 'Start your eviction notice flow →',
    primaryProduct: 'notice_only',
    primarySrc: 'eviction_notice_england',
    proofBullets: ['Route guidance for Section 21 vs Section 8', 'Preview before paying', 'Built for practical landlord workflows'],
    icon: '/images/wizard-icons/06-notice-details.png',
    keyword: 'eviction notice england',
    problemIntro: 'Most notice failures happen at the start: wrong route, wrong dates, wrong assumptions. Choosing Section 21 when you needed Section 8 (or vice versa) burns time and rent.',
    intentDeepDive: 'This page is built for broad England searches where landlords are still deciding route. The conversion job here is clarity: choose the correct starting notice, avoid wrong-route mistakes, and move into the right wizard flow before time and rent loss increases.',
    landlordScenarios: [
      'You know the tenancy is failing, but you are not sure whether to start with Section 21 or Section 8.',
      'You have mixed issues (arrears plus refusal to leave) and need a practical first move that is valid.',
      'You do not want to waste time on a notice route the court will reject later for basic setup errors.',
    ],
    mistakeRisks: ['Wrong route for your tenancy facts', 'Notice invalidated by compliance blockers', 'Service mistakes with poor evidence trail', 'Delays that stack up lost rent and stress'],
    templateRisks: ['Generic sites rarely explain route decisions clearly', 'No meaningful checks for England-specific compliance issues', 'No practical workflow beyond downloading a file', 'You can accidentally use forms without understanding consequences'],
    solicitorPositioning: 'Solicitor support is sensible for complex matters, contested claims, or strategy disputes. But many landlords just need a clear, accurate way to start the correct notice route.',
    whyLandlordHeaven: ['It helps you decide route before generating paperwork', 'The process is built for landlords, not legal specialists', 'You get practical outputs plus service guidance', 'It is a middle ground between expensive legal drafting and risky generic templates'],
    howItWorks: ['Start the wizard with your case type', 'Follow route prompts for Section 21 or Section 8', 'Review generated documents and checklist', 'Download and proceed with confidence'],
    included: ['Correct notice pack for route selected', 'Guidance on service and next steps', 'Validation prompts around frequent blockers', 'Account storage and regeneration support'],
    compliance: ['Checks route fit before generation', 'Prompts around mandatory compliance evidence', 'Date and notice period support', 'Clear disclaimers where legal advice may still be needed'],
    comparisons: [
      { point: 'Route clarity', landlordHeaven: 'Guided decision support', alternative: 'Template libraries with little context' },
      { point: 'Practical speed', landlordHeaven: 'Fast start and regeneration', alternative: 'Manual drafting cycles' },
      { point: 'Cost profile', landlordHeaven: 'Lower DIY spend', alternative: 'Higher solicitor drafting cost' },
      { point: 'Risk control', landlordHeaven: 'Checklists and prompts', alternative: 'Higher chance of avoidable notice errors' },
    ],
    faqs: [
      { question: 'Which is better: Section 21 or Section 8?', answer: 'Neither is always “better”. It depends on your case facts, tenancy status, and whether you need a no-fault or grounds-based route.' },
      { question: 'Can wrong route choice delay possession?', answer: 'Yes. Starting on the wrong route can force re-service, delay court action, and add more lost rent.' },
      { question: 'Are free templates enough for England notices?', answer: 'They can help you see form structure, but they usually do not provide route validation or practical workflow guidance.' },
      { question: 'Does this page provide legal advice?', answer: 'No. Landlord Heaven provides document generation and guidance, not legal advice or court representation.' },
    ],
    relatedLinks: [
      { href: '/section-21-notice-generator', label: 'Section 21 notice generator' },
      { href: '/section-8-notice-generator', label: 'Section 8 notice generator' },
      { href: '/section-21-court-pack', label: 'Section 21 court pack' },
      { href: '/section-8-court-pack', label: 'Section 8 court pack' },
    ],
    finalCta: 'Start the right England notice route',
  },
  'section-21-vs-section-8': {
    slug: 'section-21-vs-section-8',
    title: 'Section 21 vs Section 8 | Which Route Should You Use?',
    description: 'Compare Section 21 and Section 8 for landlords in England. Understand route fit, risks, and next steps before serving notice.',
    h1: 'Section 21 vs Section 8: Which One Fits Your Case?',
    heroSubheadline: 'Use this landlord-first decision page to avoid serving the wrong notice and losing weeks to preventable admin mistakes.',
    heroCta: 'Choose your notice route →',
    primaryProduct: 'notice_only',
    primarySrc: 'section_21_vs_section_8',
    secondaryCta: { label: 'Need notice + court forms? Start complete pack →', product: 'complete_pack', src: 'section_21_vs_section_8' },
    proofBullets: ['Clear route comparison in plain English', 'Practical decision support before generation', 'Direct links into the right wizard'],
    icon: '/images/wizard-icons/12-summary-cards.png',
    keyword: 'section 21 vs section 8',
    problemIntro: 'Landlords searching this comparison usually need to act now and do not want legal waffle. The key is matching your objective to the right possession route.',
    intentDeepDive: 'This page is intentionally a decision page, not a template page. It is designed to help landlords map facts to route quickly, then move directly into the correct wizard. The core value is reducing route confusion that causes re-service, delay, and duplicated cost.',
    landlordScenarios: [
      'You need a quick route decision before serving anything and risking a costly reset.',
      'You want to compare no-fault and grounds-based paths in practical landlord language.',
      'You may need both notice and court-stage support depending on how the tenant responds next.',
    ],
    mistakeRisks: ['Using Section 21 when you are not eligible', 'Using Section 8 with weak or mismatched grounds', 'Ignoring how route choice affects evidence and court path', 'Losing time by switching strategy late'],
    templateRisks: ['Comparison pages on generic form sites often oversimplify', 'No workflow to carry your decision into valid documents', 'No support for service and evidence continuity', 'Easy to leave with confusion, not action'],
    solicitorPositioning: 'Solicitors are still the right call for defended hearings or complex legal disputes. For many straightforward starts, landlords mainly need clear route selection and correctly prepared documents.',
    whyLandlordHeaven: ['Decision support and document generation live in one flow', 'You are guided from route choice into paperwork without switching tools', 'The process is practical and landlord-friendly', 'You can continue into complete pack if court stage is likely'],
    howItWorks: ['Compare route intent and requirements', 'Choose Section 21 or Section 8 based on your facts', 'Start the matching wizard immediately', 'Move to complete pack where court forms are needed'],
    included: ['Route-specific notice generation workflow', 'Service and validity guidance', 'Cross-link into complete pack for court stage', 'Practical next-step prompts for landlords'],
    compliance: ['Route-eligibility prompts', 'Notice timing and format prompts', 'Service record reminders', 'Clear non-legal-advice boundaries'],
    comparisons: [
      { point: 'Best for', landlordHeaven: 'Landlords choosing route + actioning quickly', alternative: 'Static legal explainers without execution path' },
      { point: 'Execution', landlordHeaven: 'Direct wizard handoff', alternative: 'Manual form hunt and setup' },
      { point: 'Cost and speed', landlordHeaven: 'DIY speed with guided checks', alternative: 'Higher-cost legal drafting or template guesswork' },
      { point: 'Scalability', landlordHeaven: 'Notice only or full court pack options', alternative: 'Single-point template only' },
    ],
    faqs: [
      { question: 'Can I still use Section 21 if tenant is in arrears?', answer: 'Potentially, but eligibility and strategy depend on your case facts. Some landlords also consider Section 8 depending on objectives and evidence.' },
      { question: 'Which route is faster?', answer: 'It varies by case and court conditions. The practical aim is choosing the route that is valid and supportable for your facts.' },
      { question: 'Should I move straight to complete pack?', answer: 'If you expect court action and want notice + court documents in one workflow, complete pack is often the better fit.' },
      { question: 'Does Landlord Heaven represent me in court?', answer: 'No. Landlord Heaven provides document generation and guidance only.' },
    ],
    relatedLinks: [
      { href: '/section-21-notice-generator', label: 'Section 21 notice generator' },
      { href: '/section-8-notice-generator', label: 'Section 8 notice generator' },
      { href: '/section-21-court-pack', label: 'Section 21 court pack' },
      { href: '/section-8-court-pack', label: 'Section 8 court pack' },
    ],
    finalCta: 'Pick your route and get moving',
  },
  'section-21-court-pack': {
    slug: 'section-21-court-pack',
    title: 'Section 21 Court Pack | Notice + N5B Workflow',
    description: 'Generate a Section 21 court pack with Form 6A route support, N5B possession path guidance, evidence checklist, and practical filing structure.',
    h1: 'Section 21 Court Pack for Landlords',
    heroSubheadline: 'Need more than just notice drafting? Build your no-fault route from Form 6A toward the N5B court stage in one guided workflow.',
    heroCta: 'Start your Section 21 court pack →',
    primaryProduct: 'complete_pack',
    primarySrc: 'section_21_court_pack',
    proofBullets: ['Notice plus court-stage workflow support', 'Evidence and witness-statement guidance', 'Practical DIY alternative to high drafting fees'],
    icon: '/images/wizard-icons/09-court.png',
    keyword: 'section 21 court pack',
    problemIntro: 'Landlords often manage to serve a notice, then stall at court preparation. Court forms, evidence order, and witness narrative all need to align.',
    intentDeepDive: 'This page is for landlords progressing beyond notice stage on the no-fault path. It focuses on joining up Form 6A history with N5B court prep so your file is coherent, service evidence is clean, and court-stage admin does not collapse under avoidable inconsistencies.',
    landlordScenarios: [
      'You served notice and now need a practical N5B-oriented bundle, not disconnected form downloads.',
      'You want notice-stage facts to carry cleanly into court paperwork without contradictions.',
      'You want a structured DIY route for straightforward cases before paying for full legal drafting.',
    ],
    mistakeRisks: ['Notice and court forms not matching each other', 'Weak evidence bundle structure', 'Missing key statements or service records', 'Filing delays from avoidable form mistakes'],
    templateRisks: ['Generic court form sites do not connect notice stage to court stage', 'No practical checklist of evidence gaps', 'No built workflow from facts to filing pack', 'Landlords are left stitching documents together manually'],
    solicitorPositioning: 'For defended or technical cases, solicitor representation can be important. For straightforward Section 21 possession prep, many landlords just want a coherent, affordable DIY pack.',
    whyLandlordHeaven: ['One route from notice stage into court-stage preparation', 'Forms and supporting documents are structured together', 'Built to reduce admin friction and rework', 'Faster and cheaper than paying for bespoke drafting in straightforward matters'],
    howItWorks: ['Complete guided case intake', 'Generate notice-aligned court document set', 'Review checklist and witness support outputs', 'Download pack and file with practical guidance'],
    included: ['Section 21 route notice documentation', 'N5B path support documents', 'Evidence checklist and witness statement draft support', 'Filing sequence guidance'],
    compliance: ['Route continuity checks between notice and court stage', 'Prompts for service evidence and chronology', 'Reminder checks around common filing blockers', 'Clarity on what still needs legal advice in complex cases'],
    comparisons: [
      { point: 'Document completeness', landlordHeaven: 'Notice + court workflow set', alternative: 'Single templates and manual patchwork' },
      { point: 'Cost', landlordHeaven: 'DIY one-time pack model', alternative: 'Higher solicitor drafting spend' },
      { point: 'Practical guidance', landlordHeaven: 'Step-led landlord flow', alternative: 'Minimal instructions from generic form sites' },
      { point: 'Consistency', landlordHeaven: 'Route-aligned outputs', alternative: 'Higher mismatch risk between documents' },
    ],
    faqs: [
      { question: 'Does this include N5B guidance?', answer: 'Yes, the pack is designed around the Section 21 route through to court-stage preparation, including N5B pathway support.' },
      { question: 'Is this better than downloading forms manually?', answer: 'For many landlords, yes. Forms alone do not provide workflow, cross-document consistency, or practical sequencing support.' },
      { question: 'Do I still need legal advice sometimes?', answer: 'Yes, especially if the case is defended, unusual, or legally complex.' },
      { question: 'Can I preview before buying?', answer: 'Yes. You can review key outputs first before completing purchase.' },
    ],
    relatedLinks: [
      { href: '/section-21-notice-generator', label: 'Start with Section 21 notice only' },
      { href: '/eviction-court-forms-england', label: 'Understand N5B and court forms context' },
      { href: '/complete-eviction-pack-england', label: 'See full complete eviction pack page' },
    ],
    finalCta: 'Build your Section 21 court pack',
  },
  'section-8-court-pack': {
    slug: 'section-8-court-pack',
    title: 'Section 8 Court Pack | Form 3 + N5/N119 Workflow',
    description: 'Build a Section 8 court pack for arrears or breach cases, connecting Form 3 notice with N5/N119 court-stage documents and practical guidance.',
    h1: 'Section 8 Court Pack for Arrears and Breach Cases',
    heroSubheadline: 'Link your Form 3 notice to the court stage in one practical workflow so you are not juggling disconnected templates and missed details.',
    heroCta: 'Start your Section 8 court pack →',
    primaryProduct: 'complete_pack',
    primarySrc: 'section_8_court_pack',
    proofBullets: ['Form 3 route into N5/N119 workflow', 'Built for arrears-focused landlord actions', 'Evidence-led process support'],
    icon: '/images/wizard-icons/15-rent-arrears.png',
    keyword: 'section 8 court pack',
    problemIntro: 'Arrears cases move fast and facts change quickly. If your notice and court paperwork do not match, you risk delay right when cashflow pressure is highest.',
    intentDeepDive: 'This page serves landlords who need the grounds-based route carried through to court prep. The practical job is to keep Form 3, arrears details, and N5/N119 paperwork aligned so avoidable admin mistakes do not slow possession further.',
    landlordScenarios: [
      'Arrears are ongoing and you need a route that links notice stage to court stage in one flow.',
      'You want N5/N119 support without manually stitching multiple template sources.',
      'You need a practical and affordable alternative to solicitor drafting for straightforward documentation.',
    ],
    mistakeRisks: ['Grounds and arrears schedules out of sync', 'Court forms missing key detail continuity', 'Weak documentation around service and chronology', 'Delayed possession from preventable admin errors'],
    templateRisks: ['Form libraries do not manage case flow continuity', 'No prompts for linking notice narrative to court narrative', 'No practical landlord checklist for evidence pack quality', 'Manual editing increases inconsistency risk'],
    solicitorPositioning: 'If your tenant defends heavily or disputes facts, legal representation may be wise. For straightforward arrears documentation, many landlords prefer a guided DIY pack first.',
    whyLandlordHeaven: ['Designed to keep notice and court documents aligned', 'Practical evidence and chronology support', 'Faster than managing disconnected manual forms', 'Clear middle ground between solicitor cost and template risk'],
    howItWorks: ['Capture arrears and breach details once', 'Generate route-aligned notice and court documents', 'Review evidence checklist and witness support', 'Download and continue with filing guidance'],
    included: ['Section 8 notice outputs (Form 3 route)', 'N5 and N119 pathway document support', 'Evidence and service checklist', 'Practical filing sequence notes'],
    compliance: ['Ground/arrears consistency reminders', 'Notice-to-court continuity prompts', 'Service-proof and record-keeping guidance', 'Boundary notes for legal-advice scenarios'],
    comparisons: [
      { point: 'Workflow continuity', landlordHeaven: 'Notice + court linked flow', alternative: 'Standalone forms with manual stitching' },
      { point: 'Landlord usability', landlordHeaven: 'Plain-English prompts', alternative: 'Legal-form heavy with little context' },
      { point: 'Turnaround', landlordHeaven: 'Fast generation and updates', alternative: 'Slow manual revisions' },
      { point: 'Error exposure', landlordHeaven: 'Guided checks and structure', alternative: 'Higher mismatch and omission risk' },
    ],
    faqs: [
      { question: 'Does this include court forms for Section 8?', answer: 'Yes, this route is built to support Section 8 cases into court-stage documentation including N5/N119 workflows.' },
      { question: 'Is this only for rent arrears?', answer: 'It is commonly used for arrears, but can also support other breach-based possession routes depending on your grounds.' },
      { question: 'Can this replace legal representation?', answer: 'No. It provides document generation and guidance, not representation. Complex defended matters may need a solicitor.' },
      { question: 'Why not just download free forms?', answer: 'Because free forms do not connect your route, evidence, and practical next steps. That gap is where many delays begin.' },
    ],
    relatedLinks: [
      { href: '/section-8-notice-generator', label: 'Section 8 notice generator' },
      { href: '/eviction-court-forms-england', label: 'Eviction court forms explained' },
      { href: '/complete-eviction-pack-england', label: 'See the full complete eviction workflow' },
    ],
    finalCta: 'Start your Section 8 court-ready flow',
  },
  'eviction-court-forms-england': {
    slug: 'eviction-court-forms-england',
    title: 'Eviction Court Forms England | N5, N119, N5B Guide',
    description: 'Understand eviction court forms in England (N5, N119, N5B) and when to use each route. Then move into a complete guided pack.',
    h1: 'Eviction Court Forms in England, Explained Simply',
    heroSubheadline: 'Looking for N5, N119, or N5B? Forms are only part of the job. Use this page to pick the right route and avoid costly filing resets.',
    heroCta: 'Start your complete court pack →',
    primaryProduct: 'complete_pack',
    primarySrc: 'eviction_court_forms_england',
    proofBullets: ['Clear explanation of N5, N119, and N5B', 'Route-focused guidance, not just form downloads', 'Direct handoff into complete pack workflow'],
    icon: '/images/wizard-icons/18-forms-bundle.png',
    keyword: 'eviction court forms england',
    problemIntro: 'Court forms are easy to find but hard to use correctly in context. The real challenge is knowing which form set matches your route and evidence.',
    intentDeepDive: 'This page targets form-intent searches that often convert poorly because users only see form names. The stronger angle is route context: when to use N5, N119, and N5B, what else is needed, and how to avoid form-only mistakes that delay your claim.',
    landlordScenarios: [
      'You searched for N5, N119, or N5B and need to know which path fits your case facts.',
      'You already downloaded forms but still feel unsure about route logic and supporting documents.',
      'You want a practical bundle workflow rather than filing isolated forms and hoping they line up.',
    ],
    mistakeRisks: ['Using the wrong possession claim path', 'Submitting forms with mismatched notice details', 'Missing supporting documents and chronology', 'Filing delays and additional court fees'],
    templateRisks: ['Generic form sites rarely explain route logic clearly', 'No practical guide from notice stage into claim stage', 'No integrated checklist for evidence readiness', 'Landlords can file incomplete packs without realising'],
    solicitorPositioning: 'Solicitor input can be helpful for defended claims and technical issues. For straightforward court-form preparation, many landlords just want structured guidance and coherent document sets.',
    whyLandlordHeaven: ['Explains route logic and then lets you act on it immediately', 'Combines form generation with practical supporting docs', 'Built for landlords managing real timelines and cashflow pressure', 'A practical middle ground between expensive legal drafting and risky form-only downloads'],
    howItWorks: ['Identify your notice route and court objective', 'Follow guided prompts to generate the right form path', 'Review court-stage checklist and supporting documents', 'Download and proceed with confidence'],
    included: ['Route-appropriate court form outputs', 'Supporting checklist and guidance documents', 'Notice-to-court continuity support', 'Practical reminders for filing stage'],
    compliance: ['Route/form mapping prompts', 'Cross-document consistency checks', 'Service evidence reminder blocks', 'Realistic disclaimers about complex-case legal advice'],
    comparisons: [
      { point: 'Forms understanding', landlordHeaven: 'Context + execution', alternative: 'Raw form files only' },
      { point: 'Document package', landlordHeaven: 'Forms plus support docs', alternative: 'No bundled workflow support' },
      { point: 'Time-to-action', landlordHeaven: 'Guided quick start', alternative: 'Manual research and drafting time' },
      { point: 'Practical landlord fit', landlordHeaven: 'Built around possession workflow', alternative: 'Government form navigation burden' },
    ],
    faqs: [
      { question: 'What is N5 used for?', answer: 'N5 is generally used for possession claims through routes that require that claim form, often alongside supporting forms depending on route.' },
      { question: 'When is N5B used?', answer: 'N5B is commonly associated with accelerated possession routes such as Section 21 pathways where eligibility criteria are met.' },
      { question: 'Is N119 always required?', answer: 'It depends on route. In many Section 8-style claims, N119 supports the particulars for rent arrears or breach context.' },
      { question: 'Are forms alone enough?', answer: 'Usually not. Route fit, evidence quality, consistency, and timing all influence whether your filing progresses smoothly.' },
    ],
    relatedLinks: [
      { href: '/section-21-court-pack', label: 'Section 21 court pack' },
      { href: '/section-8-court-pack', label: 'Section 8 court pack' },
      { href: '/complete-eviction-pack-england', label: 'Complete eviction pack for England' },
    ],
    finalCta: 'Get the right court forms workflow',
  },
  'complete-eviction-pack-england': {
    slug: 'complete-eviction-pack-england',
    title: 'Complete Eviction Pack England | Notice to Court Workflow',
    description: 'Get a complete England eviction pack from notice to court stage with guided document generation, evidence prompts, and practical landlord support.',
    h1: 'Complete Eviction Pack England',
    heroSubheadline: 'From the first notice to court-stage paperwork, get a practical end-to-end landlord workflow without paying solicitor drafting fees for every step.',
    heroCta: 'Start your complete eviction pack →',
    primaryProduct: 'complete_pack',
    primarySrc: 'complete_eviction_pack_england',
    proofBullets: ['Notice and court-stage documents in one flow', 'Built for straightforward landlord possession work', 'Guided pack with practical next-step structure'],
    icon: '/images/wizard-icons/07-review-finish.png',
    keyword: 'complete eviction pack england',
    problemIntro: 'Landlords lose momentum when each eviction stage is handled in separate tools. Notice drafting, court forms, evidence prep, and witness support should be connected.',
    intentDeepDive: 'This page is for high-intent landlords who want one complete possession workflow, not fragmented steps. The angle is end-to-end speed with structure: align notice and court paperwork, maintain evidence continuity, and reduce expensive restarts.',
    landlordScenarios: [
      'You want one route from first notice through court-ready pack preparation.',
      'You are done with patching templates and need a cleaner system for faster execution.',
      'You want a practical middle ground between DIY chaos and high solicitor drafting spend.',
    ],
    mistakeRisks: ['Switching between templates creates inconsistencies', 'Missed documents and weak evidence sequencing', 'Higher chance of restart costs and delay', 'Too much manual admin under time pressure'],
    templateRisks: ['Template banks are not full workflows', 'No integrated route logic from notice to court', 'No practical guardrails around common landlord errors', 'Manual editing burden increases risk and stress'],
    solicitorPositioning: 'Solicitors remain important where facts are disputed or the case is complex. But many straightforward cases do not need premium drafting costs at every step.',
    whyLandlordHeaven: ['One guided journey from notice through court preparation', 'Structured outputs designed to work together', 'Faster and more affordable than repeated bespoke drafting', 'Practical, landlord-first language and workflow design'],
    howItWorks: ['Start complete pack wizard with your case route', 'Generate notice, court forms, and support docs together', 'Review checklist and supporting guidance', 'Download and move forward with clearer next actions'],
    included: ['Notice pack for your chosen route', 'Court forms and supporting document workflow', 'Evidence checklist and witness support drafting', 'Service and filing guidance in one package'],
    compliance: ['Route-to-document continuity checks', 'Common blocker prompts before filing', 'Service and timeline reminders', 'Transparent legal-advice boundaries'],
    comparisons: [
      { point: 'Scope', landlordHeaven: 'End-to-end notice to court pack', alternative: 'One-off templates or isolated documents' },
      { point: 'Cost efficiency', landlordHeaven: 'Single guided workflow cost', alternative: 'Higher cumulative solicitor drafting spend' },
      { point: 'Landlord experience', landlordHeaven: 'Plain-English step flow', alternative: 'Fragmented legal-form process' },
      { point: 'Execution confidence', landlordHeaven: 'Checklists and guidance included', alternative: 'DIY uncertainty from form-only tools' },
    ],
    faqs: [
      { question: 'Who is this complete pack best for?', answer: 'Landlords in England who want a practical notice-to-court workflow and do not want to stitch forms manually across multiple websites.' },
      { question: 'Does this replace legal advice?', answer: 'No. It provides document generation and guidance. Complex, defended, or unusual matters may still require legal advice.' },
      { question: 'Can I start with notice only then upgrade?', answer: 'Yes, many landlords start with notice drafting and move to complete pack when court stage becomes likely.' },
      { question: 'Why not just use free templates?', answer: 'Because free templates usually do not validate route fit, maintain cross-document consistency, or guide practical next steps.' },
    ],
    relatedLinks: [
      { href: '/section-21-court-pack', label: 'Section 21 court pack route' },
      { href: '/section-8-court-pack', label: 'Section 8 court pack route' },
      { href: '/eviction-court-forms-england', label: 'Understand court forms first' },
    ],
    finalCta: 'Start your full eviction workflow',

  },
  'how-to-evict-a-tenant-england': {
    slug: 'how-to-evict-a-tenant-england',
    title: 'How to Evict a Tenant in England | Landlord Step-by-Step Guide',
    description: 'Learn the eviction process in England step by step. Compare Section 21 and Section 8 routes, avoid invalid notices, and choose the right next move.',
    h1: 'How to Evict a Tenant in England: Step by Step',
    heroSubheadline: 'Need a practical landlord walkthrough? This guide shows the process from first notice to court stage, and how to avoid expensive restarts.',
    heroCta: 'Start the right notice route →',
    secondaryCta: { label: 'Need full notice-to-court support? →', product: 'complete_pack', src: 'how_to_evict_a_tenant_england' },
    primaryProduct: 'notice_only',
    primarySrc: 'how_to_evict_a_tenant_england',
    proofBullets: ['Explains Section 21 vs Section 8 in plain English', 'Highlights where landlords lose time and rent', 'Shows when to use notice-only vs complete pack'],
    icon: '/images/wizard-icons/11-calendar-timeline.png',
    keyword: 'how to evict a tenant england',
    problemIntro: 'Most landlords do not get stuck because they cannot find a form. They get stuck because they are unsure which route to start, what evidence they need, and what happens after the notice expires.',
    intentDeepDive: 'This page targets broad guidance intent and acts as the top-of-cluster authority page. The goal is to move users from confusion into the right action path: Section 21, Section 8, or complete court pack workflow.',
    landlordScenarios: [
      'You need possession quickly but are unsure whether no-fault or grounds-based route fits best.',
      'The tenant is not leaving and you want a practical sequence without paying for full legal drafting upfront.',
      'You want one guide that explains notices, service, and court progression in plain landlord language.',
    ],
    mistakeRisks: ['Starting on the wrong notice route', 'Serving invalid paperwork and having to restart', 'Missing service evidence needed later in court', 'Losing additional rent while timelines drift'],
    templateRisks: ['Generic guide sites often stop at “download this form”', 'No route validation for your specific facts', 'No compliance checks before generation', 'No structured next-step workflow after service'],
    solicitorPositioning: 'Solicitors are still important for defended or unusual disputes. But for straightforward starting paperwork, many landlords simply need the right route and a practical, guided workflow first.',
    whyLandlordHeaven: ['Starts with route clarity, then generates the right documents', 'Combines notice prep with practical service guidance', 'Lets you move into complete pack when court stage is likely', 'Built for landlord execution, not abstract legal theory'],
    howItWorks: ['Choose your case direction: Section 21, Section 8, or full pack', 'Complete guided questions based on your route', 'Preview and verify key details before finalising', 'Download documents and follow next-step guidance'],
    included: ['Route-specific notice workflows', 'Service and validity checklist support', 'Internal handoff to complete pack routes', 'Regeneration if your facts change'],
    compliance: ['Route-eligibility prompts', 'Core document consistency checks', 'Service-proof reminders', 'Clear disclaimer boundaries for legal advice'],
    comparisons: [
      { point: 'Route clarity', landlordHeaven: 'Guided decision flow', alternative: 'Manual interpretation of generic guidance' },
      { point: 'Execution speed', landlordHeaven: 'Start immediately', alternative: 'Slow form hunting and manual setup' },
      { point: 'Practical support', landlordHeaven: 'Checklist-driven process', alternative: 'Template-only with little context' },
      { point: 'Cost profile', landlordHeaven: 'Lower-cost DIY workflow', alternative: 'Higher solicitor drafting spend for simple starts' },
    ],
    faqs: [
      { question: 'What is the first step in evicting a tenant in England?', answer: 'The first step is choosing the correct notice route for your facts, usually Section 21 or Section 8. Route choice affects everything that follows.' },
      { question: 'Can I evict without going to court?', answer: 'If a tenant leaves after valid notice, court may not be needed. If they stay, most possession routes require court-stage progression.' },
      { question: 'Is a free template enough to start?', answer: 'It can show structure, but it usually does not validate route fit, compliance blockers, or next-step workflow.' },
      { question: 'When should I use complete pack instead of notice only?', answer: 'Use complete pack when court progression is likely and you want notice plus court-stage workflow support in one flow.' },
    ],
    relatedLinks: [
      { href: '/section-21-notice-generator', label: 'Section 21 notice generator' },
      { href: '/section-8-notice-generator', label: 'Section 8 notice generator' },
      { href: '/complete-eviction-pack-england', label: 'Complete eviction pack for England' },
    ],
    finalCta: 'Start the right eviction route now',
  },
  'section-21-checklist': {
    slug: 'section-21-checklist',
    title: 'Section 21 Checklist for Landlords | Compliance Before Service',
    description: 'Use this Section 21 checklist to avoid invalid notices. Cover deposit protection, EPC, gas safety, How to Rent, and service essentials before serving.',
    h1: 'Section 21 Checklist: Serve It Right First Time',
    heroSubheadline: 'Before you serve Form 6A, run this practical compliance checklist so you do not lose weeks to avoidable notice failures.',
    heroCta: 'Start your Section 21 notice →',
    primaryProduct: 'notice_only',
    primarySrc: 'section_21_checklist',
    proofBullets: ['Covers key Section 21 compliance blockers', 'Shows why invalid notices fail at court stage', 'Guides you into the Section 21 generator'],
    icon: '/images/wizard-icons/05-compliance.png',
    keyword: 'section 21 checklist',
    problemIntro: 'Section 21 failures usually happen before service. Landlords miss one compliance step, serve anyway, and only discover the issue when possession is delayed.',
    intentDeepDive: 'This page serves compliance-checklist intent. It is designed to help landlords validate pre-conditions before serving, then move directly into a guided Section 21 generation flow.',
    landlordScenarios: [
      'You are ready to serve but unsure if your compliance file is complete.',
      'You served before and got challenged on paperwork quality.',
      'You want a practical pre-service checklist instead of piecing rules from multiple websites.',
    ],
    mistakeRisks: ['Deposit requirements not evidenced properly', 'Missing EPC, gas safety, or How to Rent records', 'Serving before route timing allows it', 'Weak service proof for court stage'],
    templateRisks: ['Generic checklists can be outdated', 'No checks linked to your live notice draft', 'No route-specific workflow guidance', 'No practical bridge from checklist to generation'],
    solicitorPositioning: 'Solicitors can help where disputes are complex. For straightforward Section 21 starts, many landlords mainly need an accurate checklist and a guided way to generate documents correctly.',
    whyLandlordHeaven: ['Checklist logic sits inside the notice workflow', 'Prevents common invalidity triggers before service', 'Lets you regenerate fast if details change', 'Designed to reduce restart risk and lost rent time'],
    howItWorks: ['Review checklist requirements in plain language', 'Complete guided inputs for Section 21 route', 'Validate details and preview your documents', 'Generate and serve with clearer confidence'],
    included: ['Section 21 notice generation support', 'Service and validity checklist prompts', 'Compliance reminders tied to your route', 'Practical next-step guidance'],
    compliance: ['Deposit protection checks', 'EPC and gas safety reminders', 'How to Rent provision prompts', 'Service process and evidence prompts'],
    comparisons: [
      { point: 'Checklist quality', landlordHeaven: 'Route-aware and workflow-linked', alternative: 'Static checklist with no generation context' },
      { point: 'Error prevention', landlordHeaven: 'Built into document prep flow', alternative: 'Manual cross-checking' },
      { point: 'Speed', landlordHeaven: 'Checklist to generation in one path', alternative: 'Switching tools and templates' },
      { point: 'Cost', landlordHeaven: 'Practical DIY approach', alternative: 'Paying for basic drafting/admin steps' },
    ],
    faqs: [
      { question: 'What can invalidate a Section 21 notice?', answer: 'Common invalidity triggers include missing compliance pre-conditions, incorrect timing, wrong service process, or inconsistent paperwork.' },
      { question: 'Do I need all compliance documents before serving?', answer: 'You should ensure relevant requirements for your case are satisfied before serving to avoid invalidity challenges.' },
      { question: 'Is this legal advice?', answer: 'No. Landlord Heaven provides document generation and practical guidance, not legal advice or court representation.' },
      { question: 'What if I am unsure my case is straightforward?', answer: 'Use the guided flow for practical checks, and seek legal advice if your case is unusual or likely to be defended.' },
    ],
    relatedLinks: [
      { href: '/section-21-notice-generator', label: 'Generate your Section 21 notice' },
      { href: '/section-21-court-pack', label: 'Need court progression? Section 21 court pack' },
      { href: '/section-21-vs-section-8', label: 'Not sure about route? Compare Section 21 vs Section 8' },
    ],
    finalCta: 'Run the checks and generate your Section 21',
  },
  'section-8-rent-arrears-eviction': {
    slug: 'section-8-rent-arrears-eviction',
    title: 'Section 8 Rent Arrears Eviction | Landlord Route Guide',
    description: 'Evict for rent arrears using Section 8 with practical guidance on grounds, notice details, and court progression to N5/N119 where needed.',
    h1: 'Section 8 Rent Arrears Eviction: Practical Landlord Guide',
    heroSubheadline: 'If arrears are growing, this guide shows the grounds-based route from notice stage to court progression without template guesswork.',
    heroCta: 'Start your Section 8 notice →',
    secondaryCta: { label: 'Need court forms too? Start Section 8 court pack →', product: 'complete_pack', src: 'section_8_rent_arrears_eviction' },
    primaryProduct: 'notice_only',
    primarySrc: 'section_8_rent_arrears_eviction',
    proofBullets: ['Focused on rent arrears and breach route', 'Explains notice and court handoff clearly', 'Shows when to switch to complete pack'],
    icon: '/images/wizard-icons/15-rent-arrears.png',
    keyword: 'section 8 rent arrears eviction',
    problemIntro: 'Arrears cases get expensive fast when route details are wrong. If grounds, dates, and evidence are not aligned, landlords can lose more rent while fixing paperwork.',
    intentDeepDive: 'This page targets arrears-eviction intent and clarifies the full grounds-based path: correct notice setup, practical service, and court-stage progression if the tenant does not remedy or leave.',
    landlordScenarios: [
      'The tenant owes several months and you need a valid route now, not another delay.',
      'You are unsure which grounds and evidence structure are appropriate for your case.',
      'You expect court action and want a workflow that keeps notice and court documents aligned.',
    ],
    mistakeRisks: ['Grounds selected without matching evidence', 'Arrears timeline inconsistencies', 'Wrong notice assumptions and service errors', 'Court-stage delays caused by weak document continuity'],
    templateRisks: ['Template sites do not guide grounds strategy', 'No consistency checks between notice and court docs', 'No practical service/evidence workflow', 'High risk of manual admin errors'],
    solicitorPositioning: 'Solicitors are often sensible for defended arrears disputes. For straightforward document preparation stages, many landlords prefer a guided DIY flow first to move faster and cheaper.',
    whyLandlordHeaven: ['Grounds-based workflow in plain English', 'Practical progression from notice to court prep', 'Regeneration support when arrears figures change', 'Cleaner execution than disconnected templates'],
    howItWorks: ['Capture arrears facts and route context', 'Generate Section 8 notice documents', 'Follow service and evidence checklist guidance', 'Move into Section 8 court pack when needed'],
    included: ['Section 8 notice generation support', 'Service and validity checklist', 'Arrears-focused route guidance', 'Handoff into N5/N119-ready workflow'],
    compliance: ['Ground/evidence alignment reminders', 'Date and service consistency prompts', 'Core route-to-court continuity checks', 'Clarity around when legal advice may be needed'],
    comparisons: [
      { point: 'Arrears route clarity', landlordHeaven: 'Guided and structured', alternative: 'Manual interpretation of grounds' },
      { point: 'Notice-to-court continuity', landlordHeaven: 'Connected workflow', alternative: 'Template patchwork' },
      { point: 'Admin burden', landlordHeaven: 'Single process', alternative: 'Multiple disconnected sources' },
      { point: 'Cost/speed balance', landlordHeaven: 'Practical DIY middle ground', alternative: 'Higher legal drafting cost for routine setup' },
    ],
    faqs: [
      { question: 'Is Section 8 the main route for rent arrears?', answer: 'Section 8 is commonly used for arrears and other breaches, with route details depending on your grounds and facts.' },
      { question: 'What happens after a Section 8 notice expires?', answer: 'If the issue is unresolved and tenant remains, many cases progress to court-stage possession claim paperwork.' },
      { question: 'Can I use templates for arrears cases?', answer: 'You can, but templates alone often miss route validation, chronology consistency, and practical next-step guidance.' },
      { question: 'When should I switch to complete pack?', answer: 'Switch when court progression is likely and you want notice plus court documents in one coherent workflow.' },
    ],
    relatedLinks: [
      { href: '/section-8-notice-generator', label: 'Section 8 notice generator' },
      { href: '/section-8-court-pack', label: 'Section 8 court pack' },
      { href: '/eviction-court-forms-england', label: 'Understand N5/N119 form routes' },
    ],
    finalCta: 'Start your arrears eviction route now',
  },
  'n5b-possession-claim-form': {
    slug: 'n5b-possession-claim-form',
    title: 'N5B Possession Claim Form Guide | Accelerated Route Help',
    description: 'Understand the N5B possession claim form, when it is used, and how to prepare a coherent Section 21 court-stage bundle without form-only mistakes.',
    h1: 'N5B Possession Claim Form: What Landlords Need to Know',
    heroSubheadline: 'Searching for N5B? This guide explains when it applies and why form-only downloads often create avoidable delays.',
    heroCta: 'Start your Section 21 court pack →',
    primaryProduct: 'complete_pack',
    primarySrc: 'n5b_possession_claim_form',
    proofBullets: ['Explains N5B in plain landlord language', 'Clarifies where form-only approaches fail', 'Direct route into Section 21 court pack'],
    icon: '/images/wizard-icons/09-court.png',
    keyword: 'n5b possession claim form',
    problemIntro: 'Landlords searching N5B usually need action fast, but the form alone is not the full solution. The route succeeds when notice history, service proof, and supporting docs are coherent.',
    intentDeepDive: 'This page is a form-intent authority page. It captures N5B queries and moves users toward the Section 21 court-pack workflow where form generation, document consistency, and practical guidance are connected.',
    landlordScenarios: [
      'You have served Section 21 and now need to prepare accelerated possession paperwork.',
      'You found N5B online but are unsure what else must line up for a strong file.',
      'You want a practical DIY route before paying for bespoke legal drafting in a straightforward case.',
    ],
    mistakeRisks: ['Treating N5B as a standalone task', 'Submitting inconsistent details from notice stage', 'Weak service records and chronology gaps', 'Delay from missing supporting documents'],
    templateRisks: ['Form libraries rarely explain route context', 'No validation of notice-to-court continuity', 'No workflow for supporting evidence prep', 'Higher chance of filing gaps and rework'],
    solicitorPositioning: 'Legal advice remains valuable if your case is defended or unusual. For straightforward accelerated-route document preparation, many landlords seek a faster guided workflow first.',
    whyLandlordHeaven: ['N5B path support tied to notice-stage context', 'Documents are prepared as one coherent pack', 'Practical landlord-first guidance on execution order', 'Middle ground between expensive drafting and risky form-only DIY'],
    howItWorks: ['Confirm your route context and case details', 'Generate aligned court-stage documents', 'Use checklist support for service/evidence consistency', 'Download and proceed with clearer filing confidence'],
    included: ['N5B-oriented court route support', 'Notice-to-court consistency prompts', 'Evidence and service checklist guidance', 'Practical next-step instructions'],
    compliance: ['Route-fit reminders', 'Cross-document consistency checks', 'Service-proof prompts', 'Boundaries for when to seek legal advice'],
    comparisons: [
      { point: 'Form context', landlordHeaven: 'Explained + actioned', alternative: 'Raw form with minimal guidance' },
      { point: 'Workflow quality', landlordHeaven: 'Connected document preparation', alternative: 'Manual stitching from multiple sites' },
      { point: 'Speed to action', landlordHeaven: 'Guided route', alternative: 'Research-heavy DIY process' },
      { point: 'Error risk', landlordHeaven: 'Checklist-driven', alternative: 'Higher omission risk' },
    ],
    faqs: [
      { question: 'What is the N5B form used for?', answer: 'N5B is commonly associated with accelerated possession claim routes where eligibility criteria are met.' },
      { question: 'Is N5B enough by itself?', answer: 'Usually no. Supporting documents, service evidence, and route consistency are also important.' },
      { question: 'Can I avoid solicitor costs with a guided workflow?', answer: 'For many straightforward preparation stages, yes. Complex or defended cases may still require legal advice.' },
      { question: 'Which product should I use from here?', answer: 'If you are progressing through the Section 21 court stage, Section 21 court pack and complete pack routes are usually the best fit.' },
    ],
    relatedLinks: [
      { href: '/section-21-court-pack', label: 'Section 21 court pack' },
      { href: '/complete-eviction-pack-england', label: 'Complete eviction pack England' },
      { href: '/eviction-court-forms-england', label: 'Compare N5B with other court forms' },
    ],
    finalCta: 'Build your N5B-ready court pack',
  },
  'n5-n119-possession-claim': {
    slug: 'n5-n119-possession-claim',
    title: 'N5 and N119 Possession Claim Guide | Landlord Court Forms',
    description: 'Learn when to use N5 and N119 possession claim forms and how to prepare a coherent Section 8 court-route bundle with fewer filing mistakes.',
    h1: 'N5 and N119 Possession Claim: Landlord Practical Guide',
    heroSubheadline: 'Looking for N5 and N119? This guide explains when they apply and how to avoid form-only mistakes that delay arrears cases.',
    heroCta: 'Start your Section 8 court pack →',
    primaryProduct: 'complete_pack',
    primarySrc: 'n5_n119_possession_claim',
    proofBullets: ['Explains N5/N119 route context', 'Built for arrears/breach court progression', 'Direct handoff into Section 8 court pack'],
    icon: '/images/wizard-icons/18-forms-bundle.png',
    keyword: 'n5 n119 possession claim',
    problemIntro: 'Many landlords find N5 and N119 quickly but struggle with the bigger issue: linking notice-stage facts, arrears chronology, and supporting docs into a coherent court file.',
    intentDeepDive: 'This page captures court-form intent for grounds-based claims. The practical objective is to convert users from “which form do I download?” into a complete Section 8 court workflow that reduces avoidable admin errors.',
    landlordScenarios: [
      'You are preparing a possession claim after a Section 8 route and need N5/N119 context.',
      'You want to avoid mismatched arrears details across forms and evidence.',
      'You need a practical alternative to piecing together blank forms manually.',
    ],
    mistakeRisks: ['Using N5/N119 without route continuity checks', 'Arrears figures inconsistent across documents', 'Missing supporting evidence detail', 'Court delay from incomplete or conflicting paperwork'],
    templateRisks: ['Form sites provide little process guidance', 'No linked workflow from notice to claim forms', 'No reminders for supporting pack quality', 'Higher risk of rejection or rework'],
    solicitorPositioning: 'Solicitor support can be valuable in defended arrears cases. For straightforward court-form preparation, many landlords prefer guided DIY workflows to control speed and cost.',
    whyLandlordHeaven: ['Section 8 court pack ties forms to route context', 'Helps align notice, arrears, and claim details', 'Provides practical execution structure', 'Balanced alternative to high-fee drafting for routine prep'],
    howItWorks: ['Capture case details once', 'Generate N5/N119-oriented workflow outputs', 'Review checklist and consistency prompts', 'Download and proceed with clearer filing steps'],
    included: ['N5/N119 court route support', 'Arrears-focused consistency prompts', 'Evidence and service guidance', 'Practical next-stage instructions'],
    compliance: ['Route/form alignment reminders', 'Cross-document consistency checks', 'Service and chronology prompts', 'Clarity on complex-case legal advice needs'],
    comparisons: [
      { point: 'Form clarity', landlordHeaven: 'Explains when/why each form is used', alternative: 'Download page with little context' },
      { point: 'Case consistency', landlordHeaven: 'Guided workflow', alternative: 'Manual reconciliation' },
      { point: 'Landlord usability', landlordHeaven: 'Plain-English execution path', alternative: 'Legal-form heavy process' },
      { point: 'Cost/speed', landlordHeaven: 'Practical DIY middle ground', alternative: 'Higher drafting cost or slower manual process' },
    ],
    faqs: [
      { question: 'What do N5 and N119 forms do?', answer: 'They are commonly used in possession claim routes where landlords need to present claim details and supporting particulars for arrears/breach context.' },
      { question: 'Are N5 and N119 enough without other documents?', answer: 'Usually not. Supporting evidence, service records, and route consistency are typically needed.' },
      { question: 'Should I still get legal advice?', answer: 'If your case is defended, unusual, or high-risk, legal advice may still be sensible.' },
      { question: 'Where should I start if I am unsure?', answer: 'Use the Section 8 court pack flow for guided form context, then move to complete pack if you want broader notice-to-court continuity.' },
    ],
    relatedLinks: [
      { href: '/section-8-court-pack', label: 'Section 8 court pack' },
      { href: '/complete-eviction-pack-england', label: 'Complete eviction pack England' },
      { href: '/eviction-court-forms-england', label: 'Broader court forms guide' },
    ],
    finalCta: 'Start your N5/N119-ready workflow',
  },
  'eviction-timeline-england': {
    slug: 'eviction-timeline-england',
    title: 'Eviction Timeline England | How Long Possession Can Take',
    description: 'Understand the eviction timeline in England from notice to court stage, common delay points, and how to reduce wasted time with the right workflow.',
    h1: 'Eviction Timeline England: What Actually Slows Cases Down',
    heroSubheadline: 'Want realistic timing? This page breaks down each stage and shows how paperwork mistakes can add months of avoidable delay.',
    heroCta: 'Start your eviction notice flow →',
    secondaryCta: { label: 'Need full timeline support? Start complete pack →', product: 'complete_pack', src: 'eviction_timeline_england' },
    primaryProduct: 'notice_only',
    primarySrc: 'eviction_timeline_england',
    proofBullets: ['Explains timeline by stage in plain language', 'Shows the delay cost of invalid paperwork', 'Routes users to notice-only or complete pack'],
    icon: '/images/wizard-icons/11-calendar-timeline.png',
    keyword: 'eviction timeline england',
    problemIntro: 'Landlords often ask “how long does eviction take?” but the answer depends on route quality, service quality, and whether your paperwork survives scrutiny the first time.',
    intentDeepDive: 'This page targets timeline intent and reframes speed around execution quality. It guides landlords to the right workflow so they reduce avoidable delay rather than just searching average timeline numbers.',
    landlordScenarios: [
      'You need possession planning clarity for rent-loss and cashflow decisions.',
      'You want to know which mistakes add the biggest avoidable delays.',
      'You need a practical route to start now and avoid timeline resets later.',
    ],
    mistakeRisks: ['Wrong notice route or invalid service', 'Missing compliance records that undermine notice validity', 'Weak chronology/evidence pack for court stage', 'Restarting process after avoidable rejection issues'],
    templateRisks: ['Timeline articles often omit route validation reality', 'No linked workflow to act on guidance', 'No practical checks that reduce delay risk', 'No next-step continuity from notice to court'],
    solicitorPositioning: 'Solicitors can be crucial for complex or defended cases. For straightforward first-stage paperwork, many landlords prioritise a guided process that protects timeline momentum at lower cost.',
    whyLandlordHeaven: ['Focuses on reducing delay risk, not just explaining theory', 'Guides route choice and document preparation together', 'Supports quick transitions from notice to complete pack', 'Designed to keep landlord timelines moving'],
    howItWorks: ['Choose the correct route for your case facts', 'Generate notice-stage documents with checks', 'Serve with better process and evidence discipline', 'Move to complete pack for court progression when needed'],
    included: ['Route-specific notice workflow support', 'Delay-prevention checklist prompts', 'Court-stage handoff paths', 'Practical process guidance'],
    compliance: ['Route and timing prompts', 'Service and record-keeping reminders', 'Cross-document consistency checks', 'Clear legal-advice boundary notes'],
    comparisons: [
      { point: 'Timeline focus', landlordHeaven: 'Execution-first delay reduction', alternative: 'Generic timeline ranges only' },
      { point: 'Actionability', landlordHeaven: 'Direct wizard handoff', alternative: 'No practical next-step flow' },
      { point: 'Risk control', landlordHeaven: 'Checklist and validation prompts', alternative: 'High DIY guesswork' },
      { point: 'Cost efficiency', landlordHeaven: 'Practical DIY middle path', alternative: 'High drafting spend for routine setup' },
    ],
    faqs: [
      { question: 'How long does eviction take in England?', answer: 'Timelines vary by route, tenant response, and court conditions. The biggest controllable factor is avoiding invalid paperwork and service mistakes that force restarts.' },
      { question: 'What causes the biggest delays?', answer: 'Wrong route choice, invalid notices, weak service evidence, and inconsistent court paperwork are common delay drivers.' },
      { question: 'Can a guided workflow speed things up?', answer: 'A guided workflow cannot control court capacity, but it can reduce avoidable admin errors that often add months.' },
      { question: 'Which product should I start with?', answer: 'Use notice-only for first-stage setup, and complete pack when court progression is likely or you want end-to-end workflow support.' },
    ],
    relatedLinks: [
      { href: '/eviction-notice-england', label: 'Choose the right England notice route' },
      { href: '/complete-eviction-pack-england', label: 'Complete eviction pack England' },
      { href: '/section-21-vs-section-8', label: 'Compare Section 21 vs Section 8' },
    ],
    finalCta: 'Protect your timeline and start now',
  },
};

export function getWizardHref(config: IntentPageConfig, product?: IntentProduct, srcOverride?: string) {
  const targetProduct = product ?? config.primaryProduct;
  const src = srcOverride ?? config.primarySrc;
  return targetProduct === 'notice_only' ? noticeWizard(src) : completeWizard(src);
}

export function getIntentPageMetadata(config: IntentPageConfig): Metadata {
  const canonical = getCanonicalUrl(`/${config.slug}`);
  const imageUrl = getCanonicalUrl('/og-image.png');

  return {
    title: config.title,
    description: config.description,
    alternates: { canonical },
    openGraph: {
      title: config.title,
      description: config.description,
      url: canonical,
      type: 'website',
      images: [{ url: imageUrl }],
    },
    twitter: {
      card: 'summary_large_image',
      title: config.title,
      description: config.description,
      images: [imageUrl],
    },
  };
}
