import type { FAQItem } from '@/components/seo/FAQSection';
import type { IntentSection } from '@/components/seo/HighIntentPageShell';

export interface Pass1LongformPage {
  slug: string;
  title: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  icon: string;
  heroBullets: string[];
  primaryCta: { label: string; href: string };
  secondaryCta: { label: string; href: string };
  relatedLinks: Array<{ label: string; href: string }>;
  sections: IntentSection[];
  faqs: FAQItem[];
}

function buildSections(topic: string, points: string[], extra: string): IntentSection[] {
  const intro: IntentSection = {
    title: `${topic}: start with a controlled case strategy`,
    paragraphs: [
      `Landlords usually lose time on ${topic.toLowerCase()} files because they jump to the next legal step before building a coherent chronology. In practical terms, the file needs one working timeline, one evidence index, and one route logic note that explains why each action was taken. That discipline matters for every stage: notice, claim issue, witness statement, hearing, and enforcement. A coherent file is faster to manage, easier to defend, and less likely to be delayed by contradictions that were avoidable at the start.`,
      `The commercial objective should be explicit. You are deciding how to recover control of the property, reduce ongoing loss, and protect against future challenge. When this objective is written down at the beginning, every decision can be tested against it: does this step improve legal position, improve recoverability, or reduce procedural risk? If the answer is no, do not do it. ${extra}`,
      `This guide is structured as an execution blueprint rather than a checklist. Each section explains what evidence to gather, what mistakes commonly break momentum, and how to align product choice with case stage. Use Notice Only when your route is clear and you need compliant first-step documentation quickly. Use Complete Pack when you need continuity through court and want one workflow from notice through hearing prep.`
    ]
  };

  const body = points.map((point) => ({
    title: point,
    paragraphs: [
      `${point} should be treated as a decision gateway, not a box-tick. The practical question is what must be true before you move forward. That means recording facts, preserving service evidence, and noting what could challenge your position later. Good landlords make this explicit in writing: current facts, missing evidence, and next action deadline. This avoids reactive case management and creates a defensible narrative if the tenant disputes the chronology.`,
      `At this stage, combine legal and operational controls. Legal controls include route eligibility checks, service method confirmation, and date integrity. Operational controls include diary triggers, document naming standards, contractor coordination where relevant, and communication templates that stay factual. If there is any change in tenant behaviour, such as partial payment or last-minute cooperation, update the file immediately and reassess route strength before advancing.`,
      `Most failed files do not fail because the issue was weak; they fail because the story became inconsistent between documents. Keep one master version of events and reconcile all letters, schedules, and statements to it. When you present the file later, the decision trail should show proportionate conduct, clear warnings, and practical opportunities for resolution before escalation.`
    ]
  }));

  const close: IntentSection = {
    title: `Execution model for ${topic.toLowerCase()} cases`,
    paragraphs: [
      `Run every case through a simple stage model: detection, verification, route decision, compliant service, monitoring, court readiness, and enforcement planning. Each stage should have an owner, a deadline, and a quality check. This turns eviction work from ad hoc problem-solving into a repeatable process. Portfolio landlords benefit most because multiple active files can be triaged consistently instead of being handled by urgency alone.`,
      `Before moving to court, perform a contradiction audit. Confirm names, dates, tenancy terms, arrears or loss calculations, notice details, and service proof. If anything changed after notice, explain it transparently and update schedules. This one review step prevents a large proportion of hearing-day setbacks.`,
      `After possession or resolution, close the loop: final account reconciliation, recovery decision, lessons learned, and process update. The goal of this page is not only to help with one dispute, but to reduce repeat losses across future tenancies by improving standards at each stage.`
    ],
    bullets: [
      'Use product-first routing: Notice Only for clear route starts, Complete Pack for end-to-end continuity.',
      'Keep communication factual, dated, and linked to evidence in your chronology.',
      'Treat every service or filing step as evidence generation, not mere administration.'
    ]
  };

  return [intro, ...body, close];
}

function buildFaqs(topic: string, points: string[]): FAQItem[] {
  return points.slice(0, 8).map((point) => ({
    question: `${topic}: ${point.toLowerCase()} — what should landlords do first?`,
    answer: `Start with evidence and chronology before escalation. For ${point.toLowerCase()}, record the current facts, identify missing proof, and document the decision path for your next legal step. Keep notices, service records, and communications aligned to one timeline. Landlords who do this early usually avoid procedural resets, while landlords who improvise often add delay and increase challenge risk.`
  })).concat({
    question: `${topic}: should I use a wizard flow first?`,
    answer: 'For these guides, the primary route is product-first. Begin with Notice Only when legal route certainty exists and you need compliant documents at speed. Move to Complete Pack when continuity into court, hearing prep, and enforcement planning is required. That sequencing keeps execution aligned with case stage and avoids premature route lock-in.'
  });
}

function createPage(input: Omit<Pass1LongformPage, 'sections' | 'faqs'> & { points: string[]; extra: string }): Pass1LongformPage {
  return {
    ...input,
    sections: buildSections(input.heroTitle, input.points, input.extra),
    faqs: buildFaqs(input.heroTitle, input.points),
  };
}

export const PASS1_LONGFORM_PAGES: Record<string, Pass1LongformPage> = {
  'tenant-stopped-paying-rent': createPage({ slug: 'tenant-stopped-paying-rent', title: 'Tenant Stopped Paying Rent: Arrears Recovery and Possession Blueprint', description: 'Long-form arrears strategy guide covering route selection, partial payments, evidence control, notice service quality, and post-possession debt recovery.', heroTitle: 'Tenant Stopped Paying Rent: Arrears Recovery and Possession Blueprint', heroSubtitle: 'Detailed landlord workflow for route selection, partial-payment risk control, evidence discipline, and escalation timing.', icon: '/images/wizard-icons/06-notice-details.png', heroBullets: ['Arrears route selection under unstable payment behaviour', 'Partial-payment scenarios and threshold risk controls', 'Evidence checklist, escalation timeline, and post-possession planning'], primaryCta: { label: 'Start Notice Only for arrears', href: '/products/notice-only?src=stopped_paying_rent_notice' }, secondaryCta: { label: 'Need court continuity? Use Complete Pack', href: '/products/complete-pack?src=stopped_paying_rent_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long eviction takes', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], points: ['Arrears route selection and decision gates', 'Partial-payment scenarios and ledger controls', 'Evidence checklist before serving notice', 'Timeline of escalation from first miss to hearing', 'Notice service mistakes that cause delay', 'Section 8 vs money claim decision logic', 'What happens after possession for debt recovery', 'Advanced FAQs for contested arrears files'], extra: 'In arrears cases, the biggest avoidable risk is assuming the mandatory threshold will hold without testing partial-payment behaviour before key dates.' }),
  'tenant-abandoned-property': createPage({ slug: 'tenant-abandoned-property', title: 'Tenant Abandoned Property: Safe Re-entry and Legal Control Plan', description: 'Detailed landlord guide on abandonment warning signs, evidence standards, lawful re-entry risk, belongings handling, arrears recovery, and common mistakes.', heroTitle: 'Tenant Abandoned Property: Safe Re-entry and Legal Control Plan', heroSubtitle: 'Build legal certainty before re-entry with evidence layering, notice workflow, and lawful belongings handling.', icon: '/images/wizard-icons/02-property-address.png', heroBullets: ['Abandonment warning signs and verification controls', 'Lawful re-entry risk reduction before possession action', 'Belongings, inventory, notice handling, and arrears recovery'], primaryCta: { label: 'Start Notice Only workflow', href: '/products/notice-only?src=abandoned_property_notice' }, secondaryCta: { label: 'Need full court continuity? Complete Pack', href: '/products/complete-pack?src=abandoned_property_complete' }, relatedLinks: [{ label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }], points: ['Abandonment warning signs and false positives', 'Lawful re-entry risk and unlawful eviction exposure', 'Evidence required before treating as abandoned', 'Handling belongings, inventory, and notices', 'Rent arrears recovery route after abandonment', 'Common landlord mistakes in abandonment files', 'Operational timeline for checks and escalation', 'Deeper FAQs for reappearance and challenge risk'], extra: 'The core risk is not empty rooms; it is acting as if certainty exists when the legal position is still ambiguous.' }),
  'tenant-refusing-access': createPage({ slug: 'tenant-refusing-access', title: 'Tenant Refusing Access: Enforcement Without Harassment Risk', description: 'Long-form landlord guide on access attempt logs, urgent repair escalation, gas safety implications, injunction positioning, and notice decisions.', heroTitle: 'Tenant Refusing Access: Enforcement Without Harassment Risk', heroSubtitle: 'Use structured access logs, repair evidence, and proportionate escalation when entry is repeatedly denied.', icon: '/images/wizard-icons/10-document-review.png', heroBullets: ['Access attempt logs and communication standards', 'Urgent repair and gas safety escalation controls', 'When refusal supports notice action and when it does not'], primaryCta: { label: 'Start Notice Only route', href: '/products/notice-only?src=refusing_access_notice' }, secondaryCta: { label: 'Need complete litigation workflow?', href: '/products/complete-pack?src=refusing_access_complete' }, relatedLinks: [{ label: 'Tenant damaging property', href: '/tenant-damaging-property' }, { label: 'Tenant anti-social behaviour', href: '/tenant-anti-social-behaviour' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }], points: ['Access attempt logs and proof of reasonableness', 'Urgent repair escalation when entry is blocked', 'Gas safety and inspection implications', 'Repair evidence pack and contractor records', 'Injunction and tenancy-breach positioning', 'When refusal justifies notice action', 'When refusal does not justify immediate notice action', 'Deeper FAQs for contested access disputes'], extra: 'Access disputes often fail in court when landlords cannot prove proportionate attempts and clear purpose for each requested entry.' }),
  'tenant-damaging-property': createPage({ slug: 'tenant-damaging-property', title: 'Tenant Damaging Property: Evidence, Possession, and Recovery Strategy', description: 'Detailed landlord guide on evidence packs, deposit versus damages claims, Section 8 route logic, and combining possession with money recovery.', heroTitle: 'Tenant Damaging Property: Evidence, Possession, and Recovery Strategy', heroSubtitle: 'Prepare a court-ready damage file with inventory proof, repair costing, route logic, and recovery planning.', icon: '/images/wizard-icons/12-review-submit.png', heroBullets: ['Damage evidence pack from check-in to current condition', 'Deposit deductions versus separate damages claim logic', 'Section 8 support, repair quotes, and combined recovery strategy'], primaryCta: { label: 'Start Notice Only for breach route', href: '/products/notice-only?src=damaging_property_notice' }, secondaryCta: { label: 'Need full case continuity? Complete Pack', href: '/products/complete-pack?src=damaging_property_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Tenant refusing access', href: '/tenant-refusing-access' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }], points: ['Damage evidence pack and chronology standards', 'Deposit deductions versus damages claim route', 'When damage supports Section 8 action', 'Repair quotes, photos, and check-in inventory alignment', 'Combining eviction and money claim strategy', 'Prioritising urgent safety repairs versus recoverable works', 'Common mistakes in damage-only allegations', 'Deeper FAQs for disputed condition and quantum'], extra: 'Damage disputes are won on comparative evidence, not opinion. Baseline inventory quality directly affects recovery outcomes.' }),
  'tenant-anti-social-behaviour': createPage({ slug: 'tenant-anti-social-behaviour', title: 'Tenant Anti-Social Behaviour: Evidence-Led Possession Planning', description: 'Detailed guide for landlords on ASB evidence thresholds, complaints logs, nuisance versus serious behaviour, and Section 8 ground framing.', heroTitle: 'Tenant Anti-Social Behaviour: Evidence-Led Possession Planning', heroSubtitle: 'Turn incident reports into a structured possession case with witness logs, authority evidence, and proportionate escalation.', icon: '/images/wizard-icons/09-issue-identification.png', heroBullets: ['Evidence thresholds for nuisance versus serious ASB', 'Complaint and witness logging for court credibility', 'Section 8 framing with police, council, and neighbour records'], primaryCta: { label: 'Start Notice Only for ASB route', href: '/products/notice-only?src=asb_notice' }, secondaryCta: { label: 'Need end-to-end support? Complete Pack', href: '/products/complete-pack?src=asb_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], points: ['Evidence thresholds for anti-social behaviour', 'Complaint logs and witness statement discipline', 'Nuisance versus serious ASB categorisation', 'Section 8 ground framing for ASB incidents', 'Police and council evidence integration', 'Neighbour evidence quality and corroboration', 'Risk control for retaliatory complaint allegations', 'Deeper FAQs for urgent and repeat ASB'], extra: 'ASB cases need disciplined incident-level evidence; generic complaints without dates, impact, and corroboration are rarely enough.' }),
  'how-long-does-eviction-take': createPage({ slug: 'how-long-does-eviction-take', title: 'How Long Does Eviction Take? Realistic Timings by Route and Stage', description: 'Comprehensive timing guide covering notice, court, hearing, and bailiff stages with route comparison and delay factors.', heroTitle: 'How Long Does Eviction Take? Realistic Timings by Route and Stage', heroSubtitle: 'Plan with realistic stage-based timing assumptions, dependency checks, and delay mitigation.', icon: '/images/wizard-icons/11-timeline.png', heroBullets: ['Notice-stage timing and dependency controls', 'Court, hearing, and bailiff delay realities', 'Route comparison with practical slowdown factors'], primaryCta: { label: 'Start Notice Only now', href: '/products/notice-only?src=timing_notice' }, secondaryCta: { label: 'Need route continuity? Complete Pack', href: '/products/complete-pack?src=timing_complete' }, relatedLinks: [{ label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }], points: ['Realistic timing by possession route', 'Notice stage duration and service dependencies', 'Court stage progression and listing delays', 'Hearing delays and adjournment triggers', 'Bailiff delays and enforcement queue factors', 'Case variables that slow files down', 'Route comparison for planning certainty', 'Deeper FAQs on best and worst-case timelines'], extra: 'Timings are rarely fixed windows; they are dependency chains where one weak step can reset subsequent stages.' }),
  'eviction-timeline-uk': createPage({ slug: 'eviction-timeline-uk', title: 'Eviction Timeline UK: Step-by-Step Stages from Notice to Enforcement', description: 'Detailed eviction timeline guide comparing Section 21 and Section 8 pathways, court steps, enforcement timing, and practical delay dependencies.', heroTitle: 'Eviction Timeline UK: Step-by-Step Stages from Notice to Enforcement', heroSubtitle: 'Map each stage, dependency, and delay risk from first action through enforcement day.', icon: '/images/wizard-icons/11-timeline.png', heroBullets: ['Step-by-step timeline for notice, court, and enforcement', 'Section 21 versus Section 8 sequencing comparison', 'Practical delay dependencies and mitigation actions'], primaryCta: { label: 'Start Notice Only by timeline stage', href: '/products/notice-only?src=timeline_notice' }, secondaryCta: { label: 'Need full lifecycle support? Complete Pack', href: '/products/complete-pack?src=timeline_complete' }, relatedLinks: [{ label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }], points: ['Step-by-step timeline by stage and milestone', 'Section 21 versus Section 8 timeline comparison', 'Court claim preparation and filing stage', 'Hearing stage expectations and decision outcomes', 'Enforcement stage from order to warrant', 'Practical delays and dependency bottlenecks', 'Timeline controls for landlords managing portfolios', 'Deeper FAQs on sequencing errors and resets'], extra: 'A useful timeline is not a single average duration; it is a stage model with explicit dependencies and fallback paths.' }),
  'section-8-grounds-explained': createPage({ slug: 'section-8-grounds-explained', title: 'Section 8 Grounds Explained: Route Logic, Evidence, and Practical Use', description: 'Comprehensive guide to mandatory and discretionary Section 8 grounds, evidence requirements, scenario mapping, and route selection logic.', heroTitle: 'Section 8 Grounds Explained: Route Logic, Evidence, and Practical Use', heroSubtitle: 'Understand mandatory versus discretionary grounds, what proof is needed, and how to select grounds that match your evidence.', icon: '/images/wizard-icons/03-tenancy-details.png', heroBullets: ['Mandatory versus discretionary ground selection', 'Evidence requirements by ground type and scenario', 'Route selection logic and combined-ground strategy'], primaryCta: { label: 'Start Notice Only for Section 8', href: '/products/notice-only?src=s8_grounds_notice' }, secondaryCta: { label: 'Need full case workflow? Complete Pack', href: '/products/complete-pack?src=s8_grounds_complete' }, relatedLinks: [{ label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }, { label: 'Tenant anti-social behaviour', href: '/tenant-anti-social-behaviour' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }], points: ['Mandatory versus discretionary grounds explained', 'Evidence required for each ground category', 'Common landlord scenarios mapped to grounds', 'Route selection logic for mixed facts', 'Combining multiple grounds without contradiction', 'Service and pleading mistakes by ground type', 'Court expectations for proportionality and reasonableness', 'Deeper FAQs on ground choice and fallback'], extra: 'Ground selection should follow evidence reality, not preference. Over-pleading weak grounds can undermine strong ones.' }),
  'accelerated-possession-guide': createPage({ slug: 'accelerated-possession-guide', title: 'Accelerated Possession Guide: Eligibility, Paperwork, and Court Expectations', description: 'Detailed accelerated possession guide covering what it is, when it applies, paperwork standards, court review expectations, and common mistakes.', heroTitle: 'Accelerated Possession Guide: Eligibility, Paperwork, and Court Expectations', heroSubtitle: 'Use a structured preparation model for accelerated possession applications to avoid rejection and delay.', icon: '/images/wizard-icons/10-document-review.png', heroBullets: ['What accelerated possession is and when to use it', 'Eligibility limits and exclusion scenarios', 'Paperwork standards, court expectations, and common errors'], primaryCta: { label: 'Start Notice Only for accelerated route', href: '/products/notice-only?src=accelerated_notice' }, secondaryCta: { label: 'Need court continuity? Complete Pack', href: '/products/complete-pack?src=accelerated_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], points: ['What accelerated possession is and core objective', 'When accelerated possession applies', 'When accelerated possession does not apply', 'Paperwork required and evidence bundle structure', 'Court expectations at review stage', 'Common mistakes that cause rejection or transfer', 'Post-order actions and enforcement dependencies', 'Deeper FAQs for route choice and fallback'], extra: 'Accelerated possession works best when compliance history and document quality are strong before filing.' }),
  'warrant-of-possession-guide': createPage({ slug: 'warrant-of-possession-guide', title: 'Warrant of Possession Guide: Enforcement Stage, Timelines, and Preparation', description: 'Detailed landlord guide on possession orders versus warrants, applying for enforcement, bailiff timelines, and preparation for enforcement day.', heroTitle: 'Warrant of Possession Guide: Enforcement Stage, Timelines, and Preparation', heroSubtitle: 'Understand the enforcement step from possession order to bailiff attendance, with practical preparation controls.', icon: '/images/wizard-icons/12-review-submit.png', heroBullets: ['Possession order versus warrant: what changes legally', 'Applying for enforcement and timeline expectations', 'Bailiff-stage preparation and enforcement-day planning'], primaryCta: { label: 'Start Notice Only if pre-enforcement', href: '/products/notice-only?src=warrant_notice' }, secondaryCta: { label: 'Need full end-to-end handling? Complete Pack', href: '/products/complete-pack?src=warrant_complete' }, relatedLinks: [{ label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }, { label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }], points: ['Possession order versus warrant distinction', 'Applying for enforcement after possession order', 'Timelines from application to bailiff appointment', 'Bailiff-stage documentation and communication', 'Preparing for enforcement day operationally', 'Managing tenant contact and property risk pre-attendance', 'Post-enforcement actions and debt recovery choices', 'Deeper FAQs on delays, suspension, and re-listing'], extra: 'Many landlords underestimate enforcement preparation; most avoidable failures happen between order and appointment, not at hearing.' }),
};
