import type { FAQItem } from '@/components/seo/FAQSection';
import type { IntentSection } from '@/components/seo/HighIntentPageShell';

export interface Pass1LongformPage {
  slug: string;
  title: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  icon: string;
  heroBullets: string[];
  primaryCta: { label: string; href: string };
  secondaryCta: { label: string; href: string };
  relatedLinks: Array<{ label: string; href: string }>;
  sections: IntentSection[];
  faqs: FAQItem[];
}

function buildSections(topic: string, points: string[], extra: string): IntentSection[] {
  const intro: IntentSection = {
    title: `${topic}: what to get right first`,
    paragraphs: [
      `Most landlords lose time on ${topic.toLowerCase()} because they rush into the next document before the facts are properly pinned down. Start with one clear timeline, one evidence folder, and one short note setting out what you want from the case. That usually means getting the property back, recovering money, or keeping both options open while you see how the tenant responds.`,
      `Once that is clear, the next decisions become much easier. You can check whether the notice you have in mind really fits the facts, whether the dates work, and whether your evidence is strong enough to stand up if the tenant pushes back. ${extra}`,
      `This guide is written for landlords who want clear next steps in plain English. It shows what to gather, what usually goes wrong, and when a straightforward notice is enough compared with a fuller court-ready pack.`,
    ],
  };

  const body = points.map((point) => ({
    title: point,
    paragraphs: [
      `${point} is not just another box to tick. Before you move on, check what needs to be true first. That usually means confirming the facts, saving the key documents, and writing down anything that could weaken your position later. Landlords who do this early usually find the rest of the case much easier to manage.`,
      `At this stage, keep the legal checks and practical checks side by side. Legal checks include the right notice, the right dates, and the right service method. Practical checks include diary reminders, named documents, contractor records where relevant, and calm written communication if the tenant is still engaging with you.`,
      `If anything changes, update your file the same day. A part-payment, a promise to leave, a repair complaint, or a sudden change in contact can all affect what you do next. The stronger approach is to keep your paperwork current rather than trying to explain contradictions later.`,
    ],
  }));

  const close: IntentSection = {
    title: `Keep the case clear from first notice to final outcome`,
    paragraphs: [
      `The simplest way to stay in control is to work through the case in stages: identify the problem, check the facts, choose the right legal step, serve correctly, watch for changes, and prepare for court only if you need to. That gives you a steady process instead of a rushed chain of reactions.`,
      `Before you file anything with the court, do one final consistency check. Make sure the names, dates, tenancy details, notice details, and any money figures all line up across every document. This small review step prevents a lot of avoidable delays.`,
      `Once the case ends, close the loop properly. Decide whether any debt recovery is worth pursuing, finish the account, and note what you would do differently next time. That is how one difficult tenancy turns into a better process for the next one.`,
    ],
    bullets: [
      'Keep one timeline and one evidence folder for the whole case.',
      'Update your paperwork whenever the facts change.',
      'Choose the product that matches the stage you are actually at.',
    ],
  };

  return [intro, ...body, close];
}

function buildFaqs(topic: string, points: string[]): FAQItem[] {
  return points.slice(0, 8).map((point) => ({
    question: `${topic}: what should I do about ${point.toLowerCase()} first?`,
    answer: `Start by pinning down the facts, saving the evidence, and checking that your next legal step really fits the situation. For ${point.toLowerCase()}, landlords usually get better results when the notice, dates, and supporting documents all come from one clear timeline instead of being pieced together later.`,
  })).concat({
    question: `${topic}: when should I start with Notice Only and when should I use Complete Pack?`,
    answer: 'Use Notice Only when you mainly need the first legal documents prepared properly. Use Complete Pack when the case is already moving towards court and you want the paperwork to stay joined up from notice through hearing preparation.',
  });
}

function createPage(input: Omit<Pass1LongformPage, 'sections' | 'faqs'> & { points: string[]; extra: string }): Pass1LongformPage {
  return {
    ...input,
    sections: buildSections(input.heroTitle, input.points, input.extra),
    faqs: buildFaqs(input.heroTitle, input.points),
  };
}

export const PASS1_LONGFORM_PAGES: Record<string, Pass1LongformPage> = {
  'tenant-stopped-paying-rent': createPage({ slug: 'tenant-stopped-paying-rent', title: 'Tenant Stopped Paying Rent: Arrears Recovery and Possession Blueprint', description: 'Long-form guide for landlords dealing with arrears, partial payments, evidence control, notice service, and post-possession debt recovery.', heroTitle: 'Tenant Stopped Paying Rent: Arrears Recovery and Possession Blueprint', heroSubtitle: 'A landlord guide to arrears evidence, partial payments, notice decisions, and the steps that usually come next.', icon: '/images/wizard-icons/06-notice-details.png', heroBullets: ['How to deal with arrears when payments are patchy', 'What evidence matters before you serve notice', 'When to focus on possession, debt recovery, or both'], primaryCta: { label: 'Start Notice Only for rent arrears', href: '/products/notice-only?src=stopped_paying_rent_notice' }, secondaryCta: { label: 'Need the court paperwork too? Use Complete Pack', href: '/products/complete-pack?src=stopped_paying_rent_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long eviction takes', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], points: ['Choosing the right arrears approach', 'Handling partial payments and keeping the ledger accurate', 'What to gather before serving notice', 'The usual path from missed rent to hearing', 'Notice mistakes that slow arrears cases down', 'Section 8 versus money claim: when each makes sense', 'What to do after possession if money is still owed', 'Common questions in defended arrears cases'], extra: 'In arrears cases, the biggest avoidable mistake is assuming the threshold will still be there later without checking how part-payments could change the position.' }),
  'tenant-abandoned-property': createPage({ slug: 'tenant-abandoned-property', title: 'Tenant Abandoned Property: Safe Re-entry and Legal Control Plan', description: 'Detailed landlord guide on warning signs, evidence, lawful re-entry risk, belongings handling, arrears recovery, and common mistakes.', heroTitle: 'Tenant Abandoned Property: Safe Re-entry and Legal Control Plan', heroSubtitle: 'Work out whether the property has really been abandoned before you re-enter, change locks, or deal with belongings.', icon: '/images/wizard-icons/02-property-address.png', heroBullets: ['How to tell abandonment from a risky assumption', 'What to check before re-entry', 'How to handle belongings and unpaid rent properly'], primaryCta: { label: 'Start Notice Only', href: '/products/notice-only?src=abandoned_property_notice' }, secondaryCta: { label: 'Need the court stage covered too? Use Complete Pack', href: '/products/complete-pack?src=abandoned_property_complete' }, relatedLinks: [{ label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }], points: ['Warning signs that really matter', 'The risk of unlawful re-entry', 'What evidence to gather first', 'How to deal with belongings, inventory, and notices', 'Recovering arrears after abandonment', 'Common landlord mistakes after the tenant disappears', 'A practical timeline for checks and next steps', 'Questions that come up when the tenant returns later'], extra: 'The real risk is not finding the property empty. It is acting as if you are certain when the legal position is still unclear.' }),
  'tenant-refusing-access': createPage({ slug: 'tenant-refusing-access', title: 'Tenant Refusing Access: Enforcement Without Harassment Risk', description: 'Long-form landlord guide on access logs, urgent repair escalation, gas safety implications, injunction positioning, and notice decisions.', heroTitle: 'Tenant Refusing Access: Enforcement Without Harassment Risk', heroSubtitle: 'Keep a clean record of access requests, repairs, and inspections so you can act firmly without drifting into harassment risk.', icon: '/images/wizard-icons/10-document-review.png', heroBullets: ['How to log access requests properly', 'What changes when repairs or safety checks are urgent', 'When refusal supports notice action and when it does not'], primaryCta: { label: 'Start Notice Only', href: '/products/notice-only?src=refusing_access_notice' }, secondaryCta: { label: 'Need the full court paperwork? Use Complete Pack', href: '/products/complete-pack?src=refusing_access_complete' }, relatedLinks: [{ label: 'Tenant damaging property', href: '/tenant-damaging-property' }, { label: 'Tenant anti-social behaviour', href: '/tenant-anti-social-behaviour' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }], points: ['Keeping a proper access log', 'What to do when urgent repairs are blocked', 'Gas safety and inspection issues', 'Repair evidence and contractor records', 'When an injunction or breach route may help', 'When refusal can justify notice action', 'When refusal does not justify immediate escalation', 'Questions that come up in defended access disputes'], extra: 'Access disputes often go badly for landlords who cannot show calm, proportionate requests and a clear reason for each one.' }),
  'tenant-damaging-property': createPage({ slug: 'tenant-damaging-property', title: 'Tenant Damaging Property: Evidence, Possession, and Recovery Strategy', description: 'Detailed landlord guide on evidence, deposit versus damages claims, Section 8 decisions, and combining possession with money recovery.', heroTitle: 'Tenant Damaging Property: Evidence, Possession, and Recovery Strategy', heroSubtitle: 'Build a clear damage case from the inventory onwards, then decide whether you need possession, a money claim, or both.', icon: '/images/wizard-icons/12-review-submit.png', heroBullets: ['What good damage evidence looks like', 'When to use the deposit and when to claim separately', 'How to link repair costs to the wider case'], primaryCta: { label: 'Start Notice Only for a breach case', href: '/products/notice-only?src=damaging_property_notice' }, secondaryCta: { label: 'Need the court stage covered? Use Complete Pack', href: '/products/complete-pack?src=damaging_property_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Tenant refusing access', href: '/tenant-refusing-access' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }], points: ['Building the damage evidence file', 'Deposit deductions versus a separate damages claim', 'When damage supports Section 8 action', 'How to use quotes, photos, and the check-in record together', 'Combining possession and money recovery', 'Urgent safety works versus recoverable repair costs', 'Mistakes landlords make with damage-only cases', 'Questions that come up when condition is disputed'], extra: 'Damage cases are decided on comparison and proof, not on opinion. The better the starting inventory, the stronger the claim usually is.' }),
  'tenant-anti-social-behaviour': createPage({ slug: 'tenant-anti-social-behaviour', title: 'Tenant Anti-Social Behaviour: Evidence-Led Possession Planning', description: 'Detailed guide for landlords on ASB evidence thresholds, complaint logs, nuisance versus serious behaviour, and Section 8 ground framing.', heroTitle: 'Tenant Anti-Social Behaviour: Evidence-Led Possession Planning', heroSubtitle: 'Turn complaints and incidents into a case the court can actually follow, rather than a bundle of general concerns.', icon: '/images/wizard-icons/09-issue-identification.png', heroBullets: ['How much evidence is usually enough', 'How to log neighbour complaints and witness accounts properly', 'How to link incidents to the grounds you rely on'], primaryCta: { label: 'Start Notice Only for anti-social behaviour', href: '/products/notice-only?src=asb_notice' }, secondaryCta: { label: 'Need end-to-end court support? Use Complete Pack', href: '/products/complete-pack?src=asb_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], points: ['What counts as enough anti-social behaviour evidence', 'Keeping complaint logs and witness notes usable', 'Telling routine nuisance from more serious behaviour', 'How to frame Section 8 grounds around incidents', 'Using police and council material properly', 'What makes neighbour evidence more persuasive', 'Reducing the risk of retaliation arguments', 'Questions that come up in urgent and repeated ASB cases'], extra: 'Anti-social behaviour cases are rarely won on vague complaints. Dates, impact, and supporting evidence matter far more than general frustration.' }),
  'how-long-does-eviction-take': createPage({ slug: 'how-long-does-eviction-take', title: 'How Long Does Eviction Take? Realistic Timings by Route and Stage', description: 'Timing guide covering notice, court, hearing, and bailiff stages with practical delay factors landlords actually face.', heroTitle: 'How Long Does Eviction Take? Realistic Timings by Route and Stage', heroSubtitle: 'Use real stage-by-stage timing expectations so you can plan properly instead of relying on best-case estimates.', icon: '/images/wizard-icons/11-timeline.png', heroBullets: ['How long the notice stage usually takes', 'Where court and hearing delays appear', 'What tends to slow enforcement down'], primaryCta: { label: 'Start Notice Only now', href: '/products/notice-only?src=timing_notice' }, secondaryCta: { label: 'Need the court paperwork too? Use Complete Pack', href: '/products/complete-pack?src=timing_complete' }, relatedLinks: [{ label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }], points: ['Typical timing by possession route', 'How notice periods and service affect the timetable', 'What happens at the court stage', 'Why hearings are delayed or adjourned', 'What slows bailiff enforcement down', 'Case details that change the timeline', 'How to plan around best and worst cases', 'Questions landlords usually ask about timescales'], extra: 'Eviction timing is usually a chain of dependencies, not one fixed number. One weak step early on can add weeks or months later.' }),
  'eviction-timeline-uk': createPage({ slug: 'eviction-timeline-uk', title: 'Eviction Timeline UK: Step-by-Step Stages from Notice to Enforcement', description: 'Detailed eviction timeline guide comparing Section 21 and Section 8 stages, court steps, enforcement timing, and practical delay points.', heroTitle: 'Eviction Timeline UK: Step-by-Step Stages from Notice to Enforcement', heroSubtitle: 'See the usual order of events from notice to bailiff enforcement, and what needs to happen at each stage.', icon: '/images/wizard-icons/11-timeline.png', heroBullets: ['What usually happens first, second, and third', 'How Section 21 and Section 8 timelines differ', 'Where cases most often slow down'], primaryCta: { label: 'Start Notice Only for your stage', href: '/products/notice-only?src=timeline_notice' }, secondaryCta: { label: 'Need the court paperwork too? Use Complete Pack', href: '/products/complete-pack?src=timeline_complete' }, relatedLinks: [{ label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }], points: ['The usual sequence of stages', 'Section 21 versus Section 8 timing differences', 'What happens before a court claim is filed', 'What to expect around the hearing', 'What happens after a possession order', 'The delays that catch landlords out most often', 'How portfolio landlords can stay organised', 'Questions about resets, mistakes, and missed dates'], extra: 'A useful timeline is one you can actually manage. It should show the order of events, the dependencies, and the points where things often go wrong.' }),
  'section-8-grounds-explained': createPage({ slug: 'section-8-grounds-explained', title: 'Section 8 Grounds Explained: Route Logic, Evidence, and Practical Use', description: 'Guide to mandatory and discretionary Section 8 grounds, the evidence behind them, and how landlords usually choose between them.', heroTitle: 'Section 8 Grounds Explained: Route Logic, Evidence, and Practical Use', heroSubtitle: 'Work out which grounds match the facts, what proof you need, and where landlords often weaken their own case.', icon: '/images/wizard-icons/03-tenancy-details.png', heroBullets: ['The difference between mandatory and discretionary grounds', 'What evidence the court expects to see', 'How to avoid relying on grounds that do not fit the facts'], primaryCta: { label: 'Start Notice Only for Section 8', href: '/products/notice-only?src=s8_grounds_notice' }, secondaryCta: { label: 'Need the court stage covered? Use Complete Pack', href: '/products/complete-pack?src=s8_grounds_complete' }, relatedLinks: [{ label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }, { label: 'Tenant anti-social behaviour', href: '/tenant-anti-social-behaviour' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }], points: ['Mandatory versus discretionary grounds in plain English', 'What evidence each type of ground needs', 'Common landlord situations and the grounds that may fit', 'How to handle mixed facts without overcomplicating the case', 'Using more than one ground without undermining the claim', 'Service and pleading mistakes landlords make with Section 8', 'What the court is looking for on reasonableness and proof', 'Questions landlords ask when choosing grounds'], extra: 'The best ground is the one you can actually prove. Adding weak grounds can make a strong case look less reliable.' }),
  'accelerated-possession-guide': createPage({ slug: 'accelerated-possession-guide', title: 'Accelerated Possession Guide: Eligibility, Paperwork, and Court Expectations', description: 'Detailed accelerated possession guide covering when it applies, the paperwork involved, what the court expects, and the mistakes that cause delay.', heroTitle: 'Accelerated Possession Guide: Eligibility, Paperwork, and Court Expectations', heroSubtitle: 'Find out when the accelerated route is available and what needs to be right before you rely on it.', icon: '/images/wizard-icons/10-document-review.png', heroBullets: ['When accelerated possession is the right fit', 'What paperwork needs to be in order first', 'Why applications are delayed, rejected, or transferred'], primaryCta: { label: 'Start Notice Only for accelerated possession', href: '/products/notice-only?src=accelerated_notice' }, secondaryCta: { label: 'Need the court paperwork too? Use Complete Pack', href: '/products/complete-pack?src=accelerated_complete' }, relatedLinks: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], points: ['What accelerated possession is really for', 'When you can use it', 'When you cannot use it', 'The paperwork and evidence you need', 'What the court checks at review stage', 'Mistakes that cause rejection or transfer', 'What happens after the order', 'Questions about choosing this route and falling back'], extra: 'Accelerated possession works best when the compliance history and paperwork are already clean before you file.' }),
  'warrant-of-possession-guide': createPage({ slug: 'warrant-of-possession-guide', title: 'Warrant of Possession Guide: Enforcement Stage, Timelines, and Preparation', description: 'Landlord guide to the enforcement stage after a possession order, including timings, preparation, bailiff action, and next steps.', heroTitle: 'Warrant of Possession Guide: Enforcement Stage, Timelines, and Preparation', heroSubtitle: 'Understand what happens after a possession order, how long enforcement can take, and what to prepare before attendance day.', icon: '/images/wizard-icons/12-review-submit.png', heroBullets: ['The difference between a possession order and a warrant', 'What happens between the order and the appointment', 'How to prepare for enforcement day and after'], primaryCta: { label: 'Start Notice Only if you are still pre-court', href: '/products/notice-only?src=warrant_notice' }, secondaryCta: { label: 'Need the full case paperwork? Use Complete Pack', href: '/products/complete-pack?src=warrant_complete' }, relatedLinks: [{ label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }, { label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }], points: ['What a warrant does and when you need one', 'How to apply after the possession order', 'How long enforcement usually takes', 'What paperwork and communication you need at this stage', 'How to prepare for the appointment itself', 'How to handle contact with the tenant before enforcement', 'What to do after enforcement, including debt recovery', 'Questions about delays, suspensions, and re-listings'], extra: 'Many landlords focus on getting the order and give too little thought to enforcement. A lot of avoidable delay happens after judgment, not before it.' }),
};
