import type { Metadata } from 'next';
import { getCanonicalUrl } from '@/lib/seo';
import type { FAQItem } from '@/components/seo/FAQSection';
import type { IntentSection } from '@/components/seo/HighIntentPageShell';

export interface Phase5PageContent {
  slug: string;
  title: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  icon: string;
  heroBullets: string[];
  keywords: string[];
  primaryCta: { label: string; href: string };
  secondaryCta: { label: string; href: string };
  relatedLinks: Array<{ label: string; href: string }>;
  diagrams: Array<{ title: string; description: string; imageSrc: string; imageAlt: string }>;
  sections: IntentSection[];
  faqs: FAQItem[];
}

interface Seed {
  slug: string;
  title: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  intent: string;
  legalAnchor: string;
  processFocus: string;
  nextStepFocus: string;
  mistakesFocus: string;
  pageType: 'revenue' | 'longtail';
  keywords: string[];
  links: {
    pillar: { label: string; href: string };
    clusters: Array<{ label: string; href: string }>;
    product: { label: string; href: string };
    tool: { label: string; href: string };
  };
}

const diagrams = [
  { title: 'Eviction process timeline', description: 'See the full timeline from notice service to possession and bailiff enforcement.', imageSrc: '/images/wizard-icons/11-calendar-timeline.png', imageAlt: 'Eviction timeline diagram icon' },
  { title: 'Section 21 vs Section 8 comparison', description: 'Compare route choice, risk profile, and evidence burden before serving notice.', imageSrc: '/images/wizard-icons/12-summary-cards.png', imageAlt: 'Section 21 and Section 8 comparison diagram icon' },
  { title: 'Notice → court → bailiff flow', description: 'Use this flow to avoid gaps between your notice file, claim file, and enforcement file.', imageSrc: '/images/wizard-icons/09-court.png', imageAlt: 'Notice to court to bailiff process diagram icon' },
];

function section(topic: string, heading: string, angle: string, depth: 'revenue' | 'longtail'): IntentSection {
  const extra = depth === 'revenue'
    ? 'For revenue-critical pages, this guide goes deeper on sequencing, date controls, and evidence pack integrity so landlords can move from reading to action without a second research cycle.'
    : 'For long-tail pages, this guide focuses on the practical question landlords ask immediately before legal action and gives a direct execution path.';

  const paragraphs = [
    `${topic} should be managed as a controlled legal workflow. In this ${heading.toLowerCase()} section, start by defining your objective in writing: possession, arrears recovery, or both. Then lock one chronology covering tenancy terms, breach history, payments, communications, and service events. Courts reward coherent records and punish contradictions, so each document should be drafted from the same underlying timeline rather than from memory. ${angle}`,
    `Landlords often lose weeks not because the case is weak, but because the file is inconsistent. Keep one evidence index and reconcile every notice date, arrears figure, and statement reference before moving to the next stage. If the tenant partially complies, update the file immediately and reassess route strength before you serve further documents. This prevents avoidable resets, defective claims, and adjournments that increase loss and delay possession.`,
    `Use a product-first workflow so legal intent and execution stay aligned. Begin with the relevant product page to confirm route fit, then move to generation or validation tools only after route confidence is clear. This creates a clean funnel from intent to compliance output and reduces abandoned sessions. ${extra}`,
  ];

  if (depth === 'revenue') {
    paragraphs.push(
      `In high-value possession files, build fallback logic in advance. Document what you will do if the tenant ignores the notice, raises disrepair, pays down arrears before hearing, or requests more time. Pre-committed fallback decisions help you act quickly under pressure and avoid ad hoc reactions that undermine procedural credibility.`,
      `Revenue pages prioritise execution depth. For each stage, list pre-conditions, required documents, likely tenant responses, and your trigger for escalation. This converts legal complexity into operational clarity and reduces delays caused by uncertainty between notice and court stages.`,
      `Where multiple routes are available, compare them using risk, cost, and timeline resilience rather than headline speed. A route that survives challenge is commercially faster than one that looks quick but fails on validity.`
    );
  } else {
    paragraphs.push(
      `Long-tail decision pages are designed for landlords searching moments before legal escalation. Keep your actions evidence-first, time-boxed, and documented so you can move from question to compliant execution in one sitting.`
    );
  }

  return { title: heading, paragraphs };
}

function makeSections(seed: Seed): IntentSection[] {
  return [
    section(seed.intent, 'Quick answer', 'Treat this as a decision gateway: confirm route eligibility before serving anything.', seed.pageType),
    section(seed.intent, 'Legal explanation', `${seed.legalAnchor} Keep your legal reasoning concise, factual, and linked to evidence.`, seed.pageType),
    section(seed.intent, 'Step-by-step process', `${seed.processFocus} Build each stage as a checklist with owner and deadline.`, seed.pageType),
    section(seed.intent, 'What landlords usually do next', `${seed.nextStepFocus} Plan your next two moves before you trigger court deadlines.`, seed.pageType),
    section(seed.intent, 'Common mistakes', `${seed.mistakesFocus} Most preventable delay comes from date errors, route confusion, or weak service proof.`, seed.pageType),
  ];
}

function makeFaqs(topic: string): FAQItem[] {
  return [
    { question: `Can I take action immediately for ${topic.toLowerCase()}?`, answer: 'Usually yes, but only after checking route eligibility, notice validity requirements, and evidence quality for your exact facts.' },
    { question: 'Should I prioritise Section 21 or Section 8?', answer: 'Choose the route that matches your legal facts and commercial objective, then preserve fallback options to avoid losing momentum.' },
    { question: 'What evidence should I prepare before court?', answer: 'Keep a tenancy agreement, chronology, payment ledger, notices, service proof, and communications aligned to one indexed evidence pack.' },
    { question: 'What causes the most landlord delays?', answer: 'Incorrect dates, weak service records, contradictory arrears figures, and changing route late in the process cause most avoidable delay.' },
    { question: 'When should I use the complete pack product?', answer: 'Use Complete Pack when you need continuity from notice stage into court-stage preparation and enforcement planning.' },
  ];
}

function makePage(seed: Seed): Phase5PageContent {
  return {
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    heroTitle: seed.heroTitle,
    heroSubtitle: seed.heroSubtitle,
    icon: '/images/wizard-icons/11-calendar-timeline.png',
    heroBullets: [
      'Quick route clarity before legal action',
      'Notice, court, and enforcement sequence mapped',
      'Product-first CTA path for immediate execution',
    ],
    keywords: seed.keywords,
    primaryCta: { label: 'Start complete eviction pack', href: '/products/complete-pack' },
    secondaryCta: { label: 'Validate your notice route first', href: '/tools/validators' },
    relatedLinks: [seed.links.pillar, ...seed.links.clusters.slice(0, 2), seed.links.product, seed.links.tool],
    diagrams,
    sections: makeSections(seed),
    faqs: makeFaqs(seed.heroTitle),
  };
}

const seeds: Seed[] = [
  { slug: 'evict-tenant-not-paying-rent', title: 'Evict Tenant Not Paying Rent: UK Landlord Legal Action Guide', description: 'Immediate-action guide for landlords where tenants stop paying rent, including notice route, court preparation, and enforcement.', heroTitle: 'Evict Tenant Not Paying Rent', heroSubtitle: 'What to do when arrears rise and you need possession without procedural resets.', intent: 'Rent arrears possession strategy for landlords', legalAnchor: 'Ground 8 thresholds, discretionary grounds, and Section 21 fallback eligibility are central to lawful route selection.', processFocus: 'From arrears diagnosis to notice service, claim filing, and enforcement readiness.', nextStepFocus: 'Most landlords move into Section 8 service, then court prep and parallel debt recovery planning.', mistakesFocus: 'Serving too early, weak arrears schedules, and failing to update figures after partial payment are common failures.', pageType: 'revenue', keywords: ['evict tenant not paying rent', 'landlord rent arrears eviction', 'section 8 rent arrears'], links: { pillar: { label: 'Rent arrears landlord guide', href: '/rent-arrears-landlord-guide' }, clusters: [{ label: 'Section 8 eviction process', href: '/section-8-eviction-process' }, { label: 'Recover rent arrears after eviction', href: '/recover-rent-arrears-after-eviction' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Rent arrears calculator', href: '/tools/rent-arrears-calculator' } } },
  { slug: 'tenant-stopped-paying-rent', title: 'Tenant Stopped Paying Rent: Landlord Action Before Court', description: 'Step-by-step landlord playbook for arrears cases where the tenant has stopped paying and legal action is likely.', heroTitle: 'Tenant Stopped Paying Rent', heroSubtitle: 'Take structured legal action quickly without damaging your court position.', intent: 'Early legal action when tenant stops paying rent', legalAnchor: 'Ground-led possession and service timing determine whether your claim survives challenge.', processFocus: 'Structured arrears logging, pre-action communication, notice, and claim readiness.', nextStepFocus: 'Most landlords progress to notice service and staged court prep in the same week.', mistakesFocus: 'Relying on memory, sending inconsistent arrears figures, and weak communication records create risk.', pageType: 'revenue', keywords: ['tenant stopped paying rent', 'landlord arrears action', 'eviction for rent arrears uk'], links: { pillar: { label: 'Section 8 notice guide', href: '/section-8-notice-guide' }, clusters: [{ label: 'Rent arrears eviction guide', href: '/rent-arrears-eviction-guide' }, { label: 'Money claim unpaid rent', href: '/money-claim-unpaid-rent' }], product: { label: 'Notice Only product', href: '/products/notice-only' }, tool: { label: 'Free rent demand letter', href: '/tools/free-rent-demand-letter' } } },
  { slug: 'section-21-notice-guide', title: 'Section 21 Notice Guide: Landlord Route from Notice to Possession', description: 'Full Section 21 guide for landlords covering validity checks, service process, post-notice actions, and court escalation.', heroTitle: 'Section 21 Notice Guide', heroSubtitle: 'Use a no-fault route safely with compliance-first checks and court continuity.', intent: 'No-fault possession workflow using Section 21', legalAnchor: 'Form 6A validity depends on compliance preconditions, date logic, and service evidence.', processFocus: 'Compliance audit, form preparation, service, post-expiry actions, and accelerated claim prep.', nextStepFocus: 'Landlords usually move to accelerated possession when notice expires without vacating.', mistakesFocus: 'Invalid form versions, missing compliance records, and poor service evidence are frequent blockers.', pageType: 'revenue', keywords: ['section 21 notice guide', 'form 6a landlord', 'section 21 eviction process'], links: { pillar: { label: 'How to evict a tenant UK', href: '/how-to-evict-a-tenant-uk' }, clusters: [{ label: 'Section 21 validity checklist', href: '/section-21-validity-checklist' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }], product: { label: 'Notice Only product', href: '/products/notice-only' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'section-8-notice-guide', title: 'Section 8 Notice Guide: Grounds, Evidence and Court Progression', description: 'Comprehensive Section 8 guide for landlords with grounds strategy, evidence, service and hearing preparation.', heroTitle: 'Section 8 Notice Guide', heroSubtitle: 'Choose and evidence the right grounds before serving notice.', intent: 'Grounds-based possession strategy under Section 8', legalAnchor: 'Mandatory and discretionary grounds require different evidence depth and hearing expectations.', processFocus: 'Ground selection, evidence indexing, service standards, and claim sequencing.', nextStepFocus: 'Landlords next move is often claim issue with updated arrears and witness chronology.', mistakesFocus: 'Using weak grounds, missing corroboration, and not planning for defended hearings creates delay.', pageType: 'revenue', keywords: ['section 8 notice guide', 'section 8 grounds', 'evict tenant section 8'], links: { pillar: { label: 'Eviction process England', href: '/eviction-process-england' }, clusters: [{ label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }, { label: 'Section 8 eviction process', href: '/section-8-eviction-process' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'how-to-evict-a-tenant-uk', title: 'How to Evict a Tenant UK: Landlord Legal Process Guide', description: 'End-to-end eviction guide for UK landlords from route choice and notice service to court order and bailiff enforcement.', heroTitle: 'How to Evict a Tenant in the UK', heroSubtitle: 'A practical landlord framework for legal possession action.', intent: 'End-to-end eviction process planning for UK landlords', legalAnchor: 'Jurisdiction, tenancy type, and breach facts determine lawful notice and court pathway.', processFocus: 'Route diagnosis, notice stage, court stage, order stage, and enforcement handover.', nextStepFocus: 'Landlords typically start with notice-only action and switch to full pack at court stage.', mistakesFocus: 'Generic templates, no timeline controls, and jurisdiction confusion are high-risk mistakes.', pageType: 'revenue', keywords: ['how to evict a tenant uk', 'landlord eviction process uk', 'eviction steps landlord'], links: { pillar: { label: 'Eviction guides hub', href: '/eviction-guides' }, clusters: [{ label: 'Eviction process England', href: '/eviction-process-england' }, { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'eviction-process-england', title: 'Eviction Process England: Notice, Court and Bailiff Steps', description: 'Landlord guide to the eviction process in England with stage-by-stage legal workflow and delay controls.', heroTitle: 'Eviction Process England', heroSubtitle: 'Move from notice to possession without losing procedural momentum.', intent: 'England possession workflow from notice to enforcement', legalAnchor: 'Claim viability relies on valid notice, coherent bundle evidence, and accurate filing sequence.', processFocus: 'Notice service, claim filing, hearing prep, possession order, and bailiff application.', nextStepFocus: 'Most landlords move into court claim assembly immediately after notice expiry.', mistakesFocus: 'Date mismatch between notice and claim documents is one of the most frequent court setbacks.', pageType: 'revenue', keywords: ['eviction process england', 'england landlord eviction steps', 'court bailiff eviction england'], links: { pillar: { label: 'Section 21 notice guide', href: '/section-21-notice-guide' }, clusters: [{ label: 'Court possession order guide', href: '/court-possession-order-guide' }, { label: 'Bailiff eviction process', href: '/bailiff-eviction-process' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'eviction-timeline-uk', title: 'Eviction Timeline UK: Realistic Landlord Stage Durations', description: 'Realistic UK eviction timeline breakdown from notice service through court and bailiff stages, with delay controls.', heroTitle: 'Eviction Timeline UK', heroSubtitle: 'Know what happens next and what controls actual timescales.', intent: 'Timeline forecasting for landlord possession cases', legalAnchor: 'Timeline confidence comes from dependency control, not average durations alone.', processFocus: 'Timeline by stage with trigger points and route-dependent delays.', nextStepFocus: 'Landlords usually tighten service evidence and court file readiness to protect timeline certainty.', mistakesFocus: 'Assuming fixed timelines and ignoring bottlenecks creates planning errors.', pageType: 'revenue', keywords: ['eviction timeline uk', 'how long eviction takes uk', 'landlord eviction timescale'], links: { pillar: { label: 'Eviction process England', href: '/eviction-process-england' }, clusters: [{ label: 'How long does eviction take', href: '/how-long-does-eviction-take' }, { label: 'Possession order timeline', href: '/possession-order-timeline' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'section-8-grounds-explained', title: 'Section 8 Grounds Explained: Landlord Ground Selection Framework', description: 'Practical landlord guide to Section 8 grounds, mandatory vs discretionary logic, and evidence thresholds.', heroTitle: 'Section 8 Grounds Explained', heroSubtitle: 'Choose grounds based on evidence strength, not preference.', intent: 'Section 8 ground selection and pleading strategy', legalAnchor: 'Ground choice must map to facts available at service and likely hearing challenges.', processFocus: 'Evaluate facts, choose grounds, compile proof, and preserve fallback route.', nextStepFocus: 'Landlords generally proceed to service and immediate court readiness planning.', mistakesFocus: 'Overloading weak grounds and under-documenting strong grounds reduces credibility.', pageType: 'revenue', keywords: ['section 8 grounds explained', 'mandatory discretionary grounds section 8', 'landlord section 8 evidence'], links: { pillar: { label: 'Section 8 notice guide', href: '/section-8-notice-guide' }, clusters: [{ label: 'Tenant anti-social behaviour', href: '/tenant-anti-social-behaviour' }, { label: 'Tenant stopped paying rent', href: '/tenant-stopped-paying-rent' }], product: { label: 'Notice Only product', href: '/products/notice-only' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'accelerated-possession-guide', title: 'Accelerated Possession Guide: Fast-Track Section 21 Court Route', description: 'Deep landlord guide to accelerated possession claims, eligibility checks, paperwork standards and timeline management.', heroTitle: 'Accelerated Possession Guide', heroSubtitle: 'Use the paper-based Section 21 court path correctly the first time.', intent: 'Accelerated possession eligibility and paper claim preparation', legalAnchor: 'Accelerated route success depends on pristine Section 21 compliance and documentary integrity.', processFocus: 'Eligibility check, bundle prep, filing, tenant response handling, and order stage.', nextStepFocus: 'Landlords usually progress to warrant planning if possession date is missed.', mistakesFocus: 'Filing with incomplete compliance proof causes rejection and expensive delay.', pageType: 'revenue', keywords: ['accelerated possession guide', 'n5b claim landlord', 'section 21 court process'], links: { pillar: { label: 'Section 21 notice guide', href: '/section-21-notice-guide' }, clusters: [{ label: 'N5B possession claim guide', href: '/n5b-possession-claim-guide' }, { label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'money-claim-unpaid-rent', title: 'Money Claim Unpaid Rent: Landlord Court Recovery Playbook', description: 'Landlord money-claim guide for unpaid rent, pre-action protocol, issue strategy, evidence standards, and enforcement choices.', heroTitle: 'Money Claim Unpaid Rent', heroSubtitle: 'Recover arrears with a court-ready debt file and clear enforcement path.', intent: 'County court rent arrears recovery for landlords', legalAnchor: 'Pre-action protocol compliance, quantified debt schedules, and service records are key to claim strength.', processFocus: 'Pre-action letter, issue strategy, defence handling, judgment and enforcement.', nextStepFocus: 'Landlords often coordinate money claim with possession progress to protect cashflow.', mistakesFocus: 'Skipping pre-action protocol and weak debt schedules undermine recoverability.', pageType: 'revenue', keywords: ['money claim unpaid rent', 'landlord mcol arrears', 'recover rent arrears court'], links: { pillar: { label: 'Rent arrears landlord guide', href: '/rent-arrears-landlord-guide' }, clusters: [{ label: 'Pre-action protocol debt', href: '/pre-action-protocol-debt' }, { label: 'Money claim online MCOL', href: '/money-claim-online-mcol' }], product: { label: 'Money Claim product', href: '/products/money-claim' }, tool: { label: 'Rent arrears calculator', href: '/tools/rent-arrears-calculator' } } },
  { slug: 'can-a-landlord-evict-for-noise-complaints', title: 'Can a Landlord Evict for Noise Complaints? UK Legal Guide', description: 'Landlord legal guide to eviction for noise complaints, evidence thresholds, notice choice and court preparation.', heroTitle: 'Can a Landlord Evict for Noise Complaints?', heroSubtitle: 'Yes, but only with credible evidence and correct route selection.', intent: 'Eviction action for persistent tenant noise complaints', legalAnchor: 'Noise complaints usually require Section 8 grounds with corroborated incident evidence.', processFocus: 'Build incident logs, gather third-party evidence, serve notice and prepare hearing file.', nextStepFocus: 'Landlords usually escalate to court when complaints remain persistent post-notice.', mistakesFocus: 'Relying on informal complaints without dated logs weakens claims.', pageType: 'longtail', keywords: ['evict tenant for noise complaints', 'noise complaint eviction uk', 'section 8 anti social behaviour noise'], links: { pillar: { label: 'Section 8 notice guide', href: '/section-8-notice-guide' }, clusters: [{ label: 'Tenant anti-social behaviour', href: '/tenant-anti-social-behaviour' }, { label: 'Section 8 grounds explained', href: '/section-8-grounds-explained' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'can-a-landlord-evict-for-pets', title: 'Can a Landlord Evict for Pets? Landlord Notice and Court Guide', description: 'Practical guide for landlords on pet-related tenancy breaches, evidence, notice drafting and court escalation.', heroTitle: 'Can a Landlord Evict for Pets?', heroSubtitle: 'Pet breaches can justify action when tenancy terms and evidence are clear.', intent: 'Pet-related tenancy breach eviction planning', legalAnchor: 'Enforceability depends on tenancy wording, reasonableness, and proven breach impact.', processFocus: 'Review tenancy terms, gather evidence, communicate breach, and serve compliant notice.', nextStepFocus: 'Landlords usually move from warning stage to notice if breach persists or damage escalates.', mistakesFocus: 'Vague clauses and no documented breach warnings reduce legal strength.', pageType: 'longtail', keywords: ['can landlord evict for pets', 'pet clause eviction uk', 'tenant pets breach tenancy'], links: { pillar: { label: 'How to evict a tenant UK', href: '/how-to-evict-a-tenant-uk' }, clusters: [{ label: 'Tenant breach of tenancy', href: '/tenant-breach-of-tenancy' }, { label: 'Evict tenant for damage', href: '/evict-tenant-for-damage' }], product: { label: 'Notice Only product', href: '/products/notice-only' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'can-you-evict-a-tenant-for-property-damage', title: 'Can You Evict a Tenant for Property Damage? Landlord Legal Route', description: 'Landlord guide to eviction for property damage with evidence standards, notice routes and recovery strategy.', heroTitle: 'Can You Evict a Tenant for Property Damage?', heroSubtitle: 'Yes, where damage evidence is strong and notice route is correctly chosen.', intent: 'Property damage eviction and recovery strategy', legalAnchor: 'Grounds, photographic evidence, inventories, and repair invoices drive case credibility.', processFocus: 'Capture damage evidence, issue warnings, serve notice, and prepare court bundle.', nextStepFocus: 'Landlords usually pair possession action with separate damages recovery planning.', mistakesFocus: 'Late evidence capture and no inventory baseline weaken damage claims.', pageType: 'longtail', keywords: ['evict tenant for property damage', 'tenant damage eviction uk', 'section 8 property damage'], links: { pillar: { label: 'Section 8 notice guide', href: '/section-8-notice-guide' }, clusters: [{ label: 'Tenant damaging property', href: '/tenant-damaging-property' }, { label: 'Money claim property damage', href: '/money-claim-property-damage' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'what-happens-after-section-21', title: 'What Happens After Section 21? Landlord Next-Step Guide', description: 'Landlord guide explaining what happens after serving Section 21, including expiry, court claim and enforcement.', heroTitle: 'What Happens After Section 21?', heroSubtitle: 'Plan your next legal steps before the notice expires.', intent: 'Post-Section 21 progression to possession claim', legalAnchor: 'If tenant remains, accelerated possession preparation becomes the primary path.', processFocus: 'Track expiry, verify service evidence, prepare N5B bundle, and submit claim.', nextStepFocus: 'Most landlords progress to accelerated possession and warrant planning.', mistakesFocus: 'Waiting until expiry day to prepare court file causes unnecessary delay.', pageType: 'longtail', keywords: ['what happens after section 21', 'after section 21 notice expires', 'section 21 next steps landlord'], links: { pillar: { label: 'Section 21 notice guide', href: '/section-21-notice-guide' }, clusters: [{ label: 'Section 21 expired what next', href: '/section-21-expired-what-next' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'what-happens-after-section-8', title: 'What Happens After Section 8? Landlord Court Progress Guide', description: 'Landlord action guide for the period after Section 8 service, from notice expiry to court hearing and possession order.', heroTitle: 'What Happens After Section 8?', heroSubtitle: 'Move from notice stage into claim and hearing prep confidently.', intent: 'Post-Section 8 case progression and hearing preparation', legalAnchor: 'Claim progression depends on grounds status at issue and hearing dates.', processFocus: 'Monitor notice period, update evidence, issue claim, and prep hearing narrative.', nextStepFocus: 'Landlords commonly move into court claim with updated arrears and witness evidence.', mistakesFocus: 'Not refreshing evidence between service and hearing weakens outcomes.', pageType: 'longtail', keywords: ['what happens after section 8', 'section 8 after notice expiry', 'section 8 court steps'], links: { pillar: { label: 'Section 8 notice guide', href: '/section-8-notice-guide' }, clusters: [{ label: 'Section 8 eviction process', href: '/section-8-eviction-process' }, { label: 'Court possession order guide', href: '/court-possession-order-guide' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'how-long-does-bailiff-eviction-take', title: 'How Long Does Bailiff Eviction Take? UK Landlord Timeline Guide', description: 'Landlord guide to bailiff eviction timelines, dependencies and actions that shorten avoidable enforcement delay.', heroTitle: 'How Long Does Bailiff Eviction Take?', heroSubtitle: 'Understand bailiff-stage dependencies and timeline controls.', intent: 'Bailiff-stage timeline planning for possession enforcement', legalAnchor: 'Enforcement timing varies by court capacity, paperwork quality, and tenant responses.', processFocus: 'Apply for warrant promptly, prepare documents, and manage pre-appointment risks.', nextStepFocus: 'Landlords usually tighten operational prep before appointment day.', mistakesFocus: 'Late warrant application and incomplete forms create avoidable queue delay.', pageType: 'longtail', keywords: ['how long does bailiff eviction take', 'bailiff eviction timeline uk', 'warrant of possession timescale'], links: { pillar: { label: 'Eviction process England', href: '/eviction-process-england' }, clusters: [{ label: 'Warrant of possession guide', href: '/warrant-of-possession-guide' }, { label: 'Court bailiff eviction guide', href: '/court-bailiff-eviction-guide' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'how-long-after-court-order-do-bailiffs-evict', title: 'How Long After Court Order Do Bailiffs Evict? Landlord Guide', description: 'Clear landlord guide to post-order bailiff timing, warrant applications and delay mitigation in possession enforcement.', heroTitle: 'How Long After a Court Order Do Bailiffs Evict?', heroSubtitle: 'From possession order to appointment date: what controls timing.', intent: 'Post-possession-order bailiff timeline management', legalAnchor: 'A possession order is not enforcement; a valid warrant stage is still required.', processFocus: 'Move from order to warrant, track listing, and prepare enforcement logistics.', nextStepFocus: 'Most landlords also plan arrears recovery and property handover tasks in parallel.', mistakesFocus: 'Assuming order date equals eviction date causes avoidable planning failures.', pageType: 'longtail', keywords: ['how long after court order bailiffs evict', 'possession order to bailiff time', 'court order eviction timeline'], links: { pillar: { label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, clusters: [{ label: 'Bailiff eviction process', href: '/bailiff-eviction-process' }, { label: 'Possession order timeline', href: '/possession-order-timeline' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'tenant-ignores-section-21', title: 'Tenant Ignores Section 21: What Landlords Should Do Next', description: 'Landlord guide for when a tenant ignores Section 21, covering post-expiry actions, court filing and enforcement path.', heroTitle: 'Tenant Ignores Section 21', heroSubtitle: 'When notice expires and tenant stays, move to court without delay.', intent: 'Post-expiry Section 21 escalation workflow', legalAnchor: 'Self-help eviction is unlawful; court possession route is required.', processFocus: 'Confirm expiry, lock evidence, issue accelerated claim, and track order stage.', nextStepFocus: 'Landlords usually proceed to warrant if possession date is not met.', mistakesFocus: 'Threat-based communication and delayed claim issue can both backfire.', pageType: 'longtail', keywords: ['tenant ignores section 21', 'tenant wont leave after section 21', 'section 21 ignored what next'], links: { pillar: { label: 'Section 21 notice guide', href: '/section-21-notice-guide' }, clusters: [{ label: 'Tenant refuses to leave after notice', href: '/tenant-refuses-to-leave-after-notice' }, { label: 'Accelerated possession guide', href: '/accelerated-possession-guide' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
  { slug: 'tenant-ignores-section-8', title: 'Tenant Ignores Section 8: Landlord Court Action Guide', description: 'Practical landlord guide for cases where tenant ignores Section 8 notice and possession action must progress to court.', heroTitle: 'Tenant Ignores Section 8', heroSubtitle: 'Escalate from notice stage to hearing preparation with a clean evidence file.', intent: 'Section 8 ignored notice escalation and court preparation', legalAnchor: 'Court claim must evidence both valid notice service and continuing grounds.', processFocus: 'Track expiry, refresh evidence, issue claim, and prepare for defended hearing.', nextStepFocus: 'Landlords commonly combine possession claim with arrears schedule updates.', mistakesFocus: 'Proceeding with stale evidence or weak service proof risks adjournment.', pageType: 'longtail', keywords: ['tenant ignores section 8', 'section 8 notice ignored', 'eviction after section 8 expiry'], links: { pillar: { label: 'Section 8 notice guide', href: '/section-8-notice-guide' }, clusters: [{ label: 'Section 8 eviction process', href: '/section-8-eviction-process' }, { label: 'Eviction court hearing guide', href: '/eviction-court-hearing-guide' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 8 validator', href: '/tools/validators/section-8' } } },
  { slug: 'how-to-speed-up-eviction-uk', title: 'How to Speed Up Eviction UK: Landlord Delay-Reduction Playbook', description: 'Landlord guide to accelerating eviction lawfully by improving route choice, paperwork quality, and enforcement readiness.', heroTitle: 'How to Speed Up Eviction UK', heroSubtitle: 'Reduce avoidable delay without creating legal validity risk.', intent: 'Lawful eviction acceleration strategy for landlords', legalAnchor: 'Speed comes from procedural quality, not shortcuts that jeopardise validity.', processFocus: 'Front-load evidence, validate route, stage deadlines, and pre-plan enforcement.', nextStepFocus: 'Landlords usually combine checklist controls with product-first execution tools.', mistakesFocus: 'Chasing speed with weak notices typically causes longer delays later.', pageType: 'longtail', keywords: ['how to speed up eviction uk', 'faster landlord eviction process', 'reduce eviction delays'], links: { pillar: { label: 'Eviction process England', href: '/eviction-process-england' }, clusters: [{ label: 'Eviction timeline UK', href: '/eviction-timeline-uk' }, { label: 'How long does eviction take', href: '/how-long-does-eviction-take' }], product: { label: 'Complete Pack product', href: '/products/complete-pack' }, tool: { label: 'Section 21 validator', href: '/tools/validators/section-21' } } },
];

export const PHASE5_PAGES: Record<string, Phase5PageContent> = Object.fromEntries(seeds.map((seed) => [seed.slug, makePage(seed)]));

export function getPhase5Metadata(page: Phase5PageContent): Metadata {
  const canonical = getCanonicalUrl(`/${page.slug}`);
  return {
    title: page.title,
    description: page.description,
    keywords: page.keywords,
    alternates: { canonical },
    openGraph: {
      title: page.title,
      description: page.description,
      type: 'article',
      url: canonical,
    },
  };
}
