export type OfficialFormFieldCategory = 'auto' | 'conditional' | 'manual';

export interface OfficialFormFieldMatrix {
  allFields: string[];
  autoFields: string[];
  conditionalFields: string[];
}

export const N215_FIELD_MATRIX: OfficialFormFieldMatrix = {
  allFields: [
    'Text Field 1',
    'Text Field 2',
    'Text Field 3',
    'Text Field 4',
    'Text Field 93',
    'Text Field 94',
    'Text Field 102',
    'Text Field 101',
    'Text Field 100',
    'Text Field 99',
    'Text Field 91',
    'Text Field 90',
    'Text Field 89',
    'Text Field 88',
    'Text Field 87',
    'Text Field 86',
    'Text Field 85',
    'Text1',
    'Text2',
    'Check Box3',
    'Check Box4',
    'Check Box5',
    'Text6',
    'Text7',
    'Check Box8',
    'Text9',
    'Check Box10',
    'Check Box11',
    'Text12',
    'Check Box13',
    'Text14',
    'Text15',
    'Text16',
    'Text17',
    'Text18',
    'Text19',
    'Text20',
    'Check Box21',
    'Check Box22',
    'Check Box23',
    'Check Box24',
    'Check Box25',
    'Check Box26',
    'Check Box27',
    'Check Box28',
    'Check Box29',
    'Check Box30',
    'Check Box31',
    'Check Box32',
    'Check Box33',
    'Check Box34',
    'Check Box35',
    'Text36',
    'Check Box37',
    'Check Box40',
    'Check Box41',
    'Check Box42',
    'Check Box43',
    'Check Box44',
  ],
  autoFields: [
    'Text Field 1',
    'Text Field 3',
    'Text Field 4',
    'Text Field 93',
    'Text Field 94',
    'Text Field 102',
    'Text Field 100',
    'Text Field 91',
    'Text Field 87',
    'Text Field 90',
    'Text Field 89',
    'Text Field 88',
    'Text1',
    'Text2',
    'Text16',
    'Check Box22',
    'Check Box25',
    'Check Box40',
  ],
  conditionalFields: [
    'Text Field 2',
    'Text Field 101',
    'Text Field 99',
    'Text Field 86',
    'Text Field 85',
    'Check Box3',
    'Check Box4',
    'Check Box5',
    'Text6',
    'Text7',
    'Check Box8',
    'Text9',
    'Check Box10',
    'Check Box11',
    'Text12',
    'Check Box13',
    'Text14',
    'Text15',
    'Text17',
    'Text18',
    'Text19',
    'Text20',
    'Check Box21',
    'Check Box23',
    'Check Box24',
    'Check Box26',
    'Check Box27',
    'Check Box28',
    'Check Box29',
    'Check Box30',
    'Check Box31',
    'Check Box32',
    'Check Box33',
    'Check Box34',
    'Check Box35',
    'Text36',
    'Check Box37',
    'Check Box41',
    'Check Box42',
    'Check Box43',
    'Check Box44',
  ],
};

export const N5_FIELD_MATRIX: OfficialFormFieldMatrix = {
  allFields: [
    'In the court',
    'Fee account no',
    "claimant's details",
    "defendant's details",
    'possession of',
    'heardon',
    'year',
    'time',
    'location',
    'address for service',
    'courtfee',
    'solfee',
    'total',
    'issuedate',
    'rent arrears - yes',
    'other breach of tenancy - yes',
    'forfeiture of the lease - yes',
    'mortgage arrears - yes',
    'other breach of the mortgage - yes',
    'trespass - yes',
    'other - yes',
    'some other reason - details',
    'anti-social behaviour - yes',
    'unlawful use - yes',
    'demotion of tenancy - yes',
    'demotion of tenancy - no',
    'order suspending the right to buy - yes',
    'order suspending the right to buy - no',
    'HRA - yes',
    'HRA - no',
    'claimno',
    'I believe that the facts stated in this clam form are true',
    'The Claimant believes that the facts stated in this claim form are true. I am authorised by the claimant to sign this statement',
    'Statement of Truth signature box',
    'Statement of Truth is signed by the Claimant',
    'Statement of Truth is signed by the Litigation friend (where claimant is a child or a patient)',
    'Statement of Truth is signed by the Claimant’s legal representative (as defined by CPR 2.3(1))',
    'Date the Statement of Truth is signed - DD',
    'Date the Statement of Truth is signed - MM',
    'Date the Statement of Truth is signed - YYYY',
    'Full name of the person signing the Statement of Truth',
    'Name of claimant’s legal representative’s firm',
    'If signing on behalf of firm or company give position or office held',
    'Postcode - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'Town or city - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'building and street - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'Second line of address - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'County (optional) - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'If applicable, fax number',
    'If applicable, phone number',
    'If applicable, your reference',
    'If applicable, DX number',
    'If applicable, email address',
    'claim no',
  ],
  autoFields: [
    'In the court',
    "claimant's details",
    "defendant's details",
    'possession of',
    'address for service',
    'courtfee',
    'total',
    'rent arrears - yes',
    'demotion of tenancy - no',
    'order suspending the right to buy - no',
    'HRA - no',
    'I believe that the facts stated in this clam form are true',
    'Statement of Truth signature box',
    'Statement of Truth is signed by the Claimant',
    'Date the Statement of Truth is signed - DD',
    'Date the Statement of Truth is signed - MM',
    'Date the Statement of Truth is signed - YYYY',
    'Full name of the person signing the Statement of Truth',
    'Postcode - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'building and street - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'If applicable, phone number',
    'If applicable, email address',
  ],
  conditionalFields: [
    'Fee account no',
    'heardon',
    'year',
    'time',
    'location',
    'solfee',
    'issuedate',
    'other breach of tenancy - yes',
    'forfeiture of the lease - yes',
    'mortgage arrears - yes',
    'other breach of the mortgage - yes',
    'trespass - yes',
    'other - yes',
    'some other reason - details',
    'anti-social behaviour - yes',
    'unlawful use - yes',
    'demotion of tenancy - yes',
    'order suspending the right to buy - yes',
    'HRA - yes',
    'claimno',
    'The Claimant believes that the facts stated in this claim form are true. I am authorised by the claimant to sign this statement',
    'Statement of Truth is signed by the Litigation friend (where claimant is a child or a patient)',
    'Statement of Truth is signed by the Claimant’s legal representative (as defined by CPR 2.3(1))',
    'Name of claimant’s legal representative’s firm',
    'If signing on behalf of firm or company give position or office held',
    'Town or city - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'Second line of address - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'County (optional) - Claimant’s or claimant’s legal representative’s address to which documents or payments should be sent',
    'If applicable, fax number',
    'If applicable, your reference',
    'If applicable, DX number',
    'claim no',
  ],
};

export const N119_FIELD_MATRIX: OfficialFormFieldMatrix = {
  allFields: [
    'name of court',
    'claim no',
    'name of defendant',
    'name of claimant',
    'The claimant has a right to possession of:',
    'To the best of the claimant’s knowledge the following persons are in possession of the property:',
    '3(a) Type of tenancy',
    '3(a) Date of tenancy',
    '3(b) The current rent is',
    '3(b) The current rent is payable each fortnight',
    '3(b) The current rent is payable each month',
    '3(b) The current rent is payable each - specify the period',
    '3(c) Any unpaid rent or charge for use and occupation should be calculated at £',
    '4. (a) The reason the claimant is asking for possession is:',
    '4. (b) The reason the claimant is asking for possession is:',
    '4. (c) The reason the claimant is asking for possession is:',
    '5. The following steps have already been taken to recover any arrears:',
    '6. Other type of notice',
    '6. Day and month notice served',
    '6. Year notice served',
    '7. The following information is known about the defendant’s circumstances:',
    '8. The claimant is asking the court to take the following financial or other information into account when making its decision whether or not to grant an order for possession:',
    '9. (b) Entitled to relief against forfeiture - name',
    '9. (b) Entitled to relief against forfeiture - address',
    '11. In the alternative to possession, is the claimant asking the court to make a demotion order or an order suspending the right to buy? Yes',
    '11. In the alternative to possession, is the claimant asking the court to make a demotion order or an order suspending the right to buy? No',
    '12. The (demotion) (suspension) claim is made under: section 82A(2) of the Housing Act 1985',
    '12. The (demotion) (suspension) claim is made under: section 6A(2) of the Housing Act 1988',
    '12. The (demotion) (suspension) claim is made under: section 121A of the Housing Act 1985',
    '13. The claimant is a: local authority',
    '13. The claimant is a: housing action trust',
    '13. The claimant is a: registered social landlord or a private registered provider of social housing',
    '13. The claimant is - other',
    '13. Details if the claimant is some other entity',
    '14. Has the claimant served on the tenant a statement of express terms of the tenancy which are to apply to the demoted tenancy? Yes',
    '14. Has the claimant served on the tenant a statement of express terms of the tenancy which are to apply to the demoted tenancy? No',
    'if the claimant served on the tenant a statement of express terms of the tenancy which are to apply to the demoted tenancy, please give details',
    '15. The claimant is claiming demotion of tenancy',
    '15. The claimant is claiming an order suspending the right to buy 1',
    '15. The claimant is claiming an order suspending the right to buy 2',
    '3(b) The current rent is payable each week',
    'details of the conduct alleged and any other matters relied upon',
    'I believe that the facts stated in these particulars of claim are true',
    'The Claimant believes that the facts stated in these particulars of claim are true. I am authorised by the claimant to sign this statement',
    'Statement of Truth signature box',
    'Statement of Truth signed by Claimant',
    'Statement of Truth signed by Litigation friend (where claimant is a child or a patient)',
    'Statement of Truth signed by Claimant’s legal representative (as defined by CPR 2.3(1))',
    'Date Statement of Truth is signed - MM',
    'Date Statement of Truth is signed - DD',
    'Date Statement of Truth is signed - YYYY',
    'Full name of person signing the Statement of Truth',
    'Name of claimant’s legal representative’s firm',
    'If signing on behalf of firm or company give position or office held',
  ],
  autoFields: [
    'name of court',
    'name of defendant',
    'name of claimant',
    'The claimant has a right to possession of:',
    'To the best of the claimant’s knowledge the following persons are in possession of the property:',
    '3(a) Type of tenancy',
    '3(a) Date of tenancy',
    '3(b) The current rent is',
    '3(b) The current rent is payable each month',
    '3(c) Any unpaid rent or charge for use and occupation should be calculated at £',
    '4. (a) The reason the claimant is asking for possession is:',
    '4. (b) The reason the claimant is asking for possession is:',
    '4. (c) The reason the claimant is asking for possession is:',
    '5. The following steps have already been taken to recover any arrears:',
    '6. Other type of notice',
    '6. Day and month notice served',
    '6. Year notice served',
    '7. The following information is known about the defendant’s circumstances:',
    '8. The claimant is asking the court to take the following financial or other information into account when making its decision whether or not to grant an order for possession:',
    '11. In the alternative to possession, is the claimant asking the court to make a demotion order or an order suspending the right to buy? No',
    '13. The claimant is - other',
    '13. Details if the claimant is some other entity',
    'I believe that the facts stated in these particulars of claim are true',
    'Statement of Truth signature box',
    'Statement of Truth signed by Claimant',
    'Date Statement of Truth is signed - MM',
    'Date Statement of Truth is signed - DD',
    'Date Statement of Truth is signed - YYYY',
    'Full name of person signing the Statement of Truth',
  ],
  conditionalFields: [
    'claim no',
    '3(b) The current rent is payable each fortnight',
    '3(b) The current rent is payable each - specify the period',
    '9. (b) Entitled to relief against forfeiture - name',
    '9. (b) Entitled to relief against forfeiture - address',
    '11. In the alternative to possession, is the claimant asking the court to make a demotion order or an order suspending the right to buy? Yes',
    '12. The (demotion) (suspension) claim is made under: section 82A(2) of the Housing Act 1985',
    '12. The (demotion) (suspension) claim is made under: section 6A(2) of the Housing Act 1988',
    '12. The (demotion) (suspension) claim is made under: section 121A of the Housing Act 1985',
    '13. The claimant is a: local authority',
    '13. The claimant is a: housing action trust',
    '13. The claimant is a: registered social landlord or a private registered provider of social housing',
    '14. Has the claimant served on the tenant a statement of express terms of the tenancy which are to apply to the demoted tenancy? Yes',
    '14. Has the claimant served on the tenant a statement of express terms of the tenancy which are to apply to the demoted tenancy? No',
    'if the claimant served on the tenant a statement of express terms of the tenancy which are to apply to the demoted tenancy, please give details',
    '15. The claimant is claiming demotion of tenancy',
    '15. The claimant is claiming an order suspending the right to buy 1',
    '15. The claimant is claiming an order suspending the right to buy 2',
    '3(b) The current rent is payable each week',
    'details of the conduct alleged and any other matters relied upon',
    'The Claimant believes that the facts stated in these particulars of claim are true. I am authorised by the claimant to sign this statement',
    'Statement of Truth signed by Litigation friend (where claimant is a child or a patient)',
    'Statement of Truth signed by Claimant’s legal representative (as defined by CPR 2.3(1))',
    'Name of claimant’s legal representative’s firm',
    'If signing on behalf of firm or company give position or office held',
  ],
};

export function listManualFields(matrix: OfficialFormFieldMatrix): string[] {
  const handled = new Set([...matrix.autoFields, ...matrix.conditionalFields]);
  return matrix.allFields.filter((field) => !handled.has(field));
}

export function buildFieldCoverageMatrix(matrix: OfficialFormFieldMatrix): Array<{ name: string; category: OfficialFormFieldCategory }> {
  const auto = new Set(matrix.autoFields);
  const conditional = new Set(matrix.conditionalFields);

  return matrix.allFields.map((name) => ({
    name,
    category: auto.has(name) ? 'auto' : conditional.has(name) ? 'conditional' : 'manual',
  }));
}
