import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';

import JSZip from 'jszip';
import {
  PDFCheckBox,
  PDFDocument,
  PDFFont,
  PDFForm,
  PDFImage,
  PDFPage,
  PDFTextField,
  StandardFonts,
  TextAlignment,
  rgb,
} from 'pdf-lib';

import { generateProofOfServicePDF } from '@/lib/documents/proof-of-service-generator';
import { toWinAnsiSafeText } from '@/lib/documents/pdf-safe-text';
import {
  SECTION13_CHALLENGE_EXPLAINER,
  SECTION13_EVIDENCE_EXPLAINER,
  buildSection13JustificationSummaryText,
} from '@/lib/section13/rules';
import type {
  Section13BundleAsset,
  Section13Comparable,
  Section13EvidenceUpload,
  Section13OutputSnapshot,
  Section13ProductSku,
  Section13State,
  Section13WorkflowStatus,
} from '@/lib/section13/types';

const FORM_4A_PATH = path.join(process.cwd(), 'public', 'official-forms', 'Form_4A.pdf');
const BRAND_LOGO_PATH = path.join(process.cwd(), 'public', 'images', 'logo.png');
export const SECTION13_FORM_4A_VERSION = 'england_form_4a_2026-05_may_official_v2' as const;
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN_X = 48;
const MARGIN_Y = 52;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2;
const DEFAULT_FONT_SIZE = 11;
const LINE_HEIGHT = 14;

const SECTION13_DISCLAIMER =
  'This tool provides assistance only. It does not constitute legal advice. Rent increases must be lawful and reasonable. You remain responsible for compliance with all applicable laws.';
const SECTION13_TRIBUNAL_WARNING =
  'The tenant can refer the proposed rent to the tribunal up to the day before the proposed start date. The tribunal can set a lower rent, but not higher than the rent proposed in the notice.';
const SECTION13_BRAND_LABEL = 'Landlord Heaven';
const SECTION13_PROOF_OF_SERVICE_BRAND = `Generated by ${SECTION13_BRAND_LABEL}`;
const SECTION13_NO_EXTERNAL_EVIDENCE_TEXT =
  'No additional external evidence has been uploaded. This bundle currently relies on the comparable analysis and generated core documents.';

export const FORM_4A_OFFICIAL_FIELD_NAMES = {
  text: {
    tenantNames: 'Text Field 109',
    propertyAddressLine1: 'Text Field 93',
    propertyAddressLine2: 'Text Field 92',
    propertyTownCity: 'Text Field 91',
    propertyCounty: 'Text Field 90',
    propertyPostcode: 'Text Field 1018',
    landlordName: 'Text Field 95',
    landlordAddressLine1: 'Text Field 107',
    landlordAddressLine2: 'Text Field 106',
    landlordTownCity: 'Text Field 105',
    landlordCounty: 'Text Field 104',
    landlordPostcode: 'Text Field 103',
    landlordPhone: 'Text Field 99',
    landlordEmail: 'Text Field 100',
    agentName: 'Text Field 128',
    agentAddressLine1: 'Text Field 1017',
    agentAddressLine2: 'Text Field 1016',
    agentTownCity: 'Text Field 1015',
    agentCounty: 'Text Field 1011',
    agentPostcode: 'Text Field 1010',
    agentPhone: 'Text Field 127',
    agentEmail: 'Text Field 101',
    currentRentAmount: 'Text Field 114',
    currentRentFrequency: 'Text Field 113',
    tenancyStartDate: 'Text Field 102',
    lastIncreaseDate: 'Text Field 1014',
    firstIncreaseDate: 'Text Field 1012',
    proposedRentAmount: 'Text Field 116',
    proposedRentFrequency: 'Text Field 115',
    proposedStartDate: 'Text Field 108',
    signature: 'Text Field 111',
    printName: 'Text Field 112',
    signatureDate: 'Text Field 1013',
    jointSignatory1: 'Text Field 1025',
    jointSignatory2: 'Text Field 123',
    jointSignatory3: 'Text Field 122',
    continuationText: 'Text Field 124',
    continuationSignature: 'Text Field 126',
    continuationDate: 'Text Field 125',
  },
  checkboxes: {
    signAsLandlord: 'Check Box 37',
    signAsAgent: 'Check Box 36',
  },
  includedChargeRows: [
    { current: 'Text Field 129', proposed: 'Text Field 130' },
    { current: 'Text Field 131', proposed: 'Text Field 132' },
    { current: 'Text Field 133', proposed: 'Text Field 134' },
    { current: 'Text Field 135', proposed: 'Text Field 136' },
    { current: 'Text Field 137', proposed: 'Text Field 138' },
  ],
} as const;

type OverlayField = {
  pageIndex: number;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize?: number;
  align?: 'left' | 'center' | 'right';
};

type Section13FormOverlayMap = {
  tenantNames: OverlayField;
  propertyAddressLine1: OverlayField;
  propertyAddressLine2: OverlayField;
  propertyTownCity: OverlayField;
  propertyCounty: OverlayField;
  propertyPostcode: OverlayField;
  landlordName: OverlayField;
  landlordAddressLine1: OverlayField;
  landlordAddressLine2: OverlayField;
  landlordTownCity: OverlayField;
  landlordCounty: OverlayField;
  landlordPostcode: OverlayField;
  landlordPhone: OverlayField;
  landlordEmail: OverlayField;
  agentName: OverlayField;
  agentAddressLine1: OverlayField;
  agentAddressLine2: OverlayField;
  agentTownCity: OverlayField;
  agentCounty: OverlayField;
  agentPostcode: OverlayField;
  agentPhone: OverlayField;
  agentEmail: OverlayField;
  currentRentAmount: OverlayField;
  currentRentFrequency: OverlayField;
  tenancyStartDay: OverlayField;
  tenancyStartMonth: OverlayField;
  tenancyStartYear: OverlayField;
  lastIncreaseDay: OverlayField;
  lastIncreaseMonth: OverlayField;
  lastIncreaseYear: OverlayField;
  firstIncreaseDay: OverlayField;
  firstIncreaseMonth: OverlayField;
  firstIncreaseYear: OverlayField;
  proposedRentAmount: OverlayField;
  proposedRentFrequency: OverlayField;
  proposedStartDay: OverlayField;
  proposedStartMonth: OverlayField;
  proposedStartYear: OverlayField;
  includedChargeRows: Array<{
    current: OverlayField;
    proposed: OverlayField;
  }>;
  printName: OverlayField;
  signatureDateDay: OverlayField;
  signatureDateMonth: OverlayField;
  signatureDateYear: OverlayField;
};

type EditableForm4AFieldDefinition =
  | {
      name: string;
      kind: 'text';
      field: OverlayField;
      multiline?: boolean;
    }
  | {
      name: string;
      kind: 'checkbox';
      field: OverlayField;
    };

const FORM4A_SIGN_AS_LANDLORD_FIELD: EditableForm4AFieldDefinition = {
  name: 'form4a_sign_as_landlord',
  kind: 'checkbox',
  field: { pageIndex: 4, x: 57, y: 711, width: 12, height: 12 },
};

const FORM4A_SIGN_AS_AGENT_FIELD: EditableForm4AFieldDefinition = {
  name: 'form4a_sign_as_agent',
  kind: 'checkbox',
  field: { pageIndex: 4, x: 57, y: 690, width: 12, height: 12 },
};

export const FORM_4A_OVERLAY_MAP: Record<string, Record<string, Section13FormOverlayMap>> = {
  'england_assured_section13_2026-05-01': {
    [SECTION13_FORM_4A_VERSION]: {
      tenantNames: { pageIndex: 1, x: 56, y: 652, width: 324, height: 96, fontSize: 11 },
      propertyAddressLine1: { pageIndex: 1, x: 56, y: 566, width: 326, height: 16 },
      propertyAddressLine2: { pageIndex: 1, x: 56, y: 525, width: 326, height: 16 },
      propertyTownCity: { pageIndex: 1, x: 56, y: 480, width: 190, height: 16 },
      propertyCounty: { pageIndex: 1, x: 56, y: 439, width: 190, height: 16 },
      propertyPostcode: { pageIndex: 1, x: 56, y: 399, width: 122, height: 16 },
      landlordName: { pageIndex: 1, x: 56, y: 303, width: 326, height: 18 },
      landlordAddressLine1: { pageIndex: 1, x: 56, y: 224, width: 326, height: 16 },
      landlordAddressLine2: { pageIndex: 1, x: 56, y: 183, width: 326, height: 16 },
      landlordTownCity: { pageIndex: 1, x: 56, y: 138, width: 190, height: 16 },
      landlordCounty: { pageIndex: 1, x: 56, y: 97, width: 190, height: 16 },
      landlordPostcode: { pageIndex: 1, x: 56, y: 54, width: 122, height: 16 },
      landlordPhone: { pageIndex: 2, x: 56, y: 734, width: 160, height: 16 },
      landlordEmail: { pageIndex: 2, x: 56, y: 669, width: 325, height: 16, fontSize: 10 },
      agentName: { pageIndex: 2, x: 56, y: 539, width: 325, height: 18 },
      agentAddressLine1: { pageIndex: 2, x: 56, y: 458, width: 325, height: 16 },
      agentAddressLine2: { pageIndex: 2, x: 56, y: 417, width: 325, height: 16 },
      agentTownCity: { pageIndex: 2, x: 56, y: 373, width: 190, height: 16 },
      agentCounty: { pageIndex: 2, x: 56, y: 332, width: 190, height: 16 },
      agentPostcode: { pageIndex: 2, x: 56, y: 277, width: 122, height: 16 },
      agentPhone: { pageIndex: 2, x: 56, y: 166, width: 160, height: 16 },
      agentEmail: { pageIndex: 2, x: 56, y: 101, width: 325, height: 16, fontSize: 10 },
      currentRentAmount: { pageIndex: 3, x: 67, y: 754, width: 140, height: 16, fontSize: 10 },
      currentRentFrequency: { pageIndex: 3, x: 245, y: 754, width: 158, height: 16, fontSize: 10 },
      tenancyStartDay: { pageIndex: 3, x: 56, y: 684, width: 30, height: 14, fontSize: 10, align: 'center' },
      tenancyStartMonth: { pageIndex: 3, x: 101, y: 684, width: 40, height: 14, fontSize: 10, align: 'center' },
      tenancyStartYear: { pageIndex: 3, x: 146, y: 684, width: 52, height: 14, fontSize: 10, align: 'center' },
      lastIncreaseDay: { pageIndex: 3, x: 56, y: 619, width: 30, height: 14, fontSize: 10, align: 'center' },
      lastIncreaseMonth: { pageIndex: 3, x: 101, y: 619, width: 40, height: 14, fontSize: 10, align: 'center' },
      lastIncreaseYear: { pageIndex: 3, x: 146, y: 619, width: 52, height: 14, fontSize: 10, align: 'center' },
      firstIncreaseDay: { pageIndex: 3, x: 56, y: 548, width: 30, height: 14, fontSize: 10, align: 'center' },
      firstIncreaseMonth: { pageIndex: 3, x: 101, y: 548, width: 40, height: 14, fontSize: 10, align: 'center' },
      firstIncreaseYear: { pageIndex: 3, x: 146, y: 548, width: 52, height: 14, fontSize: 10, align: 'center' },
      proposedRentAmount: { pageIndex: 3, x: 67, y: 474, width: 140, height: 16, fontSize: 10 },
      proposedRentFrequency: { pageIndex: 3, x: 245, y: 474, width: 158, height: 16, fontSize: 10 },
      proposedStartDay: { pageIndex: 3, x: 56, y: 403, width: 30, height: 14, fontSize: 10, align: 'center' },
      proposedStartMonth: { pageIndex: 3, x: 101, y: 403, width: 40, height: 14, fontSize: 10, align: 'center' },
      proposedStartYear: { pageIndex: 3, x: 146, y: 403, width: 52, height: 14, fontSize: 10, align: 'center' },
      includedChargeRows: [270, 247, 220, 188, 161].map((y) => ({
        current: { pageIndex: 3, x: 199, y, width: 76, height: 14, fontSize: 9, align: 'center' },
        proposed: { pageIndex: 3, x: 313, y, width: 76, height: 14, fontSize: 9, align: 'center' },
      })),
      printName: { pageIndex: 4, x: 56, y: 634, width: 240, height: 18 },
      signatureDateDay: { pageIndex: 4, x: 56, y: 558, width: 20, height: 14, fontSize: 10, align: 'center' },
      signatureDateMonth: { pageIndex: 4, x: 102, y: 558, width: 30, height: 14, fontSize: 10, align: 'center' },
      signatureDateYear: { pageIndex: 4, x: 147, y: 558, width: 38, height: 14, fontSize: 10, align: 'center' },
    },
  },
};

let cachedForm4AMetadata: { version: string; sha256: string } | null = null;
let cachedBrandLogoBytes: Uint8Array | null | undefined;

async function getBrandLogoBytes(): Promise<Uint8Array | null> {
  if (cachedBrandLogoBytes !== undefined) {
    return cachedBrandLogoBytes;
  }

  try {
    cachedBrandLogoBytes = await fs.readFile(BRAND_LOGO_PATH);
  } catch {
    cachedBrandLogoBytes = null;
  }

  return cachedBrandLogoBytes;
}

export interface Section13EvidenceFile {
  upload: Section13EvidenceUpload;
  bytes: Uint8Array;
  contentType: string;
}

export interface Section13PersistableDocument {
  title: string;
  description?: string;
  category?: string;
  document_type: string;
  file_name: string;
  pdf: Buffer;
  contentType?: string;
  html?: string | null;
}

export interface Section13GeneratedPack {
  documents: Section13PersistableDocument[];
  bundleAssets: Section13BundleAsset[];
  workflowStatus: Section13WorkflowStatus;
  bundleWarnings: string[];
}

export interface Section13GeneratedBundle {
  documents: Section13PersistableDocument[];
  bundleAssets: Section13BundleAsset[];
  workflowStatus: Extract<Section13WorkflowStatus, 'bundle_partial_warning' | 'bundle_ready'>;
  bundleWarnings: string[];
}

export const SECTION13_CORE_DOCUMENT_TYPES = [
  'section13_form_4a',
  'section13_justification_report',
  'section13_proof_of_service_record',
  'section13_cover_letter',
] as const;

export const SECTION13_DEFENSIVE_DOCUMENT_TYPES = [
  ...SECTION13_CORE_DOCUMENT_TYPES,
  'section13_tribunal_argument_summary',
  'section13_tribunal_defence_guide',
  'section13_landlord_response_template',
  'section13_legal_briefing',
] as const;

export const SECTION13_PREVIEWABLE_DOCUMENT_TYPES = SECTION13_DEFENSIVE_DOCUMENT_TYPES;

export type Section13PreviewableDocumentType =
  typeof SECTION13_PREVIEWABLE_DOCUMENT_TYPES[number];

export const SECTION13_BUNDLE_DOCUMENT_TYPES = [
  'section13_tribunal_bundle',
  'section13_tribunal_bundle_zip',
] as const;

export const SECTION13_BUNDLE_SOURCE_DOCUMENT_TYPES = [
  'section13_form_4a',
  'section13_justification_report',
  'section13_tribunal_argument_summary',
  'section13_proof_of_service_record',
  'section13_cover_letter',
  'section13_tribunal_defence_guide',
  'section13_landlord_response_template',
  'section13_legal_briefing',
] as const;

export function isSection13PreviewableDocumentType(
  documentType: string
): documentType is Section13PreviewableDocumentType {
  return (SECTION13_PREVIEWABLE_DOCUMENT_TYPES as readonly string[]).includes(documentType);
}

type SectionBlock = {
  heading?: string;
  lines: string[];
  variant?: 'default' | 'intro' | 'callout';
};

type BundleArtifact = {
  title: string;
  logicalSection: Section13BundleAsset['logicalSection'];
  assetType: Section13BundleAsset['assetType'];
  sourceKind: Section13BundleAsset['sourceKind'];
  includeInMerged: boolean;
  exhibitLabel?: string | null;
  pageCount?: number | null;
  status: Section13BundleAsset['status'];
  generationError?: string | null;
  documentType?: string | null;
  sourceDocumentId?: string | null;
  sourceUploadId?: string | null;
  metadata?: Record<string, unknown>;
};

export type Section13BundleSourceDocument = Pick<
  Section13PersistableDocument,
  'title' | 'description' | 'document_type' | 'file_name' | 'pdf'
> & {
  sourceDocumentId?: string | null;
};

function safeText(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return '';
  return toWinAnsiSafeText(String(value));
}

function formatCurrency(value: number | string | null | undefined): string {
  if (value === null || value === undefined || value === '') {
    return 'nil';
  }

  const numeric = typeof value === 'number' ? value : Number(String(value).replace(/[^\d.-]/g, ''));
  if (Number.isNaN(numeric)) {
    return String(value);
  }

  return `£${numeric.toFixed(2)}`;
}

function formatCurrencyFieldValue(value: number | string | null | undefined): string {
  if (value === null || value === undefined || value === '') {
    return 'nil';
  }

  const numeric = typeof value === 'number' ? value : Number(String(value).replace(/[^\d.-]/g, ''));
  if (Number.isNaN(numeric)) {
    return String(value);
  }

  return numeric.toFixed(2);
}

function formatDateUk(dateString?: string | null): string {
  if (!dateString) return '';
  const date = new Date(`${dateString}T00:00:00.000Z`);
  if (Number.isNaN(date.getTime())) return dateString;
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(date);
}

function splitDate(dateString?: string | null): { day: string; month: string; year: string } {
  if (!dateString) return { day: '', month: '', year: '' };
  const [year = '', month = '', day = ''] = dateString.split('T')[0].split('-');
  return { day, month, year };
}

function formatCombDateValue(dateString?: string | null): string {
  const { day, month, year } = splitDate(dateString);
  return `${day}${month}${year}`;
}

function formatOfficialPostcodeValue(postcode?: string | null): string {
  return String(postcode || '').toUpperCase().replace(/\s+/g, '');
}

function frequencyLabel(frequency: string): string {
  switch (frequency) {
    case 'weekly':
      return 'per week';
    case 'fortnightly':
      return 'per fortnight';
    case '4-weekly':
      return 'per four weeks';
    case 'monthly':
    case 'pcm':
      return 'per month';
    case 'ppw':
      return 'per week';
    default:
      return frequency;
  }
}

function compactFrequency(frequency: string): string {
  switch (frequency) {
    case 'weekly':
      return 'weekly';
    case 'fortnightly':
      return 'fortnightly';
    case '4-weekly':
      return '4-weekly';
    case 'monthly':
    case 'pcm':
      return 'monthly';
    case 'ppw':
      return 'weekly';
    default:
      return frequency;
  }
}

function toTitleFrequency(frequency: string): string {
  return compactFrequency(frequency).replace(/(^|-)([a-z])/g, (_, prefix: string, char: string) => `${prefix}${char.toUpperCase()}`);
}

function buildAddress(parts: Array<string | null | undefined>): string {
  return parts.map((part) => String(part || '').trim()).filter(Boolean).join(', ');
}

function buildPropertyAddress(state: Section13State): string {
  return buildAddress([
    state.tenancy.propertyAddressLine1,
    state.tenancy.propertyAddressLine2,
    state.tenancy.propertyTownCity,
    state.tenancy.postcodeNormalized || state.tenancy.postcodeRaw,
  ]);
}

function buildLandlordAddress(state: Section13State): string {
  return buildAddress([
    state.landlord.landlordAddressLine1,
    state.landlord.landlordAddressLine2,
    state.landlord.landlordTownCity,
    state.landlord.landlordPostcodeNormalized || state.landlord.landlordPostcodeRaw,
  ]);
}

function buildAgentAddress(state: Section13State): string {
  return buildAddress([
    state.landlord.agentAddressLine1,
    state.landlord.agentAddressLine2,
    state.landlord.agentTownCity,
    state.landlord.agentPostcodeNormalized || state.landlord.agentPostcodeRaw,
  ]);
}

function getSnapshotState(state: Section13State, snapshot?: Section13OutputSnapshot | null): Section13State {
  return snapshot?.stateSnapshot || state;
}

function getSnapshotComparables(
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): Section13Comparable[] {
  return snapshot?.comparableSnapshot?.length ? snapshot.comparableSnapshot : comparables;
}

function buildJustificationNarrativeText(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  if (snapshot?.justificationNarrativeText?.trim()) {
    return snapshot.justificationNarrativeText.trim();
  }

  const summary = buildSection13JustificationSummaryText(state, state.preview);
  const manual = state.adjustments.manualJustification?.trim();
  return manual ? `${summary} ${manual}` : summary;
}

function getJustificationSummaryText(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  return snapshot?.justificationSummaryText || buildSection13JustificationSummaryText(state, state.preview);
}

function getDefensibilitySummaryText(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  return (
    snapshot?.defensibilitySummarySentence ||
    state.preview?.defensibilitySummarySentence ||
    'Add a proposed rent and enough recent source-backed comparables to generate a defensibility summary.'
  );
}

function drawOverlayText(
  page: PDFPage | undefined,
  field: OverlayField | undefined,
  text: string,
  font: PDFFont,
  options?: { fontSize?: number }
) {
  if (!page || !field) return;

  drawTextBox({
    page,
    text,
    x: field.x,
    y: field.y,
    width: field.width,
    height: field.height,
    font,
    fontSize: options?.fontSize || field.fontSize,
    align: field.align,
  });
}

export async function getSection13Form4AAssetMetadata(): Promise<{ version: string; sha256: string }> {
  if (cachedForm4AMetadata) {
    return cachedForm4AMetadata;
  }

  const sourceBytes = await fs.readFile(FORM_4A_PATH);
  cachedForm4AMetadata = {
    version: SECTION13_FORM_4A_VERSION,
    sha256: crypto.createHash('sha256').update(sourceBytes).digest('hex'),
  };

  return cachedForm4AMetadata;
}

function getForm4AOverlayMap(rulesVersion: string): Section13FormOverlayMap {
  return (
    FORM_4A_OVERLAY_MAP[rulesVersion]?.[SECTION13_FORM_4A_VERSION] ||
    FORM_4A_OVERLAY_MAP['england_assured_section13_2026-05-01'][SECTION13_FORM_4A_VERSION]
  );
}

function wrapText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
  const paragraphs = safeText(text).split('\n');
  const lines: string[] = [];

  for (const paragraph of paragraphs) {
    const words = paragraph.split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      lines.push('');
      continue;
    }

    let currentLine = words[0];
    for (let index = 1; index < words.length; index += 1) {
      const nextLine = `${currentLine} ${words[index]}`;
      if (font.widthOfTextAtSize(nextLine, fontSize) <= maxWidth) {
        currentLine = nextLine;
      } else {
        lines.push(currentLine);
        currentLine = words[index];
      }
    }
    lines.push(currentLine);
  }

  return lines;
}

function drawWrappedText(params: {
  page: PDFPage;
  text: string;
  x: number;
  y: number;
  width: number;
  height?: number;
  font: PDFFont;
  fontSize?: number;
  lineHeight?: number;
  align?: 'left' | 'center' | 'right';
}): void {
  const {
    page,
    text,
    x,
    y,
    width,
    height = Number.POSITIVE_INFINITY,
    font,
    fontSize = DEFAULT_FONT_SIZE,
    lineHeight = fontSize + 2,
    align = 'left',
  } = params;

  const lines = wrapText(text, font, fontSize, width);
  let cursorY = y;

  for (const line of lines) {
    if (cursorY < y - height + lineHeight) {
      break;
    }
    const safeLine = safeText(line);
    const textWidth = font.widthOfTextAtSize(safeLine, fontSize);
    const drawX =
      align === 'center'
        ? x + Math.max((width - textWidth) / 2, 0)
        : align === 'right'
          ? x + Math.max(width - textWidth, 0)
          : x;
    page.drawText(safeText(line), {
      x: drawX,
      y: cursorY,
      font,
      size: fontSize,
      color: rgb(0.12, 0.12, 0.12),
    });
    cursorY -= lineHeight;
  }
}

function drawTextBox(params: {
  page: PDFPage;
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  font: PDFFont;
  fontSize?: number;
  align?: 'left' | 'center' | 'right';
}): void {
  drawWrappedText({
    page: params.page,
    text: params.text,
    x: params.x,
    y: params.y + params.height - (params.fontSize || DEFAULT_FONT_SIZE) - 1,
    width: params.width,
    height: params.height,
    font: params.font,
    fontSize: params.fontSize,
    align: params.align,
  });
}

function drawCheck(page: PDFPage, x: number, y: number): void {
  page.drawLine({
    start: { x, y },
    end: { x: x + 8, y: y + 8 },
    thickness: 1.5,
    color: rgb(0.15, 0.15, 0.15),
  });
  page.drawLine({
    start: { x, y: y + 8 },
    end: { x: x + 8, y },
    thickness: 1.5,
    color: rgb(0.15, 0.15, 0.15),
  });
}

function buildEditableForm4AFieldDefinitions(
  overlay: Section13FormOverlayMap
): EditableForm4AFieldDefinition[] {
  return [
    { name: 'form4a_tenant_names', kind: 'text', field: overlay.tenantNames, multiline: true },
    { name: 'form4a_property_address_line1', kind: 'text', field: overlay.propertyAddressLine1 },
    { name: 'form4a_property_address_line2', kind: 'text', field: overlay.propertyAddressLine2 },
    { name: 'form4a_property_town_city', kind: 'text', field: overlay.propertyTownCity },
    { name: 'form4a_property_county', kind: 'text', field: overlay.propertyCounty },
    { name: 'form4a_property_postcode', kind: 'text', field: overlay.propertyPostcode },
    { name: 'form4a_landlord_name', kind: 'text', field: overlay.landlordName },
    { name: 'form4a_landlord_address_line1', kind: 'text', field: overlay.landlordAddressLine1 },
    { name: 'form4a_landlord_address_line2', kind: 'text', field: overlay.landlordAddressLine2 },
    { name: 'form4a_landlord_town_city', kind: 'text', field: overlay.landlordTownCity },
    { name: 'form4a_landlord_county', kind: 'text', field: overlay.landlordCounty },
    { name: 'form4a_landlord_postcode', kind: 'text', field: overlay.landlordPostcode },
    { name: 'form4a_landlord_phone', kind: 'text', field: overlay.landlordPhone },
    { name: 'form4a_landlord_email', kind: 'text', field: overlay.landlordEmail },
    { name: 'form4a_agent_name', kind: 'text', field: overlay.agentName },
    { name: 'form4a_agent_address_line1', kind: 'text', field: overlay.agentAddressLine1 },
    { name: 'form4a_agent_address_line2', kind: 'text', field: overlay.agentAddressLine2 },
    { name: 'form4a_agent_town_city', kind: 'text', field: overlay.agentTownCity },
    { name: 'form4a_agent_county', kind: 'text', field: overlay.agentCounty },
    { name: 'form4a_agent_postcode', kind: 'text', field: overlay.agentPostcode },
    { name: 'form4a_agent_phone', kind: 'text', field: overlay.agentPhone },
    { name: 'form4a_agent_email', kind: 'text', field: overlay.agentEmail },
    { name: 'form4a_current_rent_amount', kind: 'text', field: overlay.currentRentAmount },
    { name: 'form4a_current_rent_frequency', kind: 'text', field: overlay.currentRentFrequency },
    { name: 'form4a_tenancy_start_day', kind: 'text', field: overlay.tenancyStartDay },
    { name: 'form4a_tenancy_start_month', kind: 'text', field: overlay.tenancyStartMonth },
    { name: 'form4a_tenancy_start_year', kind: 'text', field: overlay.tenancyStartYear },
    { name: 'form4a_last_increase_day', kind: 'text', field: overlay.lastIncreaseDay },
    { name: 'form4a_last_increase_month', kind: 'text', field: overlay.lastIncreaseMonth },
    { name: 'form4a_last_increase_year', kind: 'text', field: overlay.lastIncreaseYear },
    { name: 'form4a_first_increase_day', kind: 'text', field: overlay.firstIncreaseDay },
    { name: 'form4a_first_increase_month', kind: 'text', field: overlay.firstIncreaseMonth },
    { name: 'form4a_first_increase_year', kind: 'text', field: overlay.firstIncreaseYear },
    { name: 'form4a_proposed_rent_amount', kind: 'text', field: overlay.proposedRentAmount },
    { name: 'form4a_proposed_rent_frequency', kind: 'text', field: overlay.proposedRentFrequency },
    { name: 'form4a_proposed_start_day', kind: 'text', field: overlay.proposedStartDay },
    { name: 'form4a_proposed_start_month', kind: 'text', field: overlay.proposedStartMonth },
    { name: 'form4a_proposed_start_year', kind: 'text', field: overlay.proposedStartYear },
    { name: 'form4a_print_name', kind: 'text', field: overlay.printName },
    { name: 'form4a_signature_date_day', kind: 'text', field: overlay.signatureDateDay },
    { name: 'form4a_signature_date_month', kind: 'text', field: overlay.signatureDateMonth },
    { name: 'form4a_signature_date_year', kind: 'text', field: overlay.signatureDateYear },
    ...overlay.includedChargeRows.flatMap((chargeRow, index) => ([
      { name: `form4a_included_charge_${index + 1}_current`, kind: 'text' as const, field: chargeRow.current },
      { name: `form4a_included_charge_${index + 1}_proposed`, kind: 'text' as const, field: chargeRow.proposed },
    ])),
    FORM4A_SIGN_AS_LANDLORD_FIELD,
    FORM4A_SIGN_AS_AGENT_FIELD,
  ];
}

function applyEditableFieldLayout(
  textField: PDFTextField,
  definition: Extract<EditableForm4AFieldDefinition, { kind: 'text' }>
) {
  if (definition.multiline) {
    textField.enableMultiline();
  }

  if (definition.field.align === 'center') {
    textField.setAlignment(TextAlignment.Center);
  } else if (definition.field.align === 'right') {
    textField.setAlignment(TextAlignment.Right);
  } else {
    textField.setAlignment(TextAlignment.Left);
  }

  if (definition.field.fontSize) {
    textField.setFontSize(definition.field.fontSize);
  }
}

function createEditableForm4AOverlay(
  form: PDFForm,
  pdfDoc: PDFDocument,
  overlay: Section13FormOverlayMap
) {
  const pages = pdfDoc.getPages();
  for (const definition of buildEditableForm4AFieldDefinitions(overlay)) {
    const page = pages[definition.field.pageIndex];
    if (!page) continue;

    if (definition.kind === 'text') {
      const field = form.createTextField(definition.name);
      field.addToPage(page, {
        x: definition.field.x,
        y: definition.field.y,
        width: definition.field.width,
        height: definition.field.height,
        borderWidth: 0,
      });
      applyEditableFieldLayout(field, definition);
      continue;
    }

    const field = form.createCheckBox(definition.name);
    field.addToPage(page, {
      x: definition.field.x,
      y: definition.field.y,
      width: definition.field.width,
      height: definition.field.height,
      borderWidth: 0,
    });
  }
}

function setEditableTextFieldValue(form: PDFForm, fieldName: string, value: string) {
  const field = form.getFieldMaybe(fieldName);
  if (field instanceof PDFTextField) {
    field.setText(safeText(value));
  }
}

function setEditableCheckboxValue(form: PDFForm, fieldName: string, checked: boolean) {
  const field = form.getFieldMaybe(fieldName);
  if (field instanceof PDFCheckBox) {
    if (checked) {
      field.check();
    } else {
      field.uncheck();
    }
  }
}

async function pageCount(bytes: Uint8Array): Promise<number> {
  const pdf = await PDFDocument.load(bytes);
  return pdf.getPageCount();
}

async function createNarrativePdf(title: string, blocks: SectionBlock[], footer?: string): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const logoBytes = await getBrandLogoBytes();
  const logoImage = logoBytes ? await pdfDoc.embedPng(logoBytes) : null;
  let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursorY = PAGE_HEIGHT - MARGIN_Y;
  const titleFontSize = 18;
  const headingFontSize = 12;
  const bodyFontSize = 10.5;
  const bodyLineHeight = 13.5;
  const brandText = rgb(0.204, 0.141, 0.373);
  const brandTextStrong = rgb(0.141, 0.09, 0.247);
  const brandMuted = rgb(0.424, 0.365, 0.561);
  const brandSurface = rgb(0.965, 0.945, 1);
  const brandSurfaceStrong = rgb(0.929, 0.894, 1);
  const brandPanel = rgb(0.984, 0.98, 1);
  const brandBorder = rgb(0.847, 0.8, 0.965);
  const brandBorderStrong = rgb(0.776, 0.714, 0.937);

  const drawHeader = () => {
    let headerY = PAGE_HEIGHT - MARGIN_Y;

    if (logoImage) {
      const scaled = logoImage.scaleToFit(168, 34);
      page.drawImage(logoImage, {
        x: MARGIN_X,
        y: headerY - scaled.height + 2,
        width: scaled.width,
        height: scaled.height,
      });
      headerY -= scaled.height + 10;
    } else {
      page.drawText(safeText(SECTION13_BRAND_LABEL), {
        x: MARGIN_X,
        y: headerY,
        font: bold,
        size: 10,
        color: brandText,
      });
      headerY -= 16;
    }

    page.drawText(safeText(title), {
      x: MARGIN_X,
      y: headerY,
      font: bold,
      size: titleFontSize,
      color: brandTextStrong,
    });
    headerY -= 12;

    page.drawLine({
      start: { x: MARGIN_X, y: headerY },
      end: { x: PAGE_WIDTH - MARGIN_X, y: headerY },
      thickness: 1,
      color: brandBorder,
    });

    cursorY = headerY - 14;
  };

  const addPage = () => {
    page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    drawHeader();
  };

  const ensureSpace = (needed: number) => {
    if (cursorY - needed < MARGIN_Y) {
      addPage();
    }
  };

  drawHeader();

  for (const [blockIndex, block] of blocks.entries()) {
    const blockFontSize = block.variant === 'intro' ? bodyFontSize : bodyFontSize;
    const blockLineHeight = block.variant === 'intro' ? bodyLineHeight : bodyLineHeight;
    const paragraphHeights = block.lines.map((paragraph) => {
      const wrapped = wrapText(
        paragraph,
        font,
        blockFontSize,
        CONTENT_WIDTH - (block.variant === 'intro' || block.variant === 'callout' ? 28 : 0)
      );
      return wrapped.length * blockLineHeight + 6;
    });
    const totalParagraphHeight = paragraphHeights.reduce((sum, value) => sum + value, 0);

    if (block.heading && block.variant !== 'callout') {
      ensureSpace(28);
      page.drawText(safeText(block.heading), {
        x: MARGIN_X,
        y: cursorY,
        font: bold,
        size: headingFontSize,
        color: brandTextStrong,
      });
      const headingWidth = bold.widthOfTextAtSize(safeText(block.heading), headingFontSize);
      page.drawLine({
        start: { x: MARGIN_X + headingWidth + 12, y: cursorY + 6 },
        end: { x: PAGE_WIDTH - MARGIN_X, y: cursorY + 6 },
        thickness: 0.7,
        color: brandBorder,
      });
      cursorY -= 18;
    }

    if (block.variant === 'intro' || block.variant === 'callout') {
      const panelPaddingX = 12;
      const panelPaddingY = 10;
      const headingHeight = block.variant === 'callout' && block.heading ? 22 : 0;
      const panelHeight = totalParagraphHeight + panelPaddingY * 2 + headingHeight;
      ensureSpace(panelHeight + 8);
      page.drawRectangle({
        x: MARGIN_X,
        y: cursorY - panelHeight + 6,
        width: CONTENT_WIDTH,
        height: panelHeight,
        color: block.variant === 'intro' ? brandSurface : brandSurfaceStrong,
        borderColor: block.variant === 'intro' ? brandBorder : brandBorderStrong,
        borderWidth: 1,
      });
      cursorY -= panelPaddingY;
      if (block.variant === 'callout' && block.heading) {
        page.drawText(safeText(block.heading), {
          x: MARGIN_X + panelPaddingX,
          y: cursorY,
          font: bold,
          size: 11.5,
          color: brandTextStrong,
        });
        cursorY -= 17;
      }
      for (const paragraph of block.lines) {
        const wrapped = wrapText(paragraph, font, blockFontSize, CONTENT_WIDTH - panelPaddingX * 2);
        ensureSpace(wrapped.length * blockLineHeight + 6);
        for (const line of wrapped) {
          page.drawText(safeText(line), {
            x: MARGIN_X + panelPaddingX,
            y: cursorY,
            font,
            size: blockFontSize,
            color: brandText,
          });
          cursorY -= blockLineHeight;
        }
        cursorY -= 4;
      }
      cursorY -= panelPaddingY - 6;
      continue;
    }

    for (const paragraph of block.lines) {
      const wrapped = wrapText(paragraph, font, blockFontSize, CONTENT_WIDTH);
      ensureSpace(wrapped.length * blockLineHeight + 6);
      for (const line of wrapped) {
        page.drawText(safeText(line), {
          x: MARGIN_X,
          y: cursorY,
          font,
          size: blockFontSize,
          color: brandText,
        });
        cursorY -= blockLineHeight;
      }
      cursorY -= 4;
    }

    if (blockIndex < blocks.length - 1) {
      cursorY -= 2;
    }
  }

  if (footer) {
    const pages = pdfDoc.getPages();
    for (const [index, item] of pages.entries()) {
      item.drawLine({
        start: { x: MARGIN_X, y: 36 },
        end: { x: PAGE_WIDTH - MARGIN_X, y: 36 },
        thickness: 0.5,
        color: brandBorder,
      });
      item.drawText(safeText(footer), {
        x: MARGIN_X,
        y: 20,
        font,
        size: 8,
        color: brandMuted,
      });
      const pageNumber = `Page ${index + 1} of ${pages.length}`;
      item.drawText(pageNumber, {
        x: PAGE_WIDTH - MARGIN_X - font.widthOfTextAtSize(pageNumber, 8),
        y: 20,
        font,
        size: 8,
        color: brandMuted,
      });
    }
  }

  return pdfDoc.save();
}

function buildJustificationSummary(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  return getJustificationSummaryText(state, snapshot);
}

function getResolvedPreview(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
) {
  return snapshot?.previewMetrics || state.preview;
}

function buildBandSummaryLine(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  if (!preview) {
    return 'Challenge and evidence bands are not available until the comparable analysis is complete.';
  }

  return `Challenge band: ${preview.challengeBandLabel}. Evidence band: ${preview.evidenceBandLabel}.`;
}

function formatBedroomDescriptor(bedrooms?: number | null): string {
  if (!bedrooms || bedrooms <= 0) {
    return '';
  }

  const words: Record<number, string> = {
    1: 'one-bedroom',
    2: 'two-bedroom',
    3: 'three-bedroom',
    4: 'four-bedroom',
    5: 'five-bedroom',
  };

  return words[bedrooms] || `${bedrooms}-bedroom`;
}

function pluralizeComparablePropertyType(propertyType: string, count: number): string {
  const trimmed = propertyType.trim();
  if (!trimmed) {
    return count === 1 ? 'home' : 'homes';
  }

  if (count === 1 || trimmed.endsWith('s')) {
    return trimmed;
  }

  return `${trimmed}s`;
}

function buildComparableGrounding(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  const comparableCount = preview?.comparableCount ?? comparables.length;
  if (comparableCount <= 0) {
    return 'the recorded comparable evidence available for this tenancy';
  }

  const sourceBackedCount = preview?.sourceBackedCount ?? 0;
  const freshComparableCount = preview?.freshComparableCount ?? 0;
  const bedroomDescriptor = formatBedroomDescriptor(
    state.comparablesMeta.bedrooms || state.tenancy.bedrooms || null
  );
  const propertyTypes = Array.from(
    new Set(
      comparables
        .map((item) => item.propertyType?.trim().toLowerCase())
        .filter((value): value is string => Boolean(value))
    )
  );
  const propertyDescriptor =
    propertyTypes.length === 1
      ? pluralizeComparablePropertyType(propertyTypes[0], comparableCount)
      : 'properties';
  const descriptor = bedroomDescriptor ? `${bedroomDescriptor} ${propertyDescriptor}` : propertyDescriptor;

  const freshnessFragment =
    freshComparableCount === comparableCount
      ? 'all listed within the last 90 days'
      : freshComparableCount > 0
        ? `${freshComparableCount} listed within the last 90 days`
        : 'no dated listings within the 90-day freshness window';
  const sourceBackedFragment =
    sourceBackedCount === comparableCount
      ? 'all source-backed'
      : sourceBackedCount > 0
        ? `${sourceBackedCount} source-backed`
        : 'no source-backed entries';

  return `${comparableCount} comparable ${descriptor} within 0.5 miles, with ${freshnessFragment} and ${sourceBackedFragment}`;
}

function buildComparableGroundingSentence(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  const comparableCount = preview?.comparableCount ?? comparables.length;

  if (comparableCount <= 0) {
    return 'Comparable analysis is not complete enough yet to describe the local market evidence base.';
  }

  const sourceBackedCount = preview?.sourceBackedCount ?? 0;
  const freshComparableCount = preview?.freshComparableCount ?? 0;
  const bedroomDescriptor = formatBedroomDescriptor(
    state.comparablesMeta.bedrooms || state.tenancy.bedrooms || null
  );
  const descriptor = bedroomDescriptor ? `${bedroomDescriptor} homes` : 'homes';

  const freshnessFragment =
    freshComparableCount === comparableCount
      ? 'all listed within the last 90 days'
      : freshComparableCount > 0
        ? `${freshComparableCount} listed within the last 90 days`
        : 'with no dated listings inside the last 90 days';

  const sourceBackedFragment =
    sourceBackedCount === comparableCount
      ? 'all source-backed'
      : sourceBackedCount > 0
        ? `${sourceBackedCount} source-backed`
        : 'no source-backed entries';

  if (freshComparableCount === comparableCount && sourceBackedCount === comparableCount) {
    return `This proposal is grounded in ${comparableCount} comparable ${descriptor} within 0.5 miles, all listed within the last 90 days and all source-backed.`;
  }

  return `This proposal is grounded in ${comparableCount} comparable ${descriptor} within 0.5 miles, with ${freshnessFragment} and ${sourceBackedFragment}.`;
}

function getMedianPositionFragment(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  if (!preview || preview.proposedRentMonthly == null || preview.median == null) {
    return 'without a settled median position yet';
  }

  if (preview.proposedRentMonthly < preview.median) {
    return `below the adjusted median of ${formatCurrency(preview.median)} pcm`;
  }

  if (preview.proposedRentMonthly > preview.median) {
    return `above the adjusted median of ${formatCurrency(preview.median)} pcm`;
  }

  return `at the adjusted median of ${formatCurrency(preview.median)} pcm`;
}

function getCasePositionVariants(context: {
  state: Section13State;
  comparables?: Section13Comparable[];
  snapshot?: Section13OutputSnapshot | null;
}): {
  cover: string;
  justification: string;
  argument: string;
  defensive: string;
} {
  const { state, snapshot } = context;
  const preview = getResolvedPreview(state, snapshot);
  const comparables = context.comparables || [];
  const proposedRent = `${formatCurrency(state.proposal.proposedRentAmount)} ${frequencyLabel(
    state.tenancy.currentRentFrequency
  )}`;

  if (!preview) {
    return {
      cover:
        'The proposed increase can be turned into a service-ready notice pack once the comparable analysis and validation checks are complete.',
      justification:
        'The recorded facts can be analysed properly once the comparable evidence and validation checks are complete.',
      argument:
        'The proposed rent can only be defended once the comparable analysis and validation checks are complete on the saved facts.',
      defensive:
        'The landlord position should not be advanced until the comparable analysis and validation checks are complete on the saved facts.',
    };
  }

  const grounding = buildComparableGrounding(state, comparables, snapshot);
  const positionFragment = getMedianPositionFragment(state, snapshot);

  if (!preview.enteredStartDateValid || preview.validationIssues.length > 0) {
    return {
      cover:
        'The proposed increase already has recorded supporting evidence, but the saved facts still need validation issues resolved before service.',
      justification:
        `The file already records ${grounding}, but the saved facts still need validation issues resolved before the proposal can be relied on.`,
      argument:
        `The proposed rent of ${proposedRent} already has ${grounding} behind it, but the landlord should resolve the saved validation issues before advancing the case.`,
      defensive:
        `The landlord position remains anchored to ${grounding}, but the file should only be advanced once the recorded validation issues have been resolved.`,
    };
  }

  return {
    cover: `This proposed rent is supported by ${grounding} and sits ${positionFragment}. The notice file is ready to serve on the recorded facts.`,
    justification: `The recorded comparables support the proposed rent and place it ${positionFragment}.`,
    argument: `The proposed rent of ${proposedRent} is supported by current comparable evidence and sits ${positionFragment}.`,
    defensive: `The landlord relies on the comparable evidence in this file and says the proposed rent of ${proposedRent} should be judged against that market evidence, not against the size of the increase alone.`,
  };
}

function buildBandingSummary(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  return `${preview?.challengeBandLabel || 'Challenge band unavailable'}; ${
    preview?.evidenceBandLabel || 'evidence band unavailable'
  }.`;
}

function buildConclusionSentence(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);

  if (!preview) {
    return 'The proposed rent can be concluded on once the comparable analysis is complete.';
  }

  if (!preview.enteredStartDateValid || preview.validationIssues.length > 0) {
    return 'The proposed rent has supporting market evidence, but the notice file still needs the recorded validation issues resolved before service.';
  }

  if (
    preview.proposedRentMonthly == null ||
    preview.lowerQuartile == null ||
    preview.median == null ||
    preview.upperQuartile == null
  ) {
    return 'The proposed rent is supported by current market evidence and remains tied to the recorded comparable file.';
  }

  if (preview.proposedRentMonthly <= preview.lowerQuartile) {
    return 'The proposed rent is supported by current market evidence and sits within the lower end of comparable properties locally.';
  }

  if (preview.proposedRentMonthly <= preview.median) {
    return 'The proposed rent is supported by current market evidence and sits within the lower-to-mid range of comparable properties locally.';
  }

  if (preview.proposedRentMonthly <= preview.upperQuartile) {
    return 'The proposed rent is supported by current market evidence and sits within the mid-to-upper range of comparable properties locally.';
  }

  return 'The proposed rent is supported by current market evidence and sits above the upper quartile of comparable properties locally.';
}

function buildPackAnchorSentence(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  if (!preview) {
    return 'The pack is ready to record the landlord’s proposed increase once the comparable analysis and validation checks are complete.';
  }

  if (!preview.enteredStartDateValid || preview.validationIssues.length > 0) {
    return 'The pack records the proposed increase and supporting market evidence, but the saved facts still show issues to resolve before service.';
  }

  const supportedByCount =
    preview.freshComparableCount > 0
      ? preview.freshComparableCount
      : preview.sourceBackedCount > 0
        ? preview.sourceBackedCount
        : preview.comparableCount;

  const supportLabel =
    preview.freshComparableCount > 0
      ? 'recent source-backed comparables'
      : preview.sourceBackedCount > 0
        ? 'source-backed comparables'
        : 'recorded comparables';

  let medianPosition = 'keeps the proposed rent anchored to the adjusted local market evidence';
  if (preview.proposedRentMonthly != null && preview.median != null) {
    medianPosition =
      preview.proposedRentMonthly < preview.median
        ? 'places the proposed rent below the adjusted local median'
        : preview.proposedRentMonthly > preview.median
          ? 'places the proposed rent above the adjusted local median'
          : 'places the proposed rent at the adjusted local median';
  }

  return `This notice pack is ready for service on the saved facts, is supported by ${supportedByCount} ${supportLabel}, and ${medianPosition}.`;
}

function buildMarketPositionSentence(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  if (
    !preview ||
    preview.proposedRentMonthly == null ||
    preview.lowerQuartile == null ||
    preview.median == null ||
    preview.upperQuartile == null
  ) {
    return 'Comparable analysis is not complete enough to place the proposed rent within an adjusted market range.';
  }

  let positionText = 'within the adjusted comparable range';
  if (preview.proposedRentMonthly <= preview.lowerQuartile) {
    positionText = 'at or below the lower quartile of the adjusted comparable range';
  } else if (preview.proposedRentMonthly <= preview.median) {
    positionText = 'between the lower quartile and the median of the adjusted comparable range';
  } else if (preview.proposedRentMonthly <= preview.upperQuartile) {
    positionText = 'between the median and the upper quartile of the adjusted comparable range';
  } else {
    positionText = 'above the upper quartile of the adjusted comparable range';
  }

  return `The proposed rent of ${formatCurrency(state.proposal.proposedRentAmount)} ${frequencyLabel(state.tenancy.currentRentFrequency)} sits ${positionText}, against an adjusted range of ${formatCurrency(preview.lowerQuartile)} to ${formatCurrency(preview.upperQuartile)} pcm and a median of ${formatCurrency(preview.median)} pcm.`;
}

function buildEvidenceStrengthSentence(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string {
  const preview = getResolvedPreview(state, snapshot);
  if (!preview) {
    return 'Evidence strength cannot be described until comparable data has been added.';
  }

  const base = `${preview.evidenceBandLabel} is based on ${preview.comparableCount} comparable home${preview.comparableCount === 1 ? '' : 's'}, ${preview.sourceBackedCount} source-backed entr${preview.sourceBackedCount === 1 ? 'y' : 'ies'}, and ${preview.freshComparableCount} comparables dated within the 90-day freshness window.`;

  if (preview.evidenceBand === 'strong') {
    return `${base} The file reads as a well-supported market review rather than a bare assertion.`;
  }

  if (preview.evidenceBand === 'moderate') {
    return `${base} The proposal is supportable, but the landlord should stay disciplined and rely on the recorded adjustments rather than broad statements about the market.`;
  }

  const hasLinkedEvidence = comparables.some((item) => item.sourceUrl);
  return `${base} The landlord should expect closer scrutiny, so the explanation should stay anchored to the current comparables${hasLinkedEvidence ? ' and saved listing links' : ''}.`;
}

function buildComparableHighlights(
  comparables: Section13Comparable[],
  limit = 3
): string[] {
  return comparables.slice(0, limit).map((comparable, index) => {
    const sourceDate = comparable.sourceDateValue
      ? `, dated ${formatDateUk(comparable.sourceDateValue)}`
      : '';
    return `Comparable ${index + 1}: ${comparable.addressSnippet} at ${formatCurrency(comparable.rawRentValue)} ${compactFrequency(comparable.rawRentFrequency)}, adjusting to ${formatCurrency(comparable.adjustedMonthlyEquivalent)} pcm${sourceDate}.`;
  });
}

function buildKeyPointsLines(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string[] {
  const preview = getResolvedPreview(state, snapshot);
  const proposedPosition = preview?.proposedPositionLabel || 'Position not yet calculated';

  return [
    `- Proposed rent: ${formatCurrency(state.proposal.proposedRentAmount)} ${frequencyLabel(state.tenancy.currentRentFrequency)}`,
    `- Local median: ${formatCurrency(preview?.median)} pcm`,
    `- Position: ${proposedPosition}`,
    `- Evidence strength: ${preview?.evidenceBandLabel || 'Not available'}`,
    `- Comparable count: ${preview?.comparableCount ?? comparables.length} total (${preview?.sourceBackedCount ?? 0} source-backed; ${preview?.freshComparableCount ?? 0} within 90 days)`,
  ];
}

function buildComparableOverviewLines(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string[] {
  const preview = getResolvedPreview(state, snapshot);
  if ((preview?.comparableCount ?? comparables.length) <= 0) {
    return ['No comparable analysis is available yet.'];
  }

  return [
    `- Comparable base: ${buildComparableGrounding(state, comparables, snapshot)}`,
    `- Challenge band: ${preview?.challengeBandLabel || 'Not available'}`,
    `- Evidence band: ${preview?.evidenceBandLabel || 'Not available'}`,
  ];
}

function buildConsistencyLines(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string[] {
  const preview = getResolvedPreview(state, snapshot);
  const firstComparable = comparables[0];
  const grounding = buildComparableGrounding(state, comparables, snapshot);

  return [
    `Keep returning to the same market anchor: the proposal is based on ${grounding}, not on a target percentage increase.`,
    firstComparable
      ? `Use a concrete example if challenged: ${firstComparable.addressSnippet} is one of the comparables supporting the market position recorded in the report.`
      : 'If challenged, refer back to the recorded comparable table and the adjustments already applied.',
    `Describe the proposal as ${preview?.proposedPositionLabel?.toLowerCase() || 'market-positioned'} and keep the explanation tied to the Form 4A, proof of service, and justification report rather than speculation about what the tribunal may do.`,
  ];
}

function buildChallengeScriptLines(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): string[] {
  const preview = getResolvedPreview(state, snapshot);
  const grounding = buildComparableGrounding(state, comparables, snapshot);

  return [
    '1. Anchor to evidence',
    'Say: The proposed rent is based on comparable local properties and the recorded adjustments, not on a percentage increase alone.',
    '2. Position in the range',
    `Say: The figure sits ${getMedianPositionFragment(state, snapshot)} and should be judged against the adjusted comparable range recorded in the report.`,
    '3. Strength of evidence',
    `Say: The proposal is supported by ${preview?.sourceBackedCount ?? 0} source-backed comparables, with ${preview?.freshComparableCount ?? 0} listings inside the 90-day freshness window.`,
    '4. Bundle integrity',
    'Say: The full bundle includes the notice, service record, justification report, Tribunal Argument Summary, and the supporting documents I rely on.',
  ];
}

function buildComparableLines(comparables: Section13Comparable[]): string[] {
  return comparables.flatMap((comparable, index) => {
    const header = `${index + 1}. ${comparable.addressSnippet} | ${formatCurrency(comparable.rawRentValue)} ${compactFrequency(comparable.rawRentFrequency)} | adjusted ${formatCurrency(comparable.adjustedMonthlyEquivalent)} pcm`;
    const details = [
      `Source: ${comparable.source}${comparable.sourceUrl ? ` | ${comparable.sourceUrl}` : ''}`,
      comparable.propertyType ? `Property type: ${comparable.propertyType}` : null,
      comparable.distanceMiles != null ? `Distance: ${comparable.distanceMiles.toFixed(2)} miles` : null,
      comparable.sourceDateValue ? `Source date (${comparable.sourceDateKind}): ${formatDateUk(comparable.sourceDateValue)}` : null,
      comparable.adjustments.length > 0
        ? `Adjustments: ${comparable.adjustments.map((item) => `${item.category} ${item.normalizedMonthlyDelta >= 0 ? '+' : ''}${formatCurrency(item.normalizedMonthlyDelta)} (${item.reason})`).join('; ')}`
        : 'Adjustments: none recorded',
    ].filter(Boolean) as string[];

    return [header, ...details, ''];
  });
}

function buildServiceMethodLabel(state: Section13State): string {
  switch (state.proposal.serviceMethod) {
    case 'hand_delivered':
      return 'Personal delivery';
    case 'post':
      return 'First class post';
    case 'registered_post':
      return 'Registered / signed-for post';
    case 'email':
      return 'Email';
    case 'other':
      return state.proposal.serviceMethodOther || 'Other';
    default:
      return 'Not recorded';
  }
}

async function generateSection13Form4A(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): Promise<Uint8Array> {
  const resolvedState = getSnapshotState(state, snapshot);
  const sourceBytes = await fs.readFile(FORM_4A_PATH);
  const pdfDoc = await PDFDocument.load(sourceBytes);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const form = pdfDoc.getForm();

  const tenantNames = resolvedState.tenancy.tenantNames.filter(Boolean).join('\n');
  const propertyPostcode =
    formatOfficialPostcodeValue(
      resolvedState.tenancy.postcodeNormalized || resolvedState.tenancy.postcodeRaw,
    );
  const landlordPostcode =
    formatOfficialPostcodeValue(
      resolvedState.landlord.landlordPostcodeNormalized || resolvedState.landlord.landlordPostcodeRaw || '',
    );
  const agentPostcode =
    formatOfficialPostcodeValue(
      resolvedState.landlord.agentPostcodeNormalized || resolvedState.landlord.agentPostcodeRaw || '',
    );
  const startDate = resolvedState.tenancy.tenancyStartDate;
  const lastIncreaseDate = resolvedState.tenancy.lastRentIncreaseDate || '';
  const firstIncreaseDate = resolvedState.tenancy.firstIncreaseAfter2003Date || '';
  const proposedStartDate = resolvedState.proposal.proposedStartDate || '';
  const serviceDate = resolvedState.proposal.serviceDate || new Date().toISOString().slice(0, 10);
  const signAsAgent = Boolean(resolvedState.landlord.agentName);
  const signatoryName = signAsAgent
    ? resolvedState.landlord.agentName || resolvedState.landlord.landlordName
    : resolvedState.landlord.landlordName;

  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.tenantNames, tenantNames);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.propertyAddressLine1, resolvedState.tenancy.propertyAddressLine1);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.propertyAddressLine2, resolvedState.tenancy.propertyAddressLine2 || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.propertyTownCity, resolvedState.tenancy.propertyTownCity);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.propertyCounty, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.propertyPostcode, propertyPostcode || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordName, resolvedState.landlord.landlordName);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordAddressLine1, resolvedState.landlord.landlordAddressLine1);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordAddressLine2, resolvedState.landlord.landlordAddressLine2 || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordTownCity, resolvedState.landlord.landlordTownCity);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordCounty, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordPostcode, landlordPostcode);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordPhone, resolvedState.landlord.landlordPhone || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.landlordEmail, resolvedState.landlord.landlordEmail || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentName, resolvedState.landlord.agentName || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentAddressLine1, resolvedState.landlord.agentAddressLine1 || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentAddressLine2, resolvedState.landlord.agentAddressLine2 || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentTownCity, resolvedState.landlord.agentTownCity || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentCounty, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentPostcode, agentPostcode);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentPhone, resolvedState.landlord.agentPhone || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.agentEmail, resolvedState.landlord.agentEmail || '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.currentRentAmount, formatCurrencyFieldValue(resolvedState.tenancy.currentRentAmount));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.currentRentFrequency, toTitleFrequency(resolvedState.tenancy.currentRentFrequency));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.tenancyStartDate, formatCombDateValue(startDate));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.lastIncreaseDate, formatCombDateValue(lastIncreaseDate));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.firstIncreaseDate, formatCombDateValue(firstIncreaseDate));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.proposedRentAmount, formatCurrencyFieldValue(resolvedState.proposal.proposedRentAmount));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.proposedRentFrequency, toTitleFrequency(resolvedState.tenancy.currentRentFrequency));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.proposedStartDate, formatCombDateValue(proposedStartDate));

  FORM_4A_OFFICIAL_FIELD_NAMES.includedChargeRows.forEach((fields, index) => {
    const charge = resolvedState.includedCharges[index];
    const existing = charge?.included ? formatCurrencyFieldValue(charge.currentAmount) : 'nil';
    const proposed = charge?.included ? formatCurrencyFieldValue(charge.proposedAmount) : 'nil';
    setEditableTextFieldValue(form, fields.current, existing);
    setEditableTextFieldValue(form, fields.proposed, proposed);
  });

  setEditableCheckboxValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.checkboxes.signAsLandlord, !signAsAgent);
  setEditableCheckboxValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.checkboxes.signAsAgent, signAsAgent);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.signature, signatoryName);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.printName, signatoryName);
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.signatureDate, formatCombDateValue(serviceDate));
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.jointSignatory1, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.jointSignatory2, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.jointSignatory3, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.continuationText, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.continuationSignature, '');
  setEditableTextFieldValue(form, FORM_4A_OFFICIAL_FIELD_NAMES.text.continuationDate, '');

  form.updateFieldAppearances(font);

  return pdfDoc.save();
}

async function buildCoverLetterPdf(
  state: Section13State,
  snapshot?: Section13OutputSnapshot | null
): Promise<Uint8Array> {
  const resolvedState = getSnapshotState(state, snapshot);
  const preview = getResolvedPreview(resolvedState, snapshot);
  const casePosition = getCasePositionVariants({ state: resolvedState, snapshot });
  return createNarrativePdf(
    'Section 13 Rent Increase Cover Letter',
    [
      {
        variant: 'intro',
        lines: [
          'This cover letter explains the proposed rent increase and points the tenant to the notice and supporting evidence.',
          casePosition.cover,
          `Property: ${buildPropertyAddress(resolvedState)}`,
          `Tenant(s): ${resolvedState.tenancy.tenantNames.join(', ')}`,
        ],
      },
      {
        heading: 'What to do now',
        lines: [
          '1. Serve Form 4A correctly using the method you have recorded in this pack.',
          '2. Keep the proof of service record with the completed notice so you can show when and how the notice was served.',
          '3. Retain the justification report with your comparable evidence in case the tenant challenges the proposed rent.',
        ],
      },
      {
        heading: 'Rent position in brief',
        lines: [
          `Current rent: ${formatCurrency(resolvedState.tenancy.currentRentAmount)} ${frequencyLabel(resolvedState.tenancy.currentRentFrequency)}`,
          `Proposed rent: ${formatCurrency(resolvedState.proposal.proposedRentAmount)} ${frequencyLabel(resolvedState.tenancy.currentRentFrequency)}`,
          `Proposed start date: ${formatDateUk(resolvedState.proposal.proposedStartDate) || 'Not entered'}`,
          buildConclusionSentence(resolvedState, snapshot),
          `Comparable footing: ${buildComparableGrounding(resolvedState, [], snapshot)}.`,
          `Assessment: ${buildBandingSummary(resolvedState, snapshot)}`,
          buildJustificationNarrativeText(resolvedState, snapshot),
          ...(preview?.warnings?.length ? [preview.warnings.join(' ')] : []),
        ],
      },
      {
        heading: 'Keep with the notice',
        lines: [
          `Service method recorded: ${buildServiceMethodLabel(resolvedState)}`,
          `Service date recorded: ${formatDateUk(resolvedState.proposal.serviceDate) || 'Not recorded'}`,
          SECTION13_TRIBUNAL_WARNING,
          SECTION13_DISCLAIMER,
        ],
      },
    ],
    'Landlord Heaven | Section 13 rent increase pack'
  );
}

async function buildJustificationReportPdf(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): Promise<Uint8Array> {
  const resolvedState = getSnapshotState(state, snapshot);
  const preview = getResolvedPreview(resolvedState, snapshot);
  const resolvedComparables = getSnapshotComparables(comparables, snapshot);
  const casePosition = getCasePositionVariants({
    state: resolvedState,
    comparables: resolvedComparables,
    snapshot,
  });
  const manualJustification = resolvedState.adjustments.manualJustification?.trim();
  const lines: SectionBlock[] = [
    {
      variant: 'intro',
      lines: [
        'This report explains why the proposed rent is supported by local comparable evidence.',
        buildConclusionSentence(resolvedState, snapshot),
        casePosition.justification,
        `Property: ${buildPropertyAddress(resolvedState)}`,
      ],
    },
    {
      variant: 'callout',
      heading: 'Key points',
      lines: buildKeyPointsLines(resolvedState, resolvedComparables, snapshot),
    },
    {
      heading: 'Market position',
      lines: [
        `Rules version: ${resolvedState.rulesVersion}`,
        `Adjusted market range: lower quartile ${formatCurrency(preview?.lowerQuartile)} pcm | median ${formatCurrency(preview?.median)} pcm | upper quartile ${formatCurrency(preview?.upperQuartile)} pcm`,
        `Proposed rent: ${formatCurrency(resolvedState.proposal.proposedRentAmount)} ${frequencyLabel(resolvedState.tenancy.currentRentFrequency)} (${formatCurrency(preview?.proposedRentMonthly)} pcm equivalent)`,
        buildMarketPositionSentence(resolvedState, snapshot),
        getDefensibilitySummaryText(resolvedState, snapshot),
        buildEvidenceStrengthSentence(resolvedState, resolvedComparables, snapshot),
        `Challenge band: ${preview?.challengeBandLabel || 'Not available'} - ${SECTION13_CHALLENGE_EXPLAINER}`,
        `Evidence band: ${preview?.evidenceBandLabel || 'Not available'} - ${SECTION13_EVIDENCE_EXPLAINER}`,
      ],
    },
    {
      heading: 'Recorded reasoning',
      lines: [
        buildJustificationNarrativeText(resolvedState, snapshot),
        manualJustification
          ? `Case-specific note: ${manualJustification}`
          : 'No separate manual note was added. The proposal should therefore be explained by reference to the comparable analysis and recorded adjustments only.',
      ],
    },
    {
      variant: 'callout',
      heading: 'Comparable overview',
      lines: buildComparableOverviewLines(resolvedState, resolvedComparables, snapshot),
    },
    {
      heading: 'Comparable picture',
      lines: [
        preview?.previewSummary || 'No comparable summary available.',
        ...buildComparableHighlights(resolvedComparables),
      ],
    },
    {
      heading: 'Comparables and adjustments',
      lines: buildComparableLines(resolvedComparables),
    },
    {
      heading: 'Tribunal note',
      lines: [SECTION13_TRIBUNAL_WARNING, SECTION13_DISCLAIMER],
    },
  ];

  return createNarrativePdf(
    'Rent Increase Justification Report',
    lines,
    'Landlord Heaven | Comparable analysis and justification'
  );
}

async function buildDefenceGuidePdf(state: Section13State): Promise<Uint8Array> {
  const preview = state.preview;
  const casePosition = getCasePositionVariants({ state });
  return createNarrativePdf(
    'Tribunal Defence Guide',
    [
      {
        variant: 'intro',
        lines: [
          'This guide shows how to present the Section 13 file clearly if the tenant refers the notice to the tribunal.',
          casePosition.defensive,
          buildBandSummaryLine(state),
        ],
      },
      {
        heading: 'If the tenant applies',
        lines: [
          'If the tenant refers the notice to the tribunal before the proposed start date, review the application promptly and answer from the same evidence base used in this pack.',
          'Keep the Form 4A notice, proof of service record, justification report, Tribunal Argument Summary, photos, EPC, safety documents, and any negotiation correspondence together in one hearing file.',
        ],
      },
      {
        heading: 'What to file and bring',
        lines: [
          'Bring the merged tribunal bundle, printed copies of supporting evidence, and a short chronology covering the tenancy start date, any earlier increase, and the proposed effective date.',
          `Use the same band wording throughout: ${preview?.challengeBandLabel || 'Band unavailable'} and ${preview?.evidenceBandLabel || 'Band unavailable'}.`,
        ],
      },
      {
        heading: 'How to explain the evidence',
        lines: [
          'Explain why the chosen comparables are relevant, how each adjustment affects the monthly equivalent, and why any user override was applied.',
          'If a point is weak or missing, acknowledge it briefly and return to the strongest nearby comparables rather than overstating the file.',
        ],
      },
      {
        heading: 'Keep your position consistent',
        lines: [
          ...buildConsistencyLines(state, [], null),
          'Be ready to explain property condition, tenancy-period alignment, and how the earliest valid start date was calculated under the post-1 May 2026 rules.',
        ],
      },
    ],
    'Section 13 Defensive Pack | Tribunal defence guide'
  );
}

async function buildLandlordResponseTemplatePdf(state: Section13State): Promise<Uint8Array> {
  const preview = state.preview;
  const casePosition = getCasePositionVariants({ state });
  return createNarrativePdf(
    'Landlord Response Template',
    [
      {
        variant: 'intro',
        lines: [
          'Use this template when responding to a tenant application for a market rent determination.',
          casePosition.justification,
        ],
      },
      {
        heading: 'Suggested response',
        lines: [
          'I confirm that the notice under section 13(2) of the Housing Act 1988 was served on the tenant and that the proposed rent is supported by current open-market comparables for similar homes in the same area.',
          `The comparable analysis shows an adjusted median market rent of ${formatCurrency(preview?.median)} per month, with the proposed rent sitting ${getMedianPositionFragment(state)}.`,
          'The landlord therefore asks the tribunal to determine that the proposed rent is supported by the market evidence, or alternatively to set the market rent at the closest figure supported by the evidence bundle.',
        ],
      },
      {
        heading: 'Attach with response',
        lines: [
          'Attach the completed Form 4A, proof of service record, justification report, Tribunal Argument Summary, relevant evidence exhibits, and any correspondence showing attempts to resolve the issue before a hearing.',
        ],
      },
    ],
    'Section 13 Defensive Pack | Landlord response template'
  );
}

async function buildLegalBriefingPdf(state: Section13State): Promise<Uint8Array> {
  const casePosition = getCasePositionVariants({ state });
  return createNarrativePdf(
    'Tribunal Legal Briefing',
    [
      {
        variant: 'intro',
        lines: [
          'This briefing pulls together the main statutory and practical points that sit behind the landlord evidence file.',
          casePosition.justification,
        ],
      },
      {
        heading: 'Statutory framework',
        lines: [
          'This pack is prepared on the basis of Housing Act 1988 section 13(2) and section 13(4), as amended for assured tenancies from 1 May 2026.',
          'The new rent must be proposed on Form 4A, served with at least two months notice, aligned to the tenancy period, and timed so that the 52-week / 53-week anti-drift rule is satisfied.',
        ],
      },
      {
        heading: 'What the tribunal considers',
        lines: [
          'The tribunal considers the market rent for the property on the open market, assuming the same terms, letting circumstances, and tenant obligations unless the evidence shows a meaningful difference.',
          'Comparable selection, adjustment discipline, and evidence freshness are therefore central. Unsupported or stale comparables weaken the landlord case even where the notice itself is valid.',
        ],
      },
      {
        heading: 'Practical hearing points',
        lines: [
          `Current banding: ${state.preview?.challengeBandLabel || 'Not calculated'} | ${state.preview?.evidenceBandLabel || 'Not calculated'}.`,
          'Stay consistent with the report wording. Do not overstate the data. If the evidence is mixed, acknowledge that plainly and explain why the proposed figure still sits within a reasonable market range.',
        ],
      },
    ],
    'Section 13 Defensive Pack | Legal briefing'
  );
}

async function buildTribunalArgumentSummaryPdf(
  state: Section13State,
  comparables: Section13Comparable[],
  snapshot?: Section13OutputSnapshot | null
): Promise<Uint8Array> {
  const resolvedState = getSnapshotState(state, snapshot);
  const preview = getResolvedPreview(resolvedState, snapshot);
  const resolvedComparables = getSnapshotComparables(comparables, snapshot);
  const casePosition = getCasePositionVariants({
    state: resolvedState,
    comparables: resolvedComparables,
    snapshot,
  });

  return createNarrativePdf(
    'Tribunal Argument Summary',
    [
      {
        variant: 'intro',
        lines: [
          'This is the landlord’s concise argument brief for the hearing file.',
          casePosition.argument,
          `Adjusted median market rent: ${formatCurrency(preview?.median)} pcm`,
        ],
      },
      {
        heading: 'Argument in brief',
        lines: [
          'The proposal should be judged by reference to nearby open-market comparables, not by the size of the increase from the previous rent alone.',
          casePosition.defensive,
          buildJustificationNarrativeText(resolvedState, snapshot),
        ],
      },
      {
        heading: 'Strength of the evidence',
        lines: [
          buildEvidenceStrengthSentence(resolvedState, resolvedComparables, snapshot),
          ...buildComparableHighlights(resolvedComparables, 2),
        ],
      },
      {
        heading: 'If challenged, say this',
        lines: buildChallengeScriptLines(resolvedState, resolvedComparables, snapshot),
      },
      {
        heading: 'Important limit',
        lines: [
          'This summary is a concise argument brief drawn from the saved case facts and comparable analysis. It supports presentation of the case, but it does not guarantee a tribunal outcome.',
        ],
      },
    ],
    'Section 13 Defensive Pack | Tribunal argument summary'
  );
}

async function buildEvidenceChecklistPdf(state: Section13State, evidenceUploads: Section13EvidenceUpload[]): Promise<Uint8Array> {
  const uploaded = evidenceUploads.length > 0
    ? evidenceUploads.map((item) => `${item.exhibitLabel || 'Exhibit'} - ${item.title || item.fileName}`)
    : [SECTION13_NO_EXTERNAL_EVIDENCE_TEXT];

  return createNarrativePdf(
    'Evidence Checklist',
    [
      {
        lines: [
          '[ ] Copy of tenancy agreement',
          '[ ] Completed Form 4A',
          '[ ] Proof of service record',
          '[ ] Rent increase justification report',
          '[ ] Comparable evidence printout / saved links',
          '[ ] EPC certificate',
          '[ ] Gas safety / electrical certificates (if applicable)',
          '[ ] Local Housing Allowance screenshot',
        ],
      },
      {
        heading: 'Uploaded evidence currently attached',
        lines: uploaded,
      },
      {
        heading: 'Reminder',
        lines: [
          `Service method recorded: ${buildServiceMethodLabel(state)}`,
          SECTION13_TRIBUNAL_WARNING,
        ],
      },
    ],
    'Section 13 Defensive Pack | Evidence checklist'
  );
}

async function buildNegotiationEmailTemplatePdf(state: Section13State): Promise<Uint8Array> {
  return createNarrativePdf(
    'Negotiation Email Template',
    [
      {
        variant: 'intro',
        lines: [
          `Subject: Proposed rent review for ${buildPropertyAddress(state)}`,
          '',
          `Dear ${state.tenancy.tenantNames[0] || 'Tenant'},`,
          '',
          `I am writing regarding the proposed new rent of ${formatCurrency(state.proposal.proposedRentAmount)} ${frequencyLabel(state.tenancy.currentRentFrequency)} from ${formatDateUk(state.proposal.proposedStartDate)}.`,
          'I have reviewed comparable homes in the local area and prepared a summary of the evidence supporting the proposal. If you would like to discuss the figures or timing before any tribunal application is made, please reply and I will consider any evidence you wish to share.',
          '',
          'Kind regards,',
          state.landlord.agentName || state.landlord.landlordName,
        ],
      },
    ],
    'Section 13 Defensive Pack | Negotiation email template'
  );
}

async function createBundleCoverPdf(state: Section13State, productType: Section13ProductSku): Promise<Uint8Array> {
  return createNarrativePdf(
    'Tribunal Bundle Cover Sheet',
    [
      {
        variant: 'intro',
        lines: [
          `Pack: ${productType === 'section13_defensive' ? 'Section 13 Defensive Pack' : 'Section 13 Standard Pack'}`,
          `Property: ${buildPropertyAddress(state)}`,
          `Tenant(s): ${state.tenancy.tenantNames.join(', ')}`,
          `Prepared on: ${formatDateUk(new Date().toISOString().slice(0, 10))}`,
          `Rules version: ${state.rulesVersion}`,
        ],
      },
      {
        heading: 'Purpose',
        lines: [
          'This bundle brings together the Form 4A notice, market-rent justification, Tribunal Argument Summary, service record, and any uploaded supporting evidence for a tribunal-ready response pack.',
        ],
      },
    ],
    'Section 13 Defensive Pack | Bundle cover'
  );
}

async function createBundleIndexPdf(artifacts: BundleArtifact[]): Promise<Uint8Array> {
  const lines = artifacts
    .filter((item) => item.includeInMerged)
    .map((item) => `${item.exhibitLabel ? `${item.exhibitLabel}: ` : ''}${item.title}${item.pageCount ? ` (${item.pageCount} page${item.pageCount === 1 ? '' : 's'})` : ''}`);

  return createNarrativePdf(
    'Tribunal Bundle Index',
    [{ lines }],
    'Section 13 Defensive Pack | Bundle index'
  );
}

async function mergePdfArtifacts(
  coverBytes: Uint8Array,
  indexBytes: Uint8Array,
  generatedDocs: Section13BundleSourceDocument[],
  evidenceFiles: Section13EvidenceFile[]
): Promise<{
  bundleBytes: Uint8Array;
  bundleArtifacts: BundleArtifact[];
  warnings: string[];
}> {
  const warnings: string[] = [];
  const bundlePdf = await PDFDocument.create();
  const artifacts: BundleArtifact[] = [];

  const addPdf = async (
    title: string,
    bytes: Uint8Array,
    logicalSection: Section13BundleAsset['logicalSection'],
    assetType: Section13BundleAsset['assetType'],
    sourceKind: Section13BundleAsset['sourceKind'],
    includeInMerged: boolean,
    extra?: Partial<BundleArtifact>
  ) => {
    const source = await PDFDocument.load(bytes);
    const copiedPages = await bundlePdf.copyPages(source, source.getPageIndices());
    copiedPages.forEach((page) => bundlePdf.addPage(page));
    artifacts.push({
      title,
      logicalSection,
      assetType,
      sourceKind,
      includeInMerged,
      pageCount: source.getPageCount(),
      status: 'generated',
      ...extra,
    });
  };

  await addPdf('Bundle cover sheet', coverBytes, 'cover', 'report', 'supporting_input', true);
  await addPdf('Bundle index', indexBytes, 'index', 'report', 'supporting_input', true);

  for (const doc of generatedDocs) {
    const logicalSection =
      doc.document_type === 'section13_form_4a' ? 'core_notice' : 'supporting_report';
    const assetType =
      doc.document_type === 'section13_form_4a' ? 'form' : 'report';
    await addPdf(doc.title, doc.pdf, logicalSection, assetType, 'generated_document', true, {
      documentType: doc.document_type,
      sourceDocumentId: doc.sourceDocumentId || null,
    });
  }

  for (const evidence of evidenceFiles) {
    try {
      if (evidence.contentType === 'application/pdf') {
        await addPdf(
          evidence.upload.title || evidence.upload.fileName,
          evidence.bytes,
          'uploaded_evidence',
          'evidence',
          'uploaded_evidence',
          true,
          {
            sourceUploadId: evidence.upload.id || null,
            exhibitLabel: evidence.upload.exhibitLabel || null,
          }
        );
        continue;
      }

      if (evidence.contentType === 'image/png' || evidence.contentType === 'image/jpeg') {
        const imageDoc = await PDFDocument.create();
        const page = imageDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        const image: PDFImage =
          evidence.contentType === 'image/png'
            ? await imageDoc.embedPng(evidence.bytes)
            : await imageDoc.embedJpg(evidence.bytes);
        const bold = await imageDoc.embedFont(StandardFonts.HelveticaBold);
        const scale = Math.min((PAGE_WIDTH - 80) / image.width, (PAGE_HEIGHT - 120) / image.height);
        const width = image.width * scale;
        const height = image.height * scale;
        page.drawText(safeText(evidence.upload.title || evidence.upload.fileName), {
          x: 40,
          y: PAGE_HEIGHT - 40,
          size: 12,
          font: bold,
          color: rgb(0.16, 0.16, 0.16),
        });
        page.drawImage(image, {
          x: (PAGE_WIDTH - width) / 2,
          y: (PAGE_HEIGHT - height) / 2 - 20,
          width,
          height,
        });
        const imageBytes = await imageDoc.save();
        await addPdf(
          evidence.upload.title || evidence.upload.fileName,
          imageBytes,
          'uploaded_evidence',
          'evidence',
          'uploaded_evidence',
          true,
          {
            sourceUploadId: evidence.upload.id || null,
            exhibitLabel: evidence.upload.exhibitLabel || null,
          }
        );
        continue;
      }

      warnings.push(`Skipped unsupported evidence file type for ${evidence.upload.fileName}.`);
      artifacts.push({
        title: evidence.upload.title || evidence.upload.fileName,
        logicalSection: 'uploaded_evidence',
        assetType: 'evidence',
        sourceKind: 'uploaded_evidence',
        includeInMerged: false,
        status: 'warning',
        generationError: 'Unsupported evidence MIME type',
        sourceUploadId: evidence.upload.id || null,
      });
    } catch (error: any) {
      warnings.push(`Could not include uploaded evidence "${evidence.upload.fileName}" in the merged bundle.`);
      artifacts.push({
        title: evidence.upload.title || evidence.upload.fileName,
        logicalSection: 'uploaded_evidence',
        assetType: 'evidence',
        sourceKind: 'uploaded_evidence',
        includeInMerged: false,
        status: 'warning',
        generationError: error?.message || 'Evidence merge failed',
        sourceUploadId: evidence.upload.id || null,
      });
    }
  }

  return {
    bundleBytes: await bundlePdf.save(),
    bundleArtifacts: artifacts,
    warnings,
  };
}

async function createZipBundle(
  docs: Array<Pick<Section13PersistableDocument, 'file_name' | 'pdf'>>,
  evidenceFiles: Section13EvidenceFile[]
): Promise<Uint8Array> {
  const zip = new JSZip();

  for (const doc of docs) {
    zip.file(doc.file_name, doc.pdf);
  }

  for (const evidence of evidenceFiles) {
    zip.file(`uploaded-evidence/${evidence.upload.fileName}`, Buffer.from(evidence.bytes));
  }

  return zip.generateAsync({ type: 'uint8array' });
}

export async function generateSection13PreviewableDocument(params: {
  caseId: string;
  documentType: Section13PreviewableDocumentType;
  productType: Section13ProductSku;
  state: Section13State;
  comparables: Section13Comparable[];
  evidenceFiles?: Section13EvidenceFile[];
  snapshot?: Section13OutputSnapshot | null;
}): Promise<Section13PersistableDocument> {
  const {
    caseId,
    documentType,
    productType,
    state,
    comparables,
    evidenceFiles = [],
    snapshot,
  } = params;
  const resolvedState = getSnapshotState(state, snapshot);
  const resolvedComparables = getSnapshotComparables(comparables, snapshot);

  if (
    productType !== 'section13_defensive' &&
    !SECTION13_CORE_DOCUMENT_TYPES.includes(
      documentType as (typeof SECTION13_CORE_DOCUMENT_TYPES)[number]
    )
  ) {
    throw new Error(`Document type ${documentType} requires the Section 13 Defensive Pack`);
  }

  switch (documentType) {
    case 'section13_form_4a': {
      const pdfBytes = await generateSection13Form4A(resolvedState, snapshot);
      return {
        title: 'Form 4A rent increase notice',
        description: 'Official Form 4A completed from your Section 13 wizard answers.',
        category: 'notice',
        document_type: 'section13_form_4a',
        file_name: `section13-form-4a-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_justification_report': {
      const pdfBytes = await buildJustificationReportPdf(
        resolvedState,
        resolvedComparables,
        snapshot
      );
      return {
        title: 'Rent increase justification report',
        description: 'Comparable rent evidence and adjusted market analysis.',
        category: 'evidence',
        document_type: 'section13_justification_report',
        file_name: `section13-justification-report-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_proof_of_service_record': {
      const pdfBytes = await generateProofOfServicePDF({
        landlord_name: resolvedState.landlord.landlordName,
        tenant_name: resolvedState.tenancy.tenantNames.join(', '),
        property_address: buildPropertyAddress(resolvedState),
        document_served: "Form 4A - Landlord's notice proposing a new rent",
        served_date: resolvedState.proposal.serviceDate || undefined,
        expiry_date: resolvedState.proposal.proposedStartDate || undefined,
        service_address: buildPropertyAddress(resolvedState),
        service_method:
          resolvedState.proposal.serviceMethod === 'hand_delivered'
            ? 'hand_delivery'
            : resolvedState.proposal.serviceMethod === 'post'
              ? 'first_class_post'
              : resolvedState.proposal.serviceMethod === 'registered_post'
                ? 'recorded_delivery'
                : resolvedState.proposal.serviceMethod === 'email'
                  ? 'email'
                  : undefined,
        footer_branding: SECTION13_PROOF_OF_SERVICE_BRAND,
      });
      return {
        title: 'Proof of service record',
        description: 'Service method record for the Section 13 notice.',
        category: 'evidence',
        document_type: 'section13_proof_of_service_record',
        file_name: `section13-proof-of-service-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_cover_letter': {
      const pdfBytes = await buildCoverLetterPdf(resolvedState, snapshot);
      return {
        title: 'Rent increase cover letter',
        description: 'Plain-English cover letter to accompany the notice.',
        category: 'guidance',
        document_type: 'section13_cover_letter',
        file_name: `section13-cover-letter-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_tribunal_argument_summary': {
      const pdfBytes = await buildTribunalArgumentSummaryPdf(
        resolvedState,
        resolvedComparables,
        snapshot
      );
      return {
        title: 'Tribunal Argument Summary',
        description:
          'One-page case-specific summary of the landlord position and consistent argument points.',
        category: 'guidance',
        document_type: 'section13_tribunal_argument_summary',
        file_name: `section13-tribunal-argument-summary-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_tribunal_defence_guide': {
      const pdfBytes = await buildDefenceGuidePdf(resolvedState);
      return {
        title: 'Tribunal defence guide',
        description: 'Step-by-step preparation guide for a challenged rent increase.',
        category: 'guidance',
        document_type: 'section13_tribunal_defence_guide',
        file_name: `section13-tribunal-defence-guide-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_landlord_response_template': {
      const pdfBytes = await buildLandlordResponseTemplatePdf(resolvedState);
      return {
        title: 'Landlord response template',
        description: 'Template response aligned to the current rent determination process.',
        category: 'court_form',
        document_type: 'section13_landlord_response_template',
        file_name: `section13-landlord-response-template-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
    case 'section13_legal_briefing': {
      const pdfBytes = await buildLegalBriefingPdf(resolvedState);
      return {
        title: 'Tribunal legal briefing',
        description: 'Short legal and practical hearing briefing.',
        category: 'guidance',
        document_type: 'section13_legal_briefing',
        file_name: `section13-legal-briefing-${caseId}.pdf`,
        pdf: Buffer.from(pdfBytes),
      };
    }
  }
}

export async function generateSection13CoreDocuments(params: {
  caseId: string;
  productType: Section13ProductSku;
  state: Section13State;
  comparables: Section13Comparable[];
  evidenceFiles?: Section13EvidenceFile[];
  snapshot?: Section13OutputSnapshot | null;
}): Promise<Section13PersistableDocument[]> {
  const { caseId, productType, state, comparables, evidenceFiles = [], snapshot } = params;
  const documentTypes =
    productType === 'section13_defensive'
      ? SECTION13_DEFENSIVE_DOCUMENT_TYPES
      : SECTION13_CORE_DOCUMENT_TYPES;
  const documents = await Promise.all(
    documentTypes.map((documentType) =>
      generateSection13PreviewableDocument({
        caseId,
        documentType,
        productType,
        state,
        comparables,
        evidenceFiles,
        snapshot,
      })
    )
  );

  return [...documents].sort((left, right) => {
    const leftIndex = SECTION13_BUNDLE_SOURCE_DOCUMENT_TYPES.indexOf(left.document_type as any);
    const rightIndex = SECTION13_BUNDLE_SOURCE_DOCUMENT_TYPES.indexOf(right.document_type as any);
    return (leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex) - (rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex);
  });
}

async function buildSection13BundleDocuments(params: {
  caseId: string;
  productType: Extract<Section13ProductSku, 'section13_defensive'>;
  state: Section13State;
  evidenceFiles?: Section13EvidenceFile[];
  sourceDocuments: Section13BundleSourceDocument[];
  snapshot?: Section13OutputSnapshot | null;
}): Promise<Section13GeneratedBundle> {
  const { caseId, productType, state, evidenceFiles = [], sourceDocuments, snapshot } = params;
  const resolvedState = getSnapshotState(state, snapshot);
  const bundleWarnings: string[] = [];
  const sortedSourceDocuments = [...sourceDocuments].sort((left, right) => {
    const leftIndex = SECTION13_BUNDLE_SOURCE_DOCUMENT_TYPES.indexOf(left.document_type as any);
    const rightIndex = SECTION13_BUNDLE_SOURCE_DOCUMENT_TYPES.indexOf(right.document_type as any);
    return (leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex) - (rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex);
  });

  const coverPdf = await createBundleCoverPdf(resolvedState, productType);
  const docArtifacts = await Promise.all(
    sortedSourceDocuments.map(async (doc): Promise<BundleArtifact> => ({
      title: doc.title,
      logicalSection:
        doc.document_type === 'section13_form_4a'
          ? ('core_notice' as const)
          : ('supporting_report' as const),
      assetType:
        doc.document_type === 'section13_form_4a'
          ? ('form' as const)
          : ('report' as const),
      sourceKind: 'generated_document' as const,
      includeInMerged: true,
      status: 'generated' as const,
      pageCount: await pageCount(doc.pdf),
      documentType: doc.document_type,
      sourceDocumentId: doc.sourceDocumentId || null,
      exhibitLabel: null,
    }))
  );

  const coverArtifact: BundleArtifact = {
    title: 'Bundle cover sheet',
    logicalSection: 'cover',
    assetType: 'report',
    sourceKind: 'supporting_input',
    includeInMerged: true,
    status: 'generated',
    pageCount: await pageCount(coverPdf),
  };

  const exhibitArtifacts = [
    ...docArtifacts,
    ...evidenceFiles.map((item) => ({
      title: item.upload.title || item.upload.fileName,
      logicalSection: 'uploaded_evidence' as const,
      assetType: 'evidence' as const,
      sourceKind: 'uploaded_evidence' as const,
      includeInMerged: true,
      status: item.upload.uploadStatus === 'failed' ? ('warning' as const) : ('pending' as const),
      sourceUploadId: item.upload.id || null,
      exhibitLabel: item.upload.exhibitLabel || null,
    })),
  ].map((item, index) => ({
    ...item,
    exhibitLabel: item.exhibitLabel || `Exhibit ${String.fromCharCode(65 + index)}`,
  }));

  const indexPdf = await createBundleIndexPdf([coverArtifact, ...exhibitArtifacts]);
  const { bundleBytes, bundleArtifacts, warnings } = await mergePdfArtifacts(
    coverPdf,
    indexPdf,
    sortedSourceDocuments,
    evidenceFiles
  );

  bundleWarnings.push(...warnings);

  const bundlePdfDocument: Section13PersistableDocument = {
    title: 'Merged tribunal bundle PDF',
    description: 'Indexed hearing bundle with exhibits and supporting documents.',
    category: 'evidence',
    document_type: 'section13_tribunal_bundle',
    file_name: `section13-tribunal-bundle-${caseId}.pdf`,
    pdf: Buffer.from(bundleBytes),
  };

  const zipBytes = await createZipBundle([...sortedSourceDocuments, bundlePdfDocument], evidenceFiles);
  const zipDocument: Section13PersistableDocument = {
    title: 'Tribunal bundle ZIP',
    description: 'ZIP export containing the merged bundle and all supporting files.',
    category: 'evidence',
    document_type: 'section13_tribunal_bundle_zip',
    file_name: `section13-tribunal-bundle-${caseId}.zip`,
    pdf: Buffer.from(zipBytes),
    contentType: 'application/zip',
  };

  const bundleSeeds: BundleArtifact[] = [
    coverArtifact,
    {
      title: 'Bundle index',
      logicalSection: 'index',
      assetType: 'report',
      sourceKind: 'supporting_input',
      includeInMerged: true,
      status: 'generated',
      pageCount: await pageCount(indexPdf),
    },
    ...bundleArtifacts
      .filter((item) => item.logicalSection !== 'cover' && item.logicalSection !== 'index')
      .map((item) => ({
        ...item,
        exhibitLabel: item.exhibitLabel || null,
      })),
  ];

  return {
    documents: [bundlePdfDocument, zipDocument],
    bundleAssets: bundleSeeds.map((item, index) => ({
      rulesVersion: resolvedState.rulesVersion,
      logicalSection: item.logicalSection,
      assetType: item.assetType,
      title: item.title,
      sourceKind: item.sourceKind,
      exhibitLabel: item.exhibitLabel || null,
      orderIndex: index,
      includeInMerged: item.includeInMerged,
      status: item.status,
      pageCount: item.pageCount ?? null,
      generationError: item.generationError ?? null,
      sourceDocumentId: item.sourceDocumentId || null,
      sourceUploadId: item.sourceUploadId || null,
      metadata: {
        document_type: item.documentType || null,
        ...(item.metadata || {}),
      },
    })),
    workflowStatus: bundleWarnings.length > 0 ? 'bundle_partial_warning' : 'bundle_ready',
    bundleWarnings,
  };
}

export async function generateSection13TribunalBundle(params: {
  caseId: string;
  state: Section13State;
  evidenceFiles?: Section13EvidenceFile[];
  sourceDocuments: Section13BundleSourceDocument[];
  snapshot?: Section13OutputSnapshot | null;
}): Promise<Section13GeneratedBundle> {
  return buildSection13BundleDocuments({
    ...params,
    productType: 'section13_defensive',
  });
}

export async function generateSection13Pack(params: {
  caseId: string;
  productType: Section13ProductSku;
  state: Section13State;
  comparables: Section13Comparable[];
  evidenceFiles?: Section13EvidenceFile[];
  snapshot?: Section13OutputSnapshot | null;
}): Promise<Section13GeneratedPack> {
  const { caseId, productType, state, comparables, evidenceFiles = [], snapshot } = params;
  const resolvedState = getSnapshotState(state, snapshot);
  const documents = await generateSection13CoreDocuments({
    caseId,
    productType,
    state: resolvedState,
    comparables,
    evidenceFiles,
    snapshot,
  });
  const bundleWarnings: string[] = [];
  const bundleAssets: Section13BundleAsset[] = [];
  let workflowStatus: Section13WorkflowStatus = 'fulfilled';

  if (productType === 'section13_defensive') {
    workflowStatus = 'fulfilled';
  }

  if (resolvedState.preview?.warnings?.length) {
    bundleWarnings.push(...resolvedState.preview.warnings);
  }

  return {
    documents,
    bundleAssets,
    workflowStatus,
    bundleWarnings,
  };
}
