import type {
  ClaimEvidenceCategory,
  ClaimLineItemCategory,
  ClaimQuestionConfig,
  ClaimStepConfig,
  ClaimTypeConfig,
  ClaimTypeId,
} from './types';
import { PRODUCTS } from '@/lib/pricing/products';

export const CLAIM_PACK_PRICE = PRODUCTS.money_claim.price;
export const CLAIM_PACK_DISPLAY_PRICE = PRODUCTS.money_claim.displayPrice;

const claimTypeStep = (label: string, id: ClaimTypeId): ClaimStepConfig => ({
  stepId: 'claim_type',
  title: 'Claim type',
  aiIntro: 'I will start by locking the claim route, then keep the questions focused.',
  questions: [
    {
      id: 'claim_category',
      questionText: `You are preparing a ${label}.`,
      typingText: `I have set this as a ${label}.`,
      helperText: 'This decides the questions, evidence checklist, document mapping, and checkout route.',
      fieldPath: 'claim_category',
      answerType: 'single_choice',
      required: true,
      options: [{ label, value: id }],
      mapsToDocument: true,
    },
    {
      id: 'claim_flow_mode',
      questionText: 'Which document flow should this claim use?',
      typingText: 'I am matching the claim to the safest document flow.',
      helperText: 'Landlord debt claims reuse the existing landlord money-claim pack. Other claims use the generic small-claim pack model.',
      fieldPath: 'claim_flow_mode',
      answerType: 'single_choice',
      required: true,
      options: [
        { label: 'Landlord money claim', value: 'landlord_money_claim' },
        { label: 'Generic small claim', value: 'generic_small_claim' },
      ],
      mapsToDocument: true,
    },
    {
      id: 'generic_claim_category',
      questionText: 'Which claim category should appear in the document model?',
      typingText: 'I am storing the claim category for the document mapping.',
      helperText: 'This keeps generic claim documents category-specific without using the wrong template family.',
      fieldPath: 'generic_claim.category',
      answerType: 'single_choice',
      required: true,
      options: [{ label, value: id }],
      mapsToDocument: true,
    },
  ],
});

const genericAboutQuestions = (contextQuestion: ClaimQuestionConfig): ClaimQuestionConfig[] => [
  {
    id: 'claimant_name',
    questionText: 'Who is making the claim?',
    typingText: 'Let us get the claimant name exactly as it should appear on the claim.',
    helperText: 'Use the full legal name of the person or business bringing the claim.',
    fieldPath: 'claimant.name',
    answerType: 'text',
    required: true,
    mapsToDocument: true,
    validation: { minLength: 2, requiredMessage: 'Enter the claimant name.' },
  },
  {
    id: 'claimant_address',
    questionText: 'What address should the court use for the claimant?',
    typingText: 'Now I need the claimant service address.',
    helperText: 'Use the address where court papers and replies can safely be received.',
    fieldPath: 'claimant.address',
    answerType: 'address',
    required: true,
    mapsToDocument: true,
  },
  {
    id: 'defendant_name',
    questionText: 'Who owes the money or refund?',
    typingText: 'Next I need the defendant name.',
    helperText: 'Use the person or business name you would name in the claim.',
    fieldPath: 'defendant.name',
    answerType: 'text',
    required: true,
    mapsToDocument: true,
  },
  {
    id: 'defendant_address',
    questionText: 'What is the defendant address?',
    typingText: 'I will capture the defendant address for the claim form.',
    helperText: 'Use the best address you have for service or correspondence.',
    fieldPath: 'defendant.address',
    answerType: 'address',
    required: true,
    mapsToDocument: true,
  },
  {
    id: 'claim_value_estimate',
    questionText: 'Roughly how much is the claim worth?',
    typingText: 'I need an estimated claim value so the file can be checked properly.',
    helperText: 'Enter the main amount before court fees and interest.',
    fieldPath: 'generic_claim.value_estimate',
    answerType: 'currency',
    required: true,
    mapsToDocument: true,
    validation: { minAmount: 1, requiredMessage: 'Enter an estimated claim value.' },
  },
  {
    id: 'claim_summary',
    questionText: 'In one short paragraph, what happened?',
    typingText: 'Give me the plain-English story before we build the court wording.',
    helperText: 'Keep it factual: what was agreed, what went wrong, and what money you want back.',
    fieldPath: 'generic_claim.summary',
    answerType: 'textarea',
    required: true,
    mapsToDocument: true,
    validation: { minLength: 30, requiredMessage: 'Enter a short claim summary.' },
  },
  contextQuestion,
];

const genericSteps = (
  label: string,
  id: ClaimTypeId,
  contextQuestion: ClaimQuestionConfig,
  detailQuestions: ClaimQuestionConfig[],
  evidenceCategories: ClaimEvidenceCategory[]
): ClaimStepConfig[] => [
  claimTypeStep(label, id),
  {
    stepId: 'about',
    title: 'About the claim',
    aiIntro: 'I am collecting the parties, value, and short story first.',
    questions: genericAboutQuestions(contextQuestion),
  },
  {
    stepId: 'details',
    title: 'Details',
    aiIntro: 'Now I will pin down the agreement, dates, breakdown, and what went wrong.',
    questions: [
      ...detailQuestions,
      {
        id: 'line_items',
        questionText: 'What amounts make up the claim?',
        typingText: 'Break the claim into clear line items so the total is easy to follow.',
        helperText: 'Add each item separately, for example main debt, refund, repair cost, delivery, or other loss.',
        fieldPath: 'generic_claim.line_items',
        answerType: 'line_items',
        required: true,
        mapsToDocument: true,
      },
      {
        id: 'pre_action',
        questionText: 'Have you asked for payment or a refund before issuing a claim?',
        typingText: 'The pre-action position matters before court.',
        helperText: 'Say whether a letter, email, or clear demand has already been sent.',
        fieldPath: 'generic_claim.pre_action',
        answerType: 'textarea',
        required: true,
        mapsToDocument: true,
        validation: { minLength: 20 },
      },
      {
        id: 'interest',
        questionText: 'Do you want to consider claiming interest?',
        typingText: 'I will record whether statutory or contractual interest needs review.',
        helperText: 'Choose yes if you want the pack to flag interest for the final check step.',
        fieldPath: 'generic_claim.interest',
        answerType: 'yes_no',
        required: true,
        mapsToDocument: true,
      },
    ],
  },
  {
    stepId: 'evidence',
    title: 'Evidence',
    aiIntro: 'I will now ask for the records that prove the claim and the amount.',
    questions: [
      {
        id: 'evidence_items',
        questionText: 'Which evidence do you have?',
        typingText: 'Select the evidence that supports this claim.',
        helperText: `Tick from the ${evidenceCategories.length} configured evidence prompts you have or will obtain, then describe what each selected item proves. You will attach the actual files yourself when filing.`,
        fieldPath: 'generic_claim.evidence_items',
        answerType: 'evidence_checklist',
        required: true,
        mapsToDocument: true,
      },
    ],
  },
  {
    stepId: 'check',
    title: 'Check',
    aiIntro: 'I will check required fields, blockers, pre-action status, fees, and document readiness.',
    questions: [
      {
        id: 'check_confirmation',
        questionText: 'Are the names, address, amount, dates, and evidence ready to check?',
        typingText: 'Before checkout, I need one final readiness confirmation.',
        helperText: 'The check step will highlight missing fields and suitability blockers before payment.',
        fieldPath: 'generic_claim.readiness_confirmed',
        answerType: 'yes_no',
        required: true,
        mapsToDocument: false,
      },
    ],
  },
  {
    stepId: 'results',
    title: 'Results',
    aiIntro: 'Your pack preview and checkout route are ready.',
    questions: [
      {
        id: 'results_next_action',
        questionText: 'Ready to prepare the claim pack?',
        typingText: 'The result step will show the pack outputs and the next action.',
        helperText: 'You can review the pack outputs before moving to checkout.',
        fieldPath: 'generic_claim.results_next_action',
        answerType: 'single_choice',
        required: false,
        options: [{ label: 'Prepare my claim pack', value: 'prepare_pack' }],
        mapsToDocument: false,
      },
    ],
  },
];

const landlordEvidence: ClaimEvidenceCategory[] = [
  { id: 'tenancy_agreement', label: 'Tenancy agreement', helperText: 'The agreement proving rent, parties, and core terms.' },
  { id: 'rent_schedule', label: 'Rent arrears schedule', helperText: 'A dated schedule showing each missed payment.' },
  { id: 'deposit_statement', label: 'Deposit or deduction statement', helperText: 'Any deposit shortfall or deduction position.' },
  { id: 'damage_photos', label: 'Damage photos and invoices', helperText: 'Photos, contractor estimates, invoices, or receipts.' },
  { id: 'chaser_correspondence', label: 'Chaser letters and messages', helperText: 'Records showing you asked for payment before claim.' },
];

const standardPackOutputs = [
  '01-letter-before-claim.pdf',
  '02-particulars-of-claim.pdf',
  '03-schedule-of-loss.pdf',
  '04-evidence-index.pdf',
  '05-filing-guide.pdf',
  '06-service-guide.pdf',
  '07-hearing-preparation.pdf',
  '08-enforcement-guide.pdf',
];

const genericRequiredFields = [
  'claimant.name',
  'claimant.address',
  'defendant.name',
  'defendant.address',
  'generic_claim.category',
  'generic_claim.summary',
  'generic_claim.key_dates',
  'generic_claim.line_items',
  'generic_claim.evidence_items',
  'generic_claim.pre_action',
  'generic_claim.interest',
];

const lineItems = (...items: ClaimLineItemCategory[]): ClaimLineItemCategory[] => items;
const evidence = (...items: ClaimEvidenceCategory[]): ClaimEvidenceCategory[] =>
  items.map((item, index) => ({
    description: item.helperText,
    requiredForDocument: index === 0,
    recommended: index > 0,
    tips: ['Keep a copy for your court bundle', 'Make sure dates, names, and amounts are readable'],
    ...item,
  }));

const context = (
  id: string,
  questionText: string,
  helperText: string,
  fieldPath: string
): ClaimQuestionConfig => ({
  id,
  questionText,
  typingText: 'This tells me the commercial context of the dispute.',
  helperText,
  fieldPath,
  answerType: 'textarea',
  required: true,
  mapsToDocument: true,
  validation: { minLength: 15 },
});

const detail = (
  id: string,
  questionText: string,
  helperText: string,
  fieldPath: string,
  answerType: ClaimQuestionConfig['answerType'] = 'textarea'
): ClaimQuestionConfig => ({
  id,
  questionText,
  typingText: 'I will use this detail to make the claim narrative specific.',
  helperText,
  fieldPath,
  answerType,
  required: true,
  mapsToDocument: true,
});

export const CLAIM_TYPE_CONFIGS: ClaimTypeConfig[] = [
  {
    id: 'landlord_debt_claim',
    slug: 'landlord-debt-claim',
    label: 'Landlord debt claim',
    cardDescription: 'Claim unpaid rent, service charges, damage, utilities, or other tenant debt.',
    icon: 'Home',
    accent: 'purple',
    flowMode: 'landlord_money_claim',
    commercialPriority: 'highest',
    price: CLAIM_PACK_PRICE,
    stepFlow: [
      claimTypeStep('Landlord debt claim', 'landlord_debt_claim'),
      {
        stepId: 'about',
        title: 'About the claim',
        aiIntro: 'This route is protected because it powers the current landlord Money Claim Pack.',
        questions: [
          detail('landlord_full_name', 'Who is the landlord or claimant?', 'Use the name that should appear on the claim.', 'landlord_full_name', 'text'),
          detail('tenant_full_name', 'Who is the tenant or debtor?', 'Use the tenant name from the tenancy or forwarding details.', 'tenant_full_name', 'text'),
          detail('property_address_line1', 'What property does the debt relate to?', 'Enter the rented property address.', 'property_address_line1', 'address'),
          detail('tenancy_start_date', 'When did the tenancy start?', 'Use the start date from the tenancy agreement.', 'tenancy_start_date', 'date'),
        ],
      },
      {
        stepId: 'details',
        title: 'Details',
        aiIntro: 'I will capture rent, arrears, damage, utilities, and the basis of claim.',
        questions: [
          detail('rent_amount', 'What rent was payable?', 'Enter the rent amount from the tenancy agreement.', 'rent_amount', 'currency'),
          detail('rent_frequency', 'How often was rent payable?', 'For example monthly, weekly, or four-weekly.', 'rent_frequency', 'text'),
          detail('arrears_items', 'What unpaid rent is being claimed?', 'Add the arrears periods and amounts.', 'arrears_items', 'line_items'),
          detail('damage_items', 'Are you claiming damage, cleaning, utilities, council tax, or other tenant debt?', 'Add each non-rent item separately.', 'money_claim.damage_items', 'line_items'),
          detail('basis_of_claim', 'What is the basis of the landlord claim?', 'Explain why the tenant owes the money and what records support it.', 'money_claim.basis_of_claim'),
          detail('charge_interest', 'Do you want the pack to consider interest?', 'Record whether interest should be included or reviewed.', 'money_claim.charge_interest', 'yes_no'),
        ],
      },
      {
        stepId: 'evidence',
        title: 'Evidence',
        aiIntro: 'The landlord pack needs the evidence that proves liability and each figure.',
        questions: [
          {
            id: 'evidence_items',
            questionText: 'Which landlord debt evidence do you have?',
            typingText: 'Select the records that support the landlord claim.',
            helperText: landlordEvidence.map((item) => item.label).join(', '),
            fieldPath: 'money_claim.evidence_items',
            answerType: 'evidence_checklist',
            required: true,
            mapsToDocument: true,
          },
        ],
      },
      {
        stepId: 'check',
        title: 'Check',
        aiIntro: 'The existing landlord money-claim rules check this file before generation.',
        questions: [
          detail('landlord_check', 'Ready to continue in the landlord Money Claim Pack?', 'The next step opens the existing landlord flow without changing its generator.', 'money_claim.landlord_claims_handoff_confirmed', 'yes_no'),
        ],
      },
      {
        stepId: 'results',
        title: 'Results',
        aiIntro: 'Continue into the current landlord Money Claim Pack.',
        questions: [],
      },
    ],
    lineItemCategories: lineItems(
      { id: 'rent_arrears', label: 'Rent arrears', helperText: 'Missed rent periods and amounts.' },
      { id: 'property_damage', label: 'Property damage', helperText: 'Repair, replacement, or remedial costs.' },
      { id: 'utilities', label: 'Utilities and council tax', helperText: 'Bills payable by the tenant.' },
      { id: 'other_tenant_debt', label: 'Other tenant debt', helperText: 'Other sums due under the tenancy.' },
    ),
    evidenceCategories: landlordEvidence,
    requiredDocumentFields: [
      'landlord_full_name',
      'tenant_full_name',
      'property_address_line1',
      'tenancy_start_date',
      'rent_amount',
      'rent_frequency',
      'arrears_items',
      'money_claim.damage_items',
      'money_claim.basis_of_claim',
      'money_claim.charge_interest',
      'money_claim.evidence_items',
    ],
    packOutputs: [
      'Current landlord Money Claim Pack documents',
      'N1 claim form',
      'Particulars of claim',
      'Schedule of arrears',
      'Letter before claim',
      'Evidence checklist',
      'Filing and enforcement guides',
    ],
    suitabilityBlockers: [
      'Claim is not connected to a tenancy or former tenancy.',
      'The user cannot identify the debtor or service address.',
      'The claim is not for a fixed or explainable money amount.',
    ],
    seoKeywords: [
      'landlord debt claim',
      'tenant debt claim',
      'claim unpaid rent',
      'rent arrears money claim',
      'recover tenant damage costs',
      'tenant unpaid bills claim',
      'landlord county court claim',
      'tenant debt letter before claim',
      'money claim former tenant',
      'landlord small claim pack',
    ],
  },
  {
    id: 'unpaid_invoice',
    slug: 'unpaid-invoice',
    label: 'Unpaid invoice',
    cardDescription: 'Claim payment for an invoice that remains unpaid.',
    icon: 'ReceiptText',
    accent: 'green',
    flowMode: 'generic_small_claim',
    commercialPriority: 'highest',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Unpaid invoice',
      'unpaid_invoice',
      context('invoice_context', 'What work, goods, or service did the invoice cover?', 'Name the work supplied and why payment became due.', 'generic_claim.category_context'),
      [
        detail('invoice_number', 'What is the invoice number?', 'Use the invoice reference if there is one.', 'generic_claim.invoice_number', 'text'),
        detail('invoice_date', 'What date was the invoice issued?', 'Use the date on the invoice.', 'generic_claim.key_dates.invoice_date', 'date'),
        detail('invoice_due_date', 'When was the invoice due?', 'Use the due date or payment term.', 'generic_claim.key_dates.due_date', 'date'),
        detail('work_supplied', 'What was supplied to the defendant?', 'Describe the service, work, or goods supplied.', 'generic_claim.work_supplied'),
        detail('chasing_history', 'How have you chased payment?', 'Summarise reminders, calls, letters, or emails.', 'generic_claim.chasing_history'),
      ],
      evidence(
        { id: 'invoice', label: 'Invoice', helperText: 'The invoice showing amount, date, and due date.' },
        { id: 'contract_quote', label: 'Contract or quote', helperText: 'The agreement or quote the invoice follows.' },
        { id: 'delivery_proof', label: 'Delivery or completion proof', helperText: 'Records showing work or goods were supplied.' },
        {
          id: 'chaser_emails',
          label: 'Chaser emails or messages',
          helperText: 'Payment reminders and defendant replies.',
          keywordTriggers: ['chased', 'reminded', 'asked for payment', 'ignored my email'],
          aiHint: 'You mentioned chasing payment, so these messages can help show the debt was demanded before court.',
        },
        { id: 'statement_of_account', label: 'Statement of account', helperText: 'A running balance if there are multiple invoices.' },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'invoice_balance', label: 'Unpaid invoice balance', helperText: 'The unpaid invoice amount.' },
      { id: 'late_payment_fee', label: 'Late payment fee', helperText: 'Any contractual or statutory fixed sum to review.' },
      { id: 'interest', label: 'Interest', helperText: 'Contractual or statutory interest to review.' },
    ),
    evidenceCategories: evidence(
      { id: 'invoice', label: 'Invoice', helperText: 'The invoice showing amount, date, and due date.' },
      { id: 'contract_quote', label: 'Contract or quote', helperText: 'The agreement or quote the invoice follows.' },
      { id: 'delivery_proof', label: 'Delivery or completion proof', helperText: 'Records showing work or goods were supplied.' },
      {
        id: 'chaser_emails',
        label: 'Chaser emails or messages',
        helperText: 'Payment reminders and defendant replies.',
        keywordTriggers: ['chased', 'reminded', 'asked for payment', 'ignored my email'],
        aiHint: 'You mentioned chasing payment, so these messages can help show the debt was demanded before court.',
      },
      { id: 'statement_of_account', label: 'Statement of account', helperText: 'A running balance if there are multiple invoices.' },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['No invoice, agreement, or evidence that payment became due.', 'The defendant cannot be identified.'],
    seoKeywords: ['unpaid invoice claim', 'invoice debt recovery', 'small claim unpaid invoice', 'claim unpaid business invoice', 'letter before claim unpaid invoice', 'recover unpaid invoice', 'invoice payment dispute', 'county court unpaid invoice', 'invoice claim form', 'business debt claim'],
  },
  {
    id: 'loan_or_money_owed',
    slug: 'loan-or-money-owed',
    label: 'Loan or money owed',
    cardDescription: "Claim money loaned to someone that hasn't been repaid.",
    icon: 'HandCoins',
    accent: 'lavender',
    flowMode: 'generic_small_claim',
    commercialPriority: 'high',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Loan or money owed',
      'loan_or_money_owed',
      context('loan_context', 'Why was the money paid or loaned?', 'Explain the loan, transfer, or money owed in plain terms.', 'generic_claim.category_context'),
      [
        detail('loan_date', 'When was the money lent or paid?', 'Use the date of the main transfer if possible.', 'generic_claim.key_dates.loan_date', 'date'),
        detail('amount_lent', 'How much was lent or paid?', 'Enter the principal sum before repayments.', 'generic_claim.amount_lent', 'currency'),
        detail('repayment_terms', 'What repayment terms were agreed?', 'State any deadline, instalments, or promise to repay.', 'generic_claim.repayment_terms'),
        detail('repayment_deadline', 'When should repayment have been made?', 'Use the agreed deadline or best date available.', 'generic_claim.key_dates.repayment_deadline', 'date'),
        detail('partial_payments', 'Has anything been repaid?', 'List dates and amounts for any partial repayment.', 'generic_claim.partial_payments'),
        detail('admissions', 'Has the defendant admitted the debt?', 'Summarise messages, emails, or promises to pay.', 'generic_claim.admissions'),
      ],
      evidence(
        { id: 'bank_transfer', label: 'Bank transfer or payment record', helperText: 'Proof the money was sent.' },
        { id: 'written_agreement', label: 'Written agreement', helperText: 'Any loan note, email, or signed agreement.' },
        { id: 'messages', label: 'Messages about the money', helperText: 'Texts or emails discussing the loan or debt.' },
        { id: 'repayment_promises', label: 'Repayment promises', helperText: 'Admissions or promises to repay.' },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'principal', label: 'Money lent or paid', helperText: 'The main sum owed.' },
      { id: 'missed_instalments', label: 'Missed instalments', helperText: 'Unpaid agreed instalments.' },
      { id: 'interest', label: 'Interest', helperText: 'Any agreed or statutory interest to review.' },
    ),
    evidenceCategories: evidence(
      { id: 'bank_transfer', label: 'Bank transfer or payment record', helperText: 'Proof the money was sent.' },
      { id: 'written_agreement', label: 'Written agreement', helperText: 'Any loan note, email, or signed agreement.' },
      { id: 'messages', label: 'Messages about the money', helperText: 'Texts or emails discussing the loan or debt.' },
      { id: 'repayment_promises', label: 'Repayment promises', helperText: 'Admissions or promises to repay.' },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['The payment looks like a gift rather than a repayable debt.', 'There is no evidence of agreement or repayment promise.'],
    seoKeywords: ['claim money owed', 'loan not repaid claim', 'small claim loan money owed', 'recover money loaned', 'letter before claim money owed', 'personal loan court claim', 'money owed by friend claim', 'unpaid loan small claim', 'claim repayment of loan', 'debt owed court claim'],
  },
  {
    id: 'faulty_goods_refund',
    slug: 'faulty-goods-refund',
    label: 'Faulty goods refund',
    cardDescription: 'Claim a refund for goods that are faulty, damaged, or not as described.',
    icon: 'PackageOpen',
    accent: 'amber',
    flowMode: 'generic_small_claim',
    commercialPriority: 'high',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Faulty goods refund',
      'faulty_goods_refund',
      context('goods_context', 'What item did you buy and what was wrong with it?', 'Name the goods, seller, and the main fault or mismatch.', 'generic_claim.category_context'),
      [
        detail('purchase_date', 'When did you buy the goods?', 'Use the order or purchase date.', 'generic_claim.key_dates.purchase_date', 'date'),
        detail('seller_details', 'Who sold the goods?', 'Enter the seller or business details.', 'generic_claim.seller_details'),
        detail('fault_description', 'What is faulty, damaged, or not as described?', 'Be specific about the problem and when you noticed it.', 'generic_claim.fault_description'),
        detail('refund_request', 'What refund or remedy did you ask for?', 'State what you requested and when.', 'generic_claim.refund_request'),
        detail('seller_response', 'How did the seller respond?', 'Include refusal, silence, repair offer, or partial refund.', 'generic_claim.seller_response'),
      ],
      evidence(
        { id: 'receipt', label: 'Receipt or invoice', helperText: 'Proof of purchase and amount paid.' },
        { id: 'order_confirmation', label: 'Order confirmation', helperText: 'Online order details or contract terms.' },
        {
          id: 'photos',
          label: 'Photos or video of the fault',
          helperText: 'Visual proof of the problem.',
          keywordTriggers: ['broken', 'damaged', 'faulty', 'cracked', 'not as described'],
          aiHint: 'You described a fault or damage, so clear photos can help the court see the issue quickly.',
        },
        { id: 'complaint_messages', label: 'Complaint messages', helperText: 'Messages requesting a refund or repair.' },
        { id: 'seller_reply', label: 'Seller reply', helperText: 'Any refusal, offer, or admission.' },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'refund', label: 'Refund claimed', helperText: 'The price paid for the goods.' },
      { id: 'repair_cost', label: 'Repair or replacement cost', helperText: 'Reasonable remedial cost if relevant.' },
      { id: 'delivery', label: 'Delivery or return cost', helperText: 'Shipping or collection costs.' },
    ),
    evidenceCategories: evidence(
      { id: 'receipt', label: 'Receipt or invoice', helperText: 'Proof of purchase and amount paid.' },
      { id: 'order_confirmation', label: 'Order confirmation', helperText: 'Online order details or contract terms.' },
      {
        id: 'photos',
        label: 'Photos or video of the fault',
        helperText: 'Visual proof of the problem.',
        keywordTriggers: ['broken', 'damaged', 'faulty', 'cracked', 'not as described'],
        aiHint: 'You described a fault or damage, so clear photos can help the court see the issue quickly.',
      },
      { id: 'complaint_messages', label: 'Complaint messages', helperText: 'Messages requesting a refund or repair.' },
      { id: 'seller_reply', label: 'Seller reply', helperText: 'Any refusal, offer, or admission.' },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['The seller cannot be identified.', 'There is no proof of purchase or fault.'],
    seoKeywords: ['faulty goods refund claim', 'small claim faulty goods', 'consumer refund court claim', 'goods not as described claim', 'faulty product refund letter', 'claim against retailer', 'damaged goods refund claim', 'refund refused small claim', 'consumer rights refund claim', 'faulty item court claim'],
  },
  {
    id: 'poor_service_contractor_dispute',
    slug: 'poor-service-contractor-dispute',
    label: 'Poor service / contractor dispute',
    cardDescription: 'Claim for poor quality work or services not delivered as agreed.',
    icon: 'UserRoundCheck',
    accent: 'orange',
    flowMode: 'generic_small_claim',
    commercialPriority: 'high',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Poor service / contractor dispute',
      'poor_service_contractor_dispute',
      context('service_context', 'What service was agreed and what was wrong?', 'Explain the service, price, and the failure in practical terms.', 'generic_claim.category_context'),
      [
        detail('service_agreed', 'What service was agreed?', 'Describe the work or service promised.', 'generic_claim.service_agreed'),
        detail('price_agreed', 'What price was agreed?', 'Enter the agreed price or estimate.', 'generic_claim.price_agreed', 'currency'),
        detail('service_defect', 'What was defective, missing, or late?', 'Describe what was not done properly.', 'generic_claim.service_defect'),
        detail('complaint_date', 'When did you complain?', 'Use the first clear complaint date.', 'generic_claim.key_dates.complaint_date', 'date'),
        detail('remedial_cost', 'What will it cost to put right?', 'Use quotes, estimates, or refund amount.', 'generic_claim.remedial_cost', 'currency'),
      ],
      evidence(
        { id: 'quote', label: 'Quote or estimate', helperText: 'The agreed service, scope, or price.' },
        { id: 'contract', label: 'Contract or terms', helperText: 'Any written terms or booking record.' },
        { id: 'photos', label: 'Photos of poor work', helperText: 'Visual records of defects or incomplete work.' },
        { id: 'messages', label: 'Complaint messages', helperText: 'Messages raising the issue and the response.' },
        {
          id: 'replacement_quote',
          label: 'Replacement or remedial quote',
          helperText: 'Cost to fix or complete the service.',
          showWhen: 'generic_claim.remedial_cost > 0',
        },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'refund', label: 'Refund of price paid', helperText: 'Money paid for poor service.' },
      { id: 'remedial_cost', label: 'Remedial cost', helperText: 'Cost to put the work right.' },
      { id: 'consequential_loss', label: 'Direct extra cost', helperText: 'Direct extra costs caused by the failure.' },
    ),
    evidenceCategories: evidence(
      { id: 'quote', label: 'Quote or estimate', helperText: 'The agreed service, scope, or price.' },
      { id: 'contract', label: 'Contract or terms', helperText: 'Any written terms or booking record.' },
      { id: 'photos', label: 'Photos of poor work', helperText: 'Visual records of defects or incomplete work.' },
      { id: 'messages', label: 'Complaint messages', helperText: 'Messages raising the issue and the response.' },
      {
        id: 'replacement_quote',
        label: 'Replacement or remedial quote',
        helperText: 'Cost to fix or complete the service.',
        showWhen: 'generic_claim.remedial_cost > 0',
      },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['The work or service agreement is unclear.', 'The claimed remedial cost is not evidenced.'],
    seoKeywords: ['poor service claim', 'contractor dispute claim', 'claim for poor workmanship', 'small claim poor service', 'service not delivered claim', 'contractor refund claim', 'remedial cost claim', 'poor quality work court claim', 'letter before claim contractor', 'claim against service provider'],
  },
  {
    id: 'builder_tradesperson_dispute',
    slug: 'builder-tradesperson-dispute',
    label: 'Builder or tradesperson dispute',
    cardDescription: 'Claim for unfinished work, defects, or payment disputes.',
    icon: 'HardHat',
    accent: 'teal',
    flowMode: 'generic_small_claim',
    commercialPriority: 'highest',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Builder or tradesperson dispute',
      'builder_tradesperson_dispute',
      context('builder_context', 'What building or trade work was agreed?', 'Explain the scope, property, price, and main dispute.', 'generic_claim.category_context'),
      [
        detail('scope_of_works', 'What was the agreed scope of works?', 'Describe the job, materials, finish, and agreed deliverables.', 'generic_claim.scope_of_works'),
        detail('payments_made', 'How much has already been paid?', 'List deposits, staged payments, and dates if known.', 'generic_claim.payments_made'),
        detail('unfinished_or_defective', 'What is unfinished or defective?', 'Explain defects, snagging, missed work, or unsafe work.', 'generic_claim.unfinished_or_defective'),
        detail('deadline_missed', 'Was a deadline missed?', 'State the agreed completion date or delay issue.', 'generic_claim.key_dates.deadline_missed', 'date'),
        detail('remedial_quote', 'What does another builder say it will cost to fix?', 'Use a remedial quote, estimate, or expert view.', 'generic_claim.remedial_quote', 'currency'),
      ],
      evidence(
        { id: 'quote', label: 'Quote or scope of works', helperText: 'The agreed job and price.' },
        { id: 'contract', label: 'Contract or messages agreeing terms', helperText: 'Written terms or messages.' },
        { id: 'photos', label: 'Photos and videos', helperText: 'Proof of defective or unfinished works.' },
        { id: 'snagging_list', label: 'Snagging list', helperText: 'A list of defects or unfinished items.' },
        { id: 'payment_proof', label: 'Payment proof', helperText: 'Bank transfers, receipts, or invoices.' },
        { id: 'expert_estimate', label: 'Expert or remedial estimate', helperText: 'Independent quote or report.' },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'overpayment', label: 'Overpayment or refund', helperText: 'Money paid for work not delivered.' },
      { id: 'remedial_works', label: 'Remedial works', helperText: 'Cost to fix or complete the work.' },
      { id: 'materials', label: 'Materials or wasted costs', helperText: 'Direct costs connected to the defective work.' },
    ),
    evidenceCategories: evidence(
      { id: 'quote', label: 'Quote or scope of works', helperText: 'The agreed job and price.' },
      { id: 'contract', label: 'Contract or messages agreeing terms', helperText: 'Written terms or messages.' },
      { id: 'photos', label: 'Photos and videos', helperText: 'Proof of defective or unfinished works.' },
      { id: 'snagging_list', label: 'Snagging list', helperText: 'A list of defects or unfinished items.' },
      { id: 'payment_proof', label: 'Payment proof', helperText: 'Bank transfers, receipts, or invoices.' },
      { id: 'expert_estimate', label: 'Expert or remedial estimate', helperText: 'Independent quote or report.' },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['The scope of works is too vague to plead safely.', 'No evidence of payment, defect, or remedial cost.'],
    seoKeywords: ['builder dispute claim', 'tradesperson dispute claim', 'claim against builder', 'unfinished building work claim', 'poor workmanship builder claim', 'builder refund small claim', 'defective building work court claim', 'builder letter before claim', 'remedial works claim', 'tradesman small claim'],
  },
  {
    id: 'deposit_refund',
    slug: 'deposit-refund',
    label: 'Deposit refund',
    cardDescription: 'Claim the return of a deposit paid for accommodation, work, or a booking.',
    icon: 'ShieldCheck',
    accent: 'rose',
    flowMode: 'generic_small_claim',
    commercialPriority: 'medium',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Deposit refund',
      'deposit_refund',
      context('deposit_context', 'What was the deposit paid for?', 'Explain the booking, purchase, service, or other reason for the deposit.', 'generic_claim.category_context'),
      [
        detail('deposit_purpose', 'What was the deposit for?', 'Describe the item, booking, service, or arrangement.', 'generic_claim.deposit_purpose'),
        detail('deposit_amount', 'How much deposit was paid?', 'Enter the amount paid.', 'generic_claim.deposit_amount', 'currency'),
        detail('deposit_payment_date', 'When was the deposit paid?', 'Use the payment date or best date available.', 'generic_claim.key_dates.deposit_payment_date', 'date'),
        detail('refund_terms', 'What were the refund terms?', 'State any cancellation, return, or refund agreement.', 'generic_claim.refund_terms'),
        detail('refund_trigger', 'Why should the deposit now be returned?', 'Explain what happened that makes the refund due.', 'generic_claim.refund_trigger'),
        detail('refusal_reason', 'Why has the refund been refused or delayed?', 'Summarise the other side response or silence.', 'generic_claim.refusal_reason'),
      ],
      evidence(
        { id: 'receipt', label: 'Receipt or payment proof', helperText: 'Proof the deposit was paid.' },
        { id: 'terms', label: 'Terms or booking conditions', helperText: 'Refund, cancellation, or deposit terms.' },
        { id: 'refund_messages', label: 'Refund request messages', helperText: 'Messages asking for the deposit back.' },
        { id: 'proof_of_payment', label: 'Bank or card record', helperText: 'Payment record showing amount and recipient.' },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'deposit', label: 'Deposit paid', helperText: 'The deposit amount claimed back.' },
      { id: 'fee_deduction', label: 'Disputed deduction', helperText: 'Any deduction you dispute.' },
      { id: 'extra_costs', label: 'Direct extra costs', helperText: 'Direct costs caused by the refused refund.' },
    ),
    evidenceCategories: evidence(
      { id: 'receipt', label: 'Receipt or payment proof', helperText: 'Proof the deposit was paid.' },
      { id: 'terms', label: 'Terms or booking conditions', helperText: 'Refund, cancellation, or deposit terms.' },
      { id: 'refund_messages', label: 'Refund request messages', helperText: 'Messages asking for the deposit back.' },
      { id: 'proof_of_payment', label: 'Bank or card record', helperText: 'Payment record showing amount and recipient.' },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['No proof the deposit was paid.', 'Refund terms or refund trigger are unclear.'],
    seoKeywords: ['deposit refund claim', 'claim deposit back', 'small claim deposit refund', 'deposit not returned claim', 'refund deposit letter before claim', 'booking deposit refund claim', 'service deposit refund claim', 'accommodation deposit refund claim', 'court claim deposit refund', 'recover deposit paid'],
  },
  {
    id: 'vehicle_repair_damage_dispute',
    slug: 'vehicle-repair-damage-dispute',
    label: 'Vehicle repair / damage dispute',
    cardDescription: 'Claim for vehicle repairs, damage, or related costs.',
    icon: 'Car',
    accent: 'purple',
    flowMode: 'generic_small_claim',
    commercialPriority: 'medium',
    price: CLAIM_PACK_PRICE,
    stepFlow: genericSteps(
      'Vehicle repair / damage dispute',
      'vehicle_repair_damage_dispute',
      context('vehicle_context', 'What vehicle issue are you claiming for?', 'Explain the repair, damage, garage issue, or related loss.', 'generic_claim.category_context'),
      [
        detail('garage_or_defendant', 'Who is the garage, repairer, or defendant?', 'Name the business or person responsible.', 'generic_claim.garage_or_defendant'),
        detail('repair_or_damage_issue', 'What repair or damage issue happened?', 'Describe the poor repair, damage, or disputed cost.', 'generic_claim.repair_or_damage_issue'),
        detail('cost_paid', 'How much have you already paid?', 'Enter the amount paid to the garage or defendant.', 'generic_claim.cost_paid', 'currency'),
        detail('further_repair_cost', 'What further repair or damage cost are you claiming?', 'Use the estimate, invoice, or assessed cost.', 'generic_claim.further_repair_cost', 'currency'),
        detail('vehicle_timeline', 'What is the key timeline?', 'Set out dates for repair, complaint, inspection, and refusal.', 'generic_claim.key_dates.vehicle_timeline'),
      ],
      evidence(
        { id: 'invoice', label: 'Garage invoice or receipt', helperText: 'Proof of repair cost or payment.' },
        { id: 'mechanic_report', label: 'Mechanic report', helperText: 'Independent report or diagnostic evidence.' },
        { id: 'photos', label: 'Photos of damage or repair issue', helperText: 'Visual proof of the problem.' },
        { id: 'repair_estimate', label: 'Repair estimate', helperText: 'Quote for further repair or correction.' },
        { id: 'messages', label: 'Complaint messages', helperText: 'Messages with the garage or defendant.' },
      )
    ),
    lineItemCategories: lineItems(
      { id: 'repair_refund', label: 'Repair refund', helperText: 'Refund for poor or disputed repair work.' },
      { id: 'further_repair', label: 'Further repair cost', helperText: 'Cost to fix the vehicle.' },
      { id: 'vehicle_damage', label: 'Vehicle damage', helperText: 'Damage cost caused by the defendant.' },
      { id: 'direct_extra_cost', label: 'Direct extra cost', helperText: 'Direct loss such as towing or inspection.' },
    ),
    evidenceCategories: evidence(
      { id: 'invoice', label: 'Garage invoice or receipt', helperText: 'Proof of repair cost or payment.' },
      { id: 'mechanic_report', label: 'Mechanic report', helperText: 'Independent report or diagnostic evidence.' },
      { id: 'photos', label: 'Photos of damage or repair issue', helperText: 'Visual proof of the problem.' },
      { id: 'repair_estimate', label: 'Repair estimate', helperText: 'Quote for further repair or correction.' },
      { id: 'messages', label: 'Complaint messages', helperText: 'Messages with the garage or defendant.' },
    ),
    requiredDocumentFields: genericRequiredFields,
    packOutputs: standardPackOutputs,
    suitabilityBlockers: ['No proof of the repair, damage, or amount claimed.', 'The defendant responsible for the repair or damage is unclear.'],
    seoKeywords: ['vehicle repair dispute claim', 'garage repair complaint claim', 'car repair refund claim', 'vehicle damage small claim', 'claim against garage', 'poor car repair court claim', 'mechanic dispute claim', 'repair estimate small claim', 'car damage court claim', 'letter before claim garage'],
  },
];

export const CLAIM_CONFIGS_BY_ID = Object.fromEntries(
  CLAIM_TYPE_CONFIGS.map((config) => [config.id, config])
) as Record<ClaimTypeId, ClaimTypeConfig>;

export const CLAIM_CONFIGS_BY_SLUG = Object.fromEntries(
  CLAIM_TYPE_CONFIGS.map((config) => [config.slug, config])
) as Record<string, ClaimTypeConfig>;

export function getClaimConfig(id: ClaimTypeId): ClaimTypeConfig {
  return CLAIM_CONFIGS_BY_ID[id];
}
