/**
 * Site Configuration
 *
 * Single source of truth for site-wide settings including domain, branding, and contact info.
 * Used by document generators, email templates, and frontend components.
 */

export const SITE_CONFIG = {
  // Domain & URLs
  domain: 'landlordheaven.co.uk',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://landlordheaven.co.uk',

  // Branding
  name: 'Landlord Heaven',
  tagline: 'Professional Legal Documents for UK Landlords',

  // Contact
  support_email: 'support@landlordheaven.co.uk',
  refunds_email: 'refunds@landlordheaven.co.uk',
  sales_email: 'sales@landlordheaven.co.uk',
  privacy_email: 'privacy@landlordheaven.co.uk',

  // Legal
  company_name: 'Landlord Heaven Ltd',

  // Social/External
  github_issues: 'https://github.com/anthropics/claude-code/issues',
} as const;

/**
 * Get full URL for a path
 */
export function getSiteUrl(path: string = ''): string {
  const base = SITE_CONFIG.url.replace(/\/$/, '');
  const cleanPath = path.startsWith('/') ? path : `/${path}`;
  return `${base}${cleanPath}`;
}

/**
 * Format email as mailto link
 */
export function getMailtoLink(email: keyof typeof SITE_CONFIG, subject?: string): string {
  const emailAddress = SITE_CONFIG[email];
  if (typeof emailAddress !== 'string' || !emailAddress.includes('@')) {
    return '#';
  }

  if (subject) {
    return `mailto:${emailAddress}?subject=${encodeURIComponent(subject)}`;
  }

  return `mailto:${emailAddress}`;
}

/**
 * Get document footer text (for PDFs)
 */
export function getDocumentFooter(includeTimestamp = false): string {
  const footer = `This document was generated by ${SITE_CONFIG.name} | ${SITE_CONFIG.domain}`;

  if (includeTimestamp) {
    const timestamp = new Date().toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'long',
      year: 'numeric'
    });
    return `${footer} | Generated: ${timestamp}`;
  }

  return footer;
}
