/**
 * Shared Validator Page Component
 *
 * Renders a document validator page with upload, validation display, and CTAs.
 * Creates an anonymous case via wizard/start and uses UploadField for document upload.
 */

'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { Container } from '@/components/ui/Container';
import { UploadField } from '@/components/wizard/fields/UploadField';
import { EmailCaptureModal } from '@/components/leads/EmailCaptureModal';
import { AskHeavenWidget } from '@/components/ask-heaven/AskHeavenWidget';
import { RiAlertLine, RiCheckboxCircleLine } from 'react-icons/ri';
import type { Jurisdiction } from '@/lib/jurisdiction/types';
import type { AskHeavenTopic } from '@/lib/ask-heaven/buildAskHeavenLink';

export interface ValidatorCTA {
  label: string;
  href: string;
  price: number;
  primary?: boolean;
}

export interface ValidatorPageProps {
  /** Validator type key (e.g., 'section_21', 'section_8') */
  validatorKey: string;
  /** Page title */
  title: string;
  /** Page description */
  description: string;
  /** Jurisdiction for this validator - use 'all' to show a selector */
  jurisdiction: Jurisdiction | 'all';
  /** Case type for wizard/start */
  caseType: 'eviction' | 'money_claim' | 'tenancy_agreement';
  /** Product variant for wizard/start */
  productVariant: string;
  /**
   * @deprecated Static CTAs are no longer used. Dynamic CTAs with case_id
   * are generated by UploadField after validation via getWizardCta().
   */
  ctas?: ValidatorCTA[];
  /** Features list for display */
  features?: string[];
  /** Additional info text */
  additionalInfo?: string;
}

const JURISDICTION_OPTIONS: { value: Jurisdiction; label: string }[] = [
  { value: 'england', label: 'England' },
  { value: 'wales', label: 'Wales' },
  { value: 'scotland', label: 'Scotland' },
  { value: 'northern-ireland', label: 'Northern Ireland' },
];

/**
 * Map validator keys to valid evidence categories.
 * The validator key (e.g., 'section_21') may differ from the evidence category (e.g., 'notice_s21').
 */
const VALIDATOR_TO_EVIDENCE_CATEGORY: Record<string, string> = {
  section_21: 'notice_s21',
  section_8: 'notice_s8',
  wales_notice: 'correspondence',
  scotland_notice_to_leave: 'correspondence',
  tenancy_agreement: 'tenancy_agreement',
  money_claim: 'rent_schedule',
};

/**
 * Map validator keys to Ask Heaven topics for contextual help
 */
const VALIDATOR_TO_ASK_HEAVEN_TOPIC: Record<string, AskHeavenTopic> = {
  section_21: 'section_21',
  section_8: 'section_8',
  wales_notice: 'eviction',
  scotland_notice_to_leave: 'notice_to_leave',
  tenancy_agreement: 'tenancy_agreement',
  money_claim: 'money_claim',
};

export function ValidatorPage({
  validatorKey,
  title,
  description,
  jurisdiction: jurisdictionProp,
  caseType,
  productVariant,
  // ctas prop is deprecated - dynamic CTAs are generated by UploadField after validation
  features = [],
  additionalInfo,
}: ValidatorPageProps): React.ReactElement {
  const needsJurisdictionSelector = jurisdictionProp === 'all';
  const [selectedJurisdiction, setSelectedJurisdiction] = useState<Jurisdiction | null>(
    needsJurisdictionSelector ? null : (jurisdictionProp as Jurisdiction)
  );
  const [caseId, setCaseId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(!needsJurisdictionSelector);
  const [error, setError] = useState<string | null>(null);
  const [emailOpen, setEmailOpen] = useState(false);
  const [emailStatus, setEmailStatus] = useState<string | null>(null);

  // Effective jurisdiction (either fixed or user-selected)
  const effectiveJurisdiction = selectedJurisdiction;

  // Create anonymous case when jurisdiction is known
  useEffect(() => {
    // Don't create case until jurisdiction is selected
    if (!effectiveJurisdiction) return;
    // Don't re-create if we already have a case
    if (caseId) return;

    const createCase = async () => {
      setIsLoading(true);
      try {
        const response = await fetch('/api/wizard/start', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            jurisdiction: effectiveJurisdiction,
            case_type: caseType,
            product: caseType === 'eviction' ? 'notice_only' : caseType === 'money_claim' ? 'money_claim' : 'tenancy_agreement',
            product_variant: productVariant,
            validator_key: validatorKey,
          }),
        });

        if (!response.ok) {
          const data = await response.json().catch(() => ({}));
          throw new Error(data.error || 'Failed to start validation session');
        }

        const data = await response.json();
        setCaseId(data.case_id);
      } catch (err) {
        console.error('Failed to create case:', err);
        setError(err instanceof Error ? err.message : 'Failed to start validation session');
      } finally {
        setIsLoading(false);
      }
    };

    void createCase();
  }, [effectiveJurisdiction, caseType, productVariant, validatorKey, caseId]);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-purple-50 via-purple-100 to-purple-50 pt-28 pb-16 md:pt-32 md:pb-20">
        <Container>
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-block bg-primary/10 backdrop-blur-sm rounded-full px-4 py-2 mb-6">
              <span className="text-sm font-semibold text-primary">Free Validator</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 text-gray-900">
              {title}
            </h1>
            <p className="text-xl md:text-2xl mb-6 text-gray-600">
              {description}
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <a href="#validator" className="hero-btn-primary">
                Start Validation →
              </a>
              <Link href="/pricing" className="hero-btn-secondary">
                View All Products →
              </Link>
            </div>
          </div>
        </Container>
      </section>

      {/* Disclaimer Banner */}
      <div className="border-b-2 border-warning-500 bg-warning-50 py-4">
        <Container>
          <div className="flex items-start gap-3">
            <RiAlertLine className="mt-1 h-6 w-6 shrink-0 text-warning-700" />
            <div>
              <p className="text-sm font-semibold text-warning-900">
                Free Validation Preview
              </p>
              <p className="text-sm text-warning-800">
                This validator provides helpful guidance but is not a substitute for legal advice.
                For court-ready documents with full validation, upgrade to our paid packs.
              </p>
            </div>
          </div>
        </Container>
      </div>

      {/* Main Content */}
      <div className="py-16 md:py-20">
        <Container>
          <div className="max-w-4xl mx-auto">
            <div id="validator" className="rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
              <h2 className="mb-6 text-2xl font-bold text-gray-900">
                Upload Your Document
              </h2>

              {/* Jurisdiction Selector (when needed) */}
              {needsJurisdictionSelector && !selectedJurisdiction && (
                <div className="mb-6">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Where is the property located?
                  </label>
                  <p className="text-xs text-gray-500 mb-3">
                    Different rules apply in each jurisdiction. Select the correct location for accurate validation.
                  </p>
                  <div className="grid grid-cols-2 gap-3">
                    {JURISDICTION_OPTIONS.map((option) => (
                      <button
                        key={option.value}
                        type="button"
                        onClick={() => setSelectedJurisdiction(option.value)}
                        className="rounded-lg border-2 border-gray-200 bg-white px-4 py-3 text-sm font-medium text-gray-700 transition-all hover:border-primary-400 hover:bg-primary-50 focus:outline-none focus:ring-2 focus:ring-primary-500"
                      >
                        {option.label}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {isLoading && selectedJurisdiction && (
                <div className="text-center py-8">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600 mx-auto mb-4" />
                  <p className="text-sm text-gray-600">Starting validation session...</p>
                </div>
              )}

              {error && (
                <div className="rounded-lg bg-red-50 border border-red-200 p-4 mb-6">
                  <p className="text-sm text-red-700">{error}</p>
                  <button
                    onClick={() => window.location.reload()}
                    className="mt-2 text-sm text-red-600 underline hover:no-underline"
                  >
                    Try again
                  </button>
                </div>
              )}

              {caseId && !isLoading && effectiveJurisdiction && (
                <>
                  {needsJurisdictionSelector && (
                    <div className="mb-4 flex items-center justify-between rounded-lg bg-gray-50 px-4 py-2">
                      <span className="text-sm text-gray-600">
                        Validating for: <strong className="text-gray-900">{JURISDICTION_OPTIONS.find(j => j.value === effectiveJurisdiction)?.label}</strong>
                      </span>
                      <button
                        type="button"
                        onClick={() => {
                          setSelectedJurisdiction(null);
                          setCaseId(null);
                        }}
                        className="text-xs text-primary-600 hover:underline"
                      >
                        Change
                      </button>
                    </div>
                  )}

                  <p className="text-sm text-gray-600 mb-6">
                    Upload your document (PDF or image) and our AI will analyze it for compliance issues.
                  </p>

                  <UploadField
                    caseId={caseId}
                    questionId={`validator_${validatorKey}`}
                    jurisdiction={effectiveJurisdiction}
                    label="Document Upload"
                    description="Drag and drop or click to upload your document"
                    evidenceCategory={VALIDATOR_TO_EVIDENCE_CATEGORY[validatorKey] || validatorKey}
                  />

                  {/* Email Report Section - Single unified CTA */}
                  <div className="mt-8 rounded-lg border border-gray-200 bg-gray-50 p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="font-semibold text-gray-700">Get your report by email</p>
                        <p className="text-xs text-gray-500">Get a copy of your validation results</p>
                      </div>
                      <button
                        type="button"
                        className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50"
                        onClick={() => setEmailOpen(true)}
                      >
                        Email my report
                      </button>
                    </div>
                    {emailStatus && (
                      <p className="mt-2 text-xs text-gray-600">{emailStatus}</p>
                    )}
                  </div>
                </>
              )}

              {/* Features List */}
              {features.length > 0 && (
                <div className="mt-8 rounded-xl bg-primary-50 p-6">
                  <h3 className="mb-4 text-lg font-semibold text-gray-900">
                    What We Check
                  </h3>
                  <ul className="grid md:grid-cols-2 gap-3">
                    {features.map((feature) => (
                      <li key={feature} className="flex items-center gap-2 text-sm text-gray-700">
                        <RiCheckboxCircleLine className="h-5 w-5 text-primary-600 shrink-0" />
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/*
               * NOTE: Static CTAs removed. After validation, UploadField renders
               * dynamic CTAs via getWizardCta() which include case_id context.
               * This ensures the wizard session is preserved when users upgrade.
               */}

              {/* Additional Info */}
              {additionalInfo && (
                <div className="mt-8 rounded-xl bg-blue-50 p-6">
                  <p className="text-sm text-gray-700 leading-relaxed">
                    {additionalInfo}
                  </p>
                </div>
              )}
            </div>

            {/* Ask Heaven Widget */}
            <div className="mt-8">
              <AskHeavenWidget
                variant="card"
                source="validator"
                topic={VALIDATOR_TO_ASK_HEAVEN_TOPIC[validatorKey] ?? 'general'}
                title="Have questions about your validation results?"
                description="Ask Heaven can help you understand any issues found and what to do next."
              />
            </div>

            {/* Back to Hub */}
            <div className="mt-8 text-center">
              <Link
                href="/tools/validators"
                className="text-sm text-gray-600 hover:text-primary-600 transition-colors"
              >
                ← Back to all validators
              </Link>
            </div>
          </div>
        </Container>
      </div>

      {/* Email Report Modal - Single unified component */}
      <EmailCaptureModal
        open={emailOpen}
        onClose={() => setEmailOpen(false)}
        source={`validator:${validatorKey}`}
        jurisdiction={effectiveJurisdiction ?? 'england'}
        caseId={caseId ?? undefined}
        tags={['validator', validatorKey]}
        title="Email my report"
        description="We'll send you a copy of your validation report and helpful resources."
        primaryLabel="Send report"
        includeEmailReport={true}
        reportCaseId={caseId ?? undefined}
        onSuccess={() => {
          setEmailStatus('Report queued — check your inbox soon.');
        }}
      />
    </div>
  );
}
