import type { BlogPost } from './types';

const BLOG_POST_KEYWORD_TOP_UPS: Record<string, string[]> = {
  'renters-reform-bill-what-landlords-need-to-know': [
    'renters rights act landlords',
    'section 21 abolition guidance',
    'landlord reform checklist',
    'new eviction rules england',
    'tenancy reform landlord guide',
    'renters rights act documents',
  ],
  'what-is-section-21-notice': [
    'section 21 notice form 6a',
    'section 21 notice requirements',
    'section 21 notice period',
    'no fault eviction england',
    'section 21 landlord guide',
    'valid section 21 checklist',
  ],
  'section-21-vs-section-8': [
    'section 8 vs section 21 notice',
    'eviction notice comparison england',
    'section 8 grounds explained',
    'landlord possession route',
    'rent arrears eviction notice',
    'post section 21 eviction rules',
  ],
  'how-to-serve-eviction-notice': [
    'serve eviction notice landlord',
    'section 8 proof of service',
    'form 3a service rules',
    'eviction notice delivery methods',
    'n215 certificate of service',
    'valid notice service england',
  ],
  'how-long-does-eviction-take-uk': [
    'eviction timeline uk landlord',
    'section 8 eviction timeline',
    'possession order timeline',
    'bailiff eviction timescale',
    'county court eviction delay',
    'landlord eviction process duration',
  ],
  'rent-arrears-eviction-guide': [
    'evict tenant rent arrears england',
    'ground 8 rent arrears eviction',
    'section 8 rent arrears notice',
    'rent arrears possession claim',
    'recover unpaid rent landlord',
    'tenant not paying rent eviction',
  ],
  'england-assured-shorthold-tenancy-guide': [
    'assured shorthold tenancy agreement',
    'ast agreement england',
    'assured periodic tenancy agreement',
    'england tenancy agreement 2026',
    'legacy ast landlord guide',
    'renters rights act tenancy agreement',
  ],
  'england-section-21-process': [
    'section 21 process england',
    'form 6a possession route',
    'accelerated possession section 21',
    'section 21 court process',
    'legacy section 21 cases',
    'section 21 ban landlord guide',
  ],
  'england-section-8-process': [
    'section 8 process england',
    'form 3a eviction process',
    'section 8 court claim',
    'section 8 grounds landlord',
    'possession claim section 8',
    'section 8 notice to court',
  ],
  'england-section-8-ground-8': [
    'ground 8 rent arrears',
    'mandatory possession rent arrears',
    'three months rent arrears eviction',
    'section 8 ground 8 notice',
    'ground 8 possession claim',
    'rent arrears court evidence',
  ],
  'england-accelerated-possession': [
    'accelerated possession england',
    'n5b possession claim',
    'section 21 court claim',
    'accelerated possession form n5b',
    'no hearing eviction process',
    'legacy accelerated possession guide',
  ],
  'england-standard-possession': [
    'standard possession england',
    'form n5 possession claim',
    'n119 particulars of claim',
    'section 8 possession hearing',
    'county court possession claim',
    'landlord court possession pack',
  ],
  'england-section-8-ground-10-11': [
    'ground 10 rent arrears',
    'ground 11 late rent',
    'discretionary rent arrears eviction',
    'persistent late payment tenant',
    'some rent lawfully due',
    'section 8 arrears evidence',
  ],
  'england-section-8-ground-14': [
    'ground 14 antisocial behaviour',
    'antisocial behaviour eviction england',
    'nuisance tenant eviction',
    'section 8 ground 14 notice',
    'criminal behaviour tenant',
    'asb possession claim evidence',
  ],
  'england-section-8-ground-17': [
    'ground 17 false statement',
    'tenant lied on application',
    'false reference eviction',
    'tenancy fraud landlord',
    'section 8 ground 17 notice',
    'evict tenant for false statement',
  ],
  'england-section-8-ground-1': [
    'ground 1 landlord moving back',
    'landlord returning to property',
    'owner occupier possession ground',
    'family occupation possession',
    'section 8 ground 1 notice',
    'landlord wants to live in property',
  ],
  'england-section-8-ground-2': [
    'ground 2 mortgage repossession',
    'mortgage lender possession tenant',
    'buy to let repossession tenant',
    'section 8 ground 2 notice',
    'lender repossession rented property',
    'tenant rights mortgage repossession',
  ],
  'england-section-8-ground-7': [
    'ground 7 death of tenant',
    'tenant died possession',
    'succession rights tenancy england',
    'section 8 ground 7 notice',
    'deceased tenant eviction',
    'recover property after tenant death',
  ],
  'england-section-8-ground-12': [
    'ground 12 breach tenancy',
    'breach of tenancy terms eviction',
    'section 8 ground 12 notice',
    'tenant breach agreement',
    'eviction for contract breach',
    'tenancy obligations breach evidence',
  ],
  'england-possession-hearing': [
    'possession hearing landlord',
    'county court possession hearing',
    'what happens at possession hearing',
    'landlord court hearing evidence',
    'section 8 hearing preparation',
    'possession order hearing guide',
  ],
  'england-bailiff-eviction': [
    'bailiff eviction day',
    'county court bailiff eviction',
    'warrant of possession landlord',
    'what happens when bailiffs evict',
    'tenant eviction bailiff process',
    'possession order enforcement',
  ],
  'england-county-court-forms': [
    'county court eviction forms',
    'form n5 landlord',
    'form n119 landlord',
    'n5b possession claim form',
    'possession claim court forms',
    'section 8 court forms england',
  ],
  'england-deposit-protection': [
    'deposit protection england',
    'tenancy deposit scheme landlord',
    'deposit prescribed information',
    'section 21 deposit protection',
    'deposit dispute evidence',
    'landlord deposit rules england',
  ],
  'england-hmo-licensing': [
    'hmo licensing england',
    'mandatory hmo licence',
    'additional hmo licensing',
    'hmo landlord compliance',
    'house in multiple occupation rules',
    'hmo licence checklist england',
  ],
  'england-money-claim-online': [
    'money claim online landlord',
    'mcol rent arrears',
    'claim unpaid rent online',
    'county court money claim landlord',
    'tenant debt recovery england',
    'rent arrears court claim',
  ],
  'england-particulars-of-claim': [
    'particulars of claim rent arrears',
    'n119 particulars of claim',
    'rent arrears claim wording',
    'landlord court claim particulars',
    'money claim particulars tenant',
    'possession claim particulars',
  ],
  'scotland-private-residential-tenancy': [
    'private residential tenancy scotland',
    'prt agreement scotland',
    'scottish tenancy agreement',
    'notice to leave scotland',
    'scotland landlord tenancy rules',
    'first-tier tribunal scotland tenancy',
  ],
  'scotland-eviction-process': [
    'scotland eviction process',
    'notice to leave eviction',
    'first-tier tribunal eviction',
    'scotland possession process',
    'prt eviction grounds',
    'scottish landlord eviction guide',
  ],
  'scotland-notice-to-leave': [
    'notice to leave scotland',
    'scotland eviction notice',
    'prt notice to leave',
    'notice to leave grounds',
    'scotland landlord notice periods',
    'valid notice to leave checklist',
  ],
  'scotland-first-tier-tribunal': [
    'first-tier tribunal scotland landlord',
    'housing tribunal scotland eviction',
    'scotland rent arrears tribunal',
    'prt tribunal application',
    'landlord tribunal evidence scotland',
    'eviction order tribunal scotland',
  ],
  'scotland-eviction-ground-12': [
    'scotland ground 12 rent arrears',
    'prt rent arrears eviction',
    'notice to leave ground 12',
    'rent arrears tribunal scotland',
    'scottish landlord arrears eviction',
    'eviction for rent arrears scotland',
  ],
  'scotland-eviction-ground-1': [
    'scotland ground 1 selling property',
    'landlord selling property scotland',
    'notice to leave sale ground',
    'prt eviction selling property',
    'scottish landlord sale eviction',
    'tribunal evidence property sale',
  ],
  'scotland-eviction-ground-4': [
    'scotland ground 4 landlord moving in',
    'landlord intends to live property',
    'notice to leave landlord moving in',
    'prt eviction landlord occupation',
    'family moving into rental scotland',
    'tribunal evidence landlord occupation',
  ],
  'scotland-eviction-ground-11': [
    'scotland ground 11 breach tenancy',
    'prt breach eviction',
    'notice to leave breach ground',
    'tenant breach scotland',
    'scottish tenancy obligations breach',
    'tribunal evidence breach tenancy',
  ],
  'scotland-eviction-ground-3': [
    'scotland ground 3 refurbishment eviction',
    'prt refurbishment ground',
    'notice to leave refurbishment',
    'landlord renovation eviction scotland',
    'substantial works tenant eviction',
    'tribunal evidence refurbishment',
  ],
  'scotland-eviction-ground-14': [
    'scotland ground 14 antisocial behaviour',
    'antisocial behaviour eviction scotland',
    'notice to leave asb',
    'prt asb eviction',
    'neighbour complaints tenant scotland',
    'tribunal evidence antisocial behaviour',
  ],
  'scotland-eviction-ground-6': [
    'scotland ground 6 non residential',
    'non residential purpose eviction',
    'notice to leave ground 6',
    'change of use eviction scotland',
    'prt non residential ground',
    'tribunal evidence change of use',
  ],
  'scotland-eviction-ground-7': [
    'scotland ground 7 demolition eviction',
    'demolition eviction scotland',
    'notice to leave demolition',
    'prt demolition ground',
    'landlord demolition tribunal evidence',
    'tenant eviction for demolition scotland',
  ],
  'scotland-eviction-ground-13': [
    'scotland ground 13 criminal behaviour',
    'criminal behaviour eviction scotland',
    'notice to leave criminal conduct',
    'prt criminal behaviour ground',
    'tenant conviction eviction scotland',
    'tribunal evidence criminal behaviour',
  ],
  'scotland-eviction-ground-15': [
    'scotland ground 15 antisocial association',
    'antisocial association eviction',
    'notice to leave ground 15',
    'prt antisocial association',
    'tenant associate nuisance scotland',
    'tribunal evidence antisocial association',
  ],
  'scotland-simple-procedure': [
    'scotland simple procedure rent arrears',
    'recover rent arrears scotland',
    'simple procedure claim landlord',
    'tenant debt scotland',
    'sheriff court rent arrears',
    'scottish landlord money claim',
  ],
  'scotland-deposit-protection': [
    'scotland deposit protection tenancy',
    'scottish tenancy deposit scheme',
    'safe deposits scotland landlord',
    'deposit prescribed information scotland',
    'scotland deposit dispute',
    'landlord deposit rules scotland',
  ],
  'scotland-landlord-registration': [
    'scotland landlord registration requirements',
    'register as landlord scotland',
    'landlord registration number scotland',
    'private landlord register scotland',
    'scottish landlord compliance',
    'landlord registration renewal scotland',
  ],
  'scotland-hmo-licensing': [
    'scotland hmo licensing requirements',
    'hmo licence scotland',
    'scottish hmo landlord rules',
    'hmo safety standards scotland',
    'multiple occupation licence scotland',
    'hmo compliance checklist scotland',
  ],
  'scotland-repairing-standard': [
    'scotland repairing standard landlord',
    'repairing standard scotland guidance',
    'landlord repair duties scotland',
    'tenant repair rights scotland',
    'scottish housing quality duties',
    'repairing standard tribunal scotland',
  ],
  'wales-standard-occupation-contract': [
    'standard occupation contract wales',
    'occupation contract template wales',
    'renting homes wales contract',
    'wales landlord contract rules',
    'written statement wales landlord',
    'contract-holder agreement wales',
  ],
  'wales-renting-homes-act': [
    'renting homes wales act 2016',
    'renting homes wales landlord guide',
    'occupation contract wales rules',
    'contract-holder rights wales',
    'wales landlord obligations',
    'written statement rules wales',
  ],
  'wales-eviction-process': [
    'wales eviction process',
    'possession process wales',
    'notice seeking possession wales',
    'occupation contract eviction',
    'wales landlord possession guide',
    'court possession wales landlord',
  ],
  'wales-deposit-protection': [
    'deposit protection wales',
    'tenancy deposit scheme wales',
    'occupation contract deposit rules',
    'wales landlord deposit dispute',
    'deposit prescribed information wales',
    'renting homes deposit protection',
  ],
  'rent-smart-wales': [
    'rent smart wales registration',
    'rent smart wales licence',
    'wales landlord registration',
    'landlord licence wales',
    'rent smart wales compliance',
    'wales letting agent licence',
  ],
  'wales-hmo-licensing': [
    'hmo licensing wales',
    'wales hmo licence',
    'house in multiple occupation wales',
    'hmo compliance wales',
    'wales landlord hmo rules',
    'multiple occupation licence wales',
  ],
  'wales-fitness-human-habitation': [
    'fitness for human habitation wales',
    'ffhh wales landlord',
    'wales property condition rules',
    'renting homes fitness requirements',
    'wales landlord repair obligations',
    'contract-holder habitation rights',
  ],
  'wales-possession-grounds': [
    'wales possession grounds eviction',
    'occupation contract possession grounds',
    'renting homes possession claim',
    'wales landlord eviction grounds',
    'serious rent arrears wales',
    'wales court possession evidence',
  ],
  'wales-landlord-obligations-checklist': [
    'wales landlord obligations checklist',
    'renting homes compliance checklist',
    'wales landlord legal duties',
    'occupation contract landlord duties',
    'wales rental property compliance',
    'landlord documents wales checklist',
  ],
  'wales-rent-increases': [
    'rent increase wales',
    'wales rent variation notice',
    'increase rent occupation contract',
    'renting homes rent increase rules',
    'wales landlord rent review',
    'contract-holder rent increase notice',
  ],
  'wales-abandoned-property': [
    'abandoned property wales landlord',
    'tenant abandoned property wales',
    'occupation contract abandonment',
    'wales landlord abandoned goods',
    'recover abandoned rental property',
    'renting homes abandonment rules',
  ],
  'wales-joint-tenancies': [
    'joint occupation contract wales',
    'joint contract-holder wales',
    'wales shared tenancy agreement',
    'occupation contract joint tenants',
    'renting homes joint contract',
    'wales landlord joint letting',
  ],
  'wales-gas-electrical-safety': [
    'wales landlord gas electrical safety',
    'gas safety wales landlord',
    'electrical safety wales landlord',
    'wales rental safety certificate',
    'landlord compliance certificates wales',
    'renting homes safety obligations',
  ],
  'wales-epc-requirements': [
    'wales landlord epc requirements',
    'epc rating rental wales',
    'minimum energy efficiency wales',
    'wales rental epc rules',
    'landlord energy certificate wales',
    'mees rules wales landlord',
  ],
  'wales-anti-social-behaviour-possession': [
    'wales anti social behaviour eviction',
    'asb possession wales',
    'occupation contract antisocial behaviour',
    'wales nuisance tenant possession',
    'renting homes asb grounds',
    'wales landlord evidence asb',
  ],
  'wales-notice-periods-landlords': [
    'wales landlord notice periods',
    'renting homes notice periods',
    'occupation contract notice period',
    'wales eviction notice timing',
    'landlord notice rules wales',
    'contract-holder notice periods',
  ],
  'wales-contract-holder-rights': [
    'wales contract holder rights',
    'renting homes tenant rights',
    'occupation contract rights',
    'wales landlord duties to contract holder',
    'contract-holder repair rights',
    'wales renting rights guide',
  ],
  'wales-residential-property-tribunal': [
    'residential property tribunal wales',
    'wales rent tribunal landlord',
    'property tribunal wales guide',
    'landlord tribunal evidence wales',
    'renting homes tribunal dispute',
    'wales tenancy tribunal process',
  ],
  'northern-ireland-private-tenancies-order': [
    'private tenancies order northern ireland',
    'northern ireland tenancy rules',
    'ni landlord legal duties',
    'private tenancy agreement ni',
    'northern ireland rental law',
    'ni landlord compliance guide',
  ],
  'northern-ireland-landlord-registration': [
    'northern ireland landlord registration',
    'ni landlord register',
    'register landlord northern ireland',
    'landlord registration certificate ni',
    'ni private landlord compliance',
    'northern ireland landlord licence',
  ],
  'northern-ireland-deposit-protection': [
    'northern ireland deposit protection',
    'ni tenancy deposit scheme',
    'deposit prescribed information ni',
    'landlord deposit dispute ni',
    'northern ireland deposit rules',
    'protect tenant deposit ni',
  ],
  'northern-ireland-eviction-process': [
    'northern ireland eviction process',
    'notice to quit northern ireland',
    'ni landlord possession process',
    'evict tenant northern ireland',
    'northern ireland court possession',
    'ni rent arrears eviction',
  ],
  'uk-landlord-insurance-guide': [
    'landlord insurance uk',
    'buy to let insurance',
    'rent guarantee insurance',
    'landlord liability insurance',
    'rental property insurance uk',
    'landlord buildings insurance',
    'landlord legal expenses insurance',
    'tenant default insurance',
  ],
  'uk-landlord-tax-guide': [
    'landlord tax uk',
    'rental income tax landlord',
    'buy to let tax rules',
    'landlord allowable expenses',
    'property tax return landlord',
    'uk landlord tax deductions',
  ],
  'uk-gas-safety-landlords': [
    'landlord gas safety requirements UK',
    'gas safety certificate landlord',
    'annual gas safety check',
    'cp12 certificate landlord',
    'gas safety tenant copy',
    'landlord gas compliance checklist',
  ],
  'uk-electrical-safety-landlords': [
    'landlord electrical safety requirements UK',
    'eicr landlord rules',
    'electrical safety certificate rental',
    'five year electrical inspection',
    'landlord eicr compliance',
    'rental property electrical report',
  ],
  'uk-fire-safety-landlords': [
    'landlord fire safety requirements UK',
    'smoke alarm landlord rules',
    'carbon monoxide alarm landlord',
    'fire safety rental property',
    'landlord alarm compliance',
    'rental fire risk checklist',
  ],
  'uk-tenant-referencing-guide': [
    'tenant referencing UK landlords',
    'tenant credit checks landlord',
    'right to rent referencing',
    'guarantor checks tenant',
    'tenant affordability check',
    'landlord referencing checklist',
  ],
  'uk-right-to-rent-checks': [
    'right to rent checks UK landlords',
    'right to rent documents',
    'landlord immigration check',
    'right to rent share code',
    'tenant identity check landlord',
    'right to rent compliance',
  ],
  'uk-hmo-regulations-guide': [
    'HMO regulations UK landlords',
    'hmo licence requirements',
    'house in multiple occupation rules',
    'hmo management regulations',
    'hmo fire safety rules',
    'hmo landlord compliance checklist',
  ],
  'uk-deposit-protection-guide': [
    'deposit protection UK landlords',
    'tenancy deposit scheme UK',
    'deposit prescribed information',
    'protect tenant deposit',
    'deposit dispute landlord',
    'landlord deposit compliance',
  ],
  'uk-rent-arrears-guide': [
    'rent arrears UK landlords',
    'tenant not paying rent',
    'recover unpaid rent UK',
    'rent arrears letter landlord',
    'evict tenant rent arrears',
    'rent arrears action plan',
  ],
  'uk-tenancy-agreements-guide': [
    'tenancy agreement UK landlords',
    'rental agreement template UK',
    'landlord tenancy contract',
    'tenancy clauses landlord',
    'uk rental agreement guide',
    'landlord document template',
  ],
  'uk-property-maintenance-obligations': [
    'landlord maintenance obligations UK',
    'rental property repairs landlord',
    'tenant repair rights UK',
    'landlord repair duties',
    'property maintenance compliance',
    'housing health safety landlord',
  ],
  'uk-end-of-tenancy-guide': [
    'end of tenancy UK landlords',
    'checkout inspection landlord',
    'deposit deductions evidence',
    'tenant move out checklist',
    'end of tenancy cleaning',
    'landlord inventory checkout',
  ],
  'uk-property-inspections-guide': [
    'property inspections UK landlords',
    'rental inspection checklist',
    'landlord inspection notice',
    'periodic property inspection',
    'tenant access inspection',
    'property condition report landlord',
  ],
  'uk-landlord-tenant-communication': [
    'landlord tenant communication',
    'tenant email templates landlord',
    'rental communication records',
    'landlord message evidence',
    'tenant dispute communication',
    'property management communication',
  ],
  'uk-buy-to-let-investment-guide': [
    'buy to let investment UK',
    'rental yield landlord',
    'buy to let property strategy',
    'landlord investment guide',
    'property portfolio income',
    'buy to let compliance costs',
  ],
  'uk-money-claims-online-guide': [
    'money claims online landlords',
    'mcol landlord claim',
    'tenant debt money claim',
    'claim unpaid rent online',
    'county court money claim',
    'landlord debt recovery',
  ],
  'uk-landlord-software-tools-guide': [
    'landlord software UK',
    'landlord tools online',
    'property management software',
    'rent arrears calculator',
    'landlord document generator',
    'rental compliance tools',
  ],
  'uk-property-inventory-guide': [
    'property inventory landlords',
    'rental inventory checklist',
    'tenant check-in inventory',
    'deposit dispute inventory',
    'landlord evidence photos',
    'end of tenancy inventory',
  ],
  'uk-rent-collection-methods-guide': [
    'rent collection methods UK',
    'collect rent from tenant',
    'direct debit rent collection',
    'standing order rent landlord',
    'late rent payment process',
    'rent payment tracking landlord',
  ],
  'uk-epc-requirements-guide': [
    'EPC requirements landlords UK',
    'minimum EPC rating rental',
    'landlord energy certificate',
    'mees regulations landlord',
    'rental property EPC rules',
    'epc compliance checklist',
  ],
  'uk-landlord-licensing-guide': [
    'landlord licensing UK',
    'selective licensing landlord',
    'additional licensing property',
    'hmo licensing landlord',
    'local authority landlord licence',
    'rental licensing compliance',
  ],
  'uk-guarantor-agreements-guide': [
    'guarantor agreement UK',
    'rent guarantor clause',
    'tenant guarantor agreement',
    'claim rent from guarantor',
    'guarantor deed landlord',
    'landlord guarantor checklist',
  ],
  'uk-letting-agent-selection-guide': [
    'letting agent UK',
    'choose letting agent landlord',
    'letting agent fees landlord',
    'property management agent',
    'letting agent contract',
    'landlord agent checklist',
  ],
  'uk-void-period-management-guide': [
    'void period landlord UK',
    'reduce rental voids',
    'empty property landlord costs',
    'tenant turnover strategy',
    'market rental property faster',
    'void period checklist landlord',
  ],
  'uk-property-marketing-guide': [
    'property marketing UK landlord',
    'advertise rental property',
    'rental listing photos',
    'find tenants faster',
    'landlord marketing checklist',
    'rental property advert wording',
  ],
  'uk-tenant-move-in-checklist-guide': [
    'tenant move in checklist UK',
    'landlord move in checklist',
    'new tenant paperwork',
    'check-in inventory landlord',
    'tenant handover documents',
    'rental start checklist',
  ],
  'uk-landlord-associations-guide': [
    'landlord associations UK',
    'landlord membership benefits',
    'property landlord network',
    'landlord accreditation UK',
    'landlord support organisation',
    'rental sector membership',
  ],
  'uk-tenant-retention-guide': [
    'tenant retention UK landlord',
    'keep good tenants',
    'reduce tenant turnover',
    'renew tenancy agreement',
    'landlord tenant relationship',
    'rental retention strategy',
    'tenant renewal checklist',
    'improve tenant retention',
  ],
  'uk-right-to-rent-guide': [
    'right to rent check UK',
    'right to rent documents landlord',
    'share code right to rent',
    'landlord immigration compliance',
    'right to rent civil penalty',
    'tenant identity checks',
  ],
  'uk-smoke-co-alarm-regulations-guide': [
    'smoke alarm regulations landlord UK',
    'carbon monoxide alarm requirements',
    'rental smoke alarm rules',
    'landlord alarm compliance',
    'fire safety alarm checklist',
    'smoke and co alarm regulations',
  ],
  'uk-electrical-safety-guide': [
    'electrical safety landlord UK',
    'eicr certificate landlord',
    'electrical inspection rental',
    'landlord electrical compliance',
    'eicr remedial works',
    'electrical safety standards rental',
  ],
  'uk-furnished-unfurnished-letting-guide': [
    'furnished vs unfurnished rental UK',
    'furnished letting landlord',
    'unfurnished rental property',
    'landlord furniture inventory',
    'rental furnishing tax',
    'tenant furnishing expectations',
  ],
  'uk-hmo-management-guide': [
    'HMO management UK',
    'hmo landlord responsibilities',
    'shared house management',
    'hmo tenant rules',
    'hmo fire safety management',
    'multi-let property management',
  ],
  'uk-student-letting-guide': [
    'student letting UK',
    'student accommodation landlord',
    'student tenancy agreement',
    'student guarantor requirements',
    'university rental property',
    'student hmo landlord guide',
  ],
  'uk-holiday-let-regulations-guide': [
    'holiday let regulations UK',
    'short term rental rules',
    'airbnb planning permission',
    'furnished holiday let tax',
    'holiday rental compliance',
    'landlord holiday let safety',
  ],
  'uk-corporate-letting-guide': [
    'corporate letting UK',
    'company let agreement',
    'corporate tenant landlord',
    'serviced accommodation letting',
    'relocation rental property',
    'business tenant agreement',
  ],
  'uk-property-portfolio-growth-guide': [
    'property portfolio growth UK',
    'growing property portfolio',
    'portfolio landlord strategy',
    'buy to let portfolio',
    'property investment scaling',
    'landlord portfolio management',
  ],
  'how-to-write-letter-before-action-unpaid-rent': [
    'letter before action unpaid rent',
    'rent arrears lba template',
    'pre-action protocol rent arrears',
    'tenant debt recovery letter',
    'landlord letter before claim',
    'unpaid rent demand letter',
  ],
  'what-is-county-court-judgment-landlords': [
    'county court judgment landlord',
    'ccj tenant debt',
    'enforce ccj against tenant',
    'default judgment rent arrears',
    'money judgment landlord',
    'tenant debt court judgment',
  ],
  'calculating-interest-tenant-debt': [
    'interest on tenant debt',
    'statutory interest rent arrears',
    'calculate debt interest landlord',
    '8 percent interest claim',
    'money claim interest tenant',
    'rent arrears interest calculation',
  ],
  'how-long-does-money-claim-online-take': [
    'how long does money claim online take',
    'mcol timeline landlord',
    'money claim online duration',
    'tenant debt court timeline',
    'ccj timeline rent arrears',
    'landlord money claim process',
  ],
  'when-to-use-guarantor-clause-tenancy': [
    'guarantor clause tenancy',
    'rent guarantor agreement',
    'tenant guarantor clause',
    'claim from guarantor rent',
    'guarantor deed landlord',
    'landlord guarantor protection',
  ],
  'recovering-cleaning-costs-from-tenants': [
    'recover cleaning costs tenant',
    'tenant cleaning charges',
    'end of tenancy cleaning claim',
    'cleaning deduction deposit',
    'landlord cleaning evidence',
    'claim cleaning costs court',
  ],
  'fair-wear-tear-vs-tenant-damage': [
    'fair wear and tear tenant damage',
    'wear and tear definition landlord',
    'tenant damage claim',
    'deposit deduction damage',
    'landlord damage evidence',
    'rental damage vs wear and tear',
    'inventory evidence damage claim',
    'fair wear and tear examples',
  ],
  'should-you-accept-payment-plan-from-tenant': [
    'tenant payment plan',
    'rent arrears repayment plan',
    'accept payment plan tenant',
    'tenant debt instalments',
    'landlord arrears agreement',
    'negotiate tenant debt',
  ],
  'small-claims-court-tips-landlords': [
    'small claims court landlord',
    'landlord court tips',
    'small claims hearing tenant',
    'present landlord evidence court',
    'win small claims landlord',
    'tenant debt small claim',
  ],
  'what-to-do-when-tenant-wont-pay': [
    'tenant wont pay',
    'tenant not paying rent',
    'recover money from tenant',
    'rent arrears action plan',
    'landlord debt recovery steps',
    'unpaid rent court claim',
  ],
  'do-landlords-need-a-new-tenancy-agreement-after-1-may-2026': [
    'new tenancy agreement after 1 May 2026',
    'england tenancy agreement 2026',
    'renters rights act tenancy wording',
    'assured periodic tenancy agreement',
    'review tenancy agreement england',
    'old tenancy agreement outdated',
    'replace old ast agreement',
    'landlord tenancy update checklist',
    'renters rights act contract review',
    'post reform tenancy agreement',
  ],
};

export function getBlogPostManualSeoKeywords(post: BlogPost): string[] {
  return normalizeKeywords([
    post.targetKeyword,
    ...post.secondaryKeywords,
    ...(BLOG_POST_KEYWORD_TOP_UPS[post.slug] ?? []),
  ]);
}

function normalizeKeywords(values: string[]): string[] {
  const seen = new Set<string>();
  const keywords: string[] = [];

  for (const value of values) {
    const keyword = value.replace(/\s+/g, ' ').trim();
    if (!keyword) {
      continue;
    }

    const key = keyword.toLowerCase();
    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    keywords.push(keyword);
  }

  return keywords;
}
