-- =====================================================
-- SEO AUTOMATION SCHEMA - Phase 2
-- =====================================================
-- Created: November 2024
-- Purpose: Automated SEO content generation, backlink acquisition, and performance tracking
--
-- Tables:
-- 1. seo_pages - SEO landing pages
-- 2. seo_keywords - Target keywords
-- 3. seo_content_queue - Content generation queue
-- 4. seo_backlinks - Backlink opportunities and acquisitions
-- 5. seo_performance - Daily performance metrics
-- 6. seo_automation_log - Automation task logs
-- =====================================================

-- =====================================================
-- 1. SEO PAGES TABLE
-- =====================================================
-- Stores all SEO landing pages generated by the system
-- =====================================================

CREATE TABLE IF NOT EXISTS seo_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Page identification
  slug TEXT NOT NULL UNIQUE, -- URL slug (e.g., "section-21-notice-london")
  title TEXT NOT NULL, -- Page title (SEO optimized)
  meta_description TEXT NOT NULL, -- Meta description (150-160 chars)
  h1 TEXT NOT NULL, -- H1 heading

  -- Page content
  content TEXT NOT NULL, -- Full page content (HTML/Markdown)
  content_type TEXT NOT NULL DEFAULT 'location', -- location, topic, service, guide

  -- SEO metadata
  target_keyword TEXT NOT NULL, -- Primary keyword
  secondary_keywords TEXT[] DEFAULT '{}', -- Related keywords
  search_volume INTEGER DEFAULT 0, -- Monthly search volume
  keyword_difficulty INTEGER DEFAULT 0, -- 0-100 difficulty score

  -- Location targeting (if applicable)
  location TEXT, -- e.g., "London", "Manchester"
  region TEXT, -- e.g., "England", "Scotland"
  jurisdiction TEXT, -- e.g., "england-wales"

  -- Content quality
  word_count INTEGER DEFAULT 0,
  readability_score INTEGER DEFAULT 0, -- Flesch reading ease
  ai_quality_score INTEGER DEFAULT 0, -- AI content quality (0-100)

  -- SEO status
  status TEXT NOT NULL DEFAULT 'draft', -- draft, published, archived
  published_at TIMESTAMPTZ,
  last_refreshed_at TIMESTAMPTZ,

  -- Performance tracking
  views INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  avg_time_on_page INTEGER DEFAULT 0, -- seconds
  bounce_rate DECIMAL(5,2) DEFAULT 0.00, -- percentage
  conversions INTEGER DEFAULT 0,

  -- Search rankings
  current_rank INTEGER, -- Current position in SERP
  best_rank INTEGER, -- Best position achieved
  rank_history JSONB DEFAULT '[]', -- [{date, rank}]

  -- Internal linking
  internal_links TEXT[] DEFAULT '{}', -- Links to other pages
  backlinks_count INTEGER DEFAULT 0,

  -- Schema.org structured data
  schema_markup JSONB,

  -- Automation
  auto_refresh BOOLEAN DEFAULT true, -- Auto-refresh content monthly
  last_generated_by TEXT, -- 'ai' or 'manual'
  generation_prompt TEXT, -- AI prompt used

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_seo_pages_slug ON seo_pages(slug);
CREATE INDEX idx_seo_pages_status ON seo_pages(status);
CREATE INDEX idx_seo_pages_location ON seo_pages(location);
CREATE INDEX idx_seo_pages_keyword ON seo_pages(target_keyword);
CREATE INDEX idx_seo_pages_published ON seo_pages(published_at);

-- =====================================================
-- 2. SEO KEYWORDS TABLE
-- =====================================================
-- Keyword research and tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS seo_keywords (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Keyword data
  keyword TEXT NOT NULL UNIQUE,
  search_volume INTEGER DEFAULT 0, -- Monthly searches
  difficulty INTEGER DEFAULT 0, -- 0-100 (how hard to rank)
  cpc DECIMAL(10,2) DEFAULT 0.00, -- Cost per click (for reference)

  -- Categorization
  intent TEXT, -- informational, navigational, transactional
  category TEXT, -- eviction, tenancy, hmo, etc.
  jurisdiction TEXT, -- england-wales, scotland, northern-ireland
  location TEXT, -- Specific location if local keyword

  -- Competition analysis
  serp_features TEXT[] DEFAULT '{}', -- Featured snippet, People also ask, etc.
  top_ranking_domains TEXT[] DEFAULT '{}',
  content_gaps TEXT[], -- Missing content opportunities

  -- Targeting status
  status TEXT NOT NULL DEFAULT 'identified', -- identified, targeted, ranked
  priority INTEGER DEFAULT 0, -- 1-10 priority
  assigned_page_id UUID REFERENCES seo_pages(id),

  -- Performance
  current_rank INTEGER,
  rank_history JSONB DEFAULT '[]',

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_seo_keywords_keyword ON seo_keywords(keyword);
CREATE INDEX idx_seo_keywords_status ON seo_keywords(status);
CREATE INDEX idx_seo_keywords_priority ON seo_keywords(priority DESC);

-- =====================================================
-- 3. SEO CONTENT QUEUE TABLE
-- =====================================================
-- Queue for automated content generation
-- =====================================================

CREATE TABLE IF NOT EXISTS seo_content_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Content specification
  content_type TEXT NOT NULL, -- location_page, topic_page, guide, refresh
  target_keyword TEXT NOT NULL,
  page_slug TEXT, -- If updating existing page
  page_id UUID REFERENCES seo_pages(id),

  -- Generation parameters
  location TEXT,
  jurisdiction TEXT,
  word_count_target INTEGER DEFAULT 1500,
  ai_model TEXT DEFAULT 'gpt-4o-mini', -- or claude-sonnet
  generation_prompt TEXT,

  -- Queue management
  status TEXT NOT NULL DEFAULT 'pending', -- pending, processing, completed, failed
  priority INTEGER DEFAULT 5, -- 1-10
  scheduled_for TIMESTAMPTZ DEFAULT NOW(),

  -- Execution tracking
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  processing_time INTEGER, -- seconds

  -- Results
  generated_content TEXT,
  quality_score INTEGER,
  error_message TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_seo_content_queue_status ON seo_content_queue(status);
CREATE INDEX idx_seo_content_queue_scheduled ON seo_content_queue(scheduled_for);
CREATE INDEX idx_seo_content_queue_priority ON seo_content_queue(priority DESC);

-- =====================================================
-- 4. SEO BACKLINKS TABLE
-- =====================================================
-- Backlink opportunities and acquisitions
-- =====================================================

CREATE TABLE IF NOT EXISTS seo_backlinks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Target domain
  target_domain TEXT NOT NULL,
  target_url TEXT,
  contact_email TEXT,
  contact_name TEXT,

  -- Domain metrics
  domain_authority INTEGER, -- 0-100
  domain_rating INTEGER, -- 0-100
  monthly_traffic INTEGER,
  relevance_score INTEGER, -- 0-100 how relevant to our niche

  -- Outreach
  outreach_status TEXT NOT NULL DEFAULT 'identified', -- identified, contacted, negotiating, acquired, rejected
  outreach_template TEXT,
  outreach_sent_at TIMESTAMPTZ,
  follow_up_sent_at TIMESTAMPTZ,
  follow_up_count INTEGER DEFAULT 0,

  -- Response tracking
  response_received BOOLEAN DEFAULT false,
  response_date TIMESTAMPTZ,
  response_type TEXT, -- interested, not_interested, conditional
  response_notes TEXT,

  -- Backlink details (if acquired)
  acquired BOOLEAN DEFAULT false,
  acquired_at TIMESTAMPTZ,
  backlink_url TEXT, -- The actual link pointing to us
  target_page_url TEXT, -- Our page being linked to
  anchor_text TEXT,
  link_type TEXT, -- dofollow, nofollow

  -- Cost (if paid)
  cost_gbp DECIMAL(10,2) DEFAULT 0.00,
  is_paid BOOLEAN DEFAULT false,

  -- Verification
  verified BOOLEAN DEFAULT false,
  last_checked_at TIMESTAMPTZ,
  status_check_count INTEGER DEFAULT 0,

  -- Categorization
  link_category TEXT, -- guest_post, resource_page, directory, broken_link, etc.
  niche TEXT[] DEFAULT '{}',

  -- Automation
  auto_discovered BOOLEAN DEFAULT false,
  discovery_method TEXT, -- competitor_analysis, content_search, scraping

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_seo_backlinks_status ON seo_backlinks(outreach_status);
CREATE INDEX idx_seo_backlinks_acquired ON seo_backlinks(acquired);
CREATE INDEX idx_seo_backlinks_domain ON seo_backlinks(target_domain);

-- =====================================================
-- 5. SEO PERFORMANCE TABLE
-- =====================================================
-- Daily performance tracking and analytics
-- =====================================================

CREATE TABLE IF NOT EXISTS seo_performance (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Time period
  date DATE NOT NULL,
  page_id UUID REFERENCES seo_pages(id),

  -- Traffic metrics
  sessions INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  page_views INTEGER DEFAULT 0,
  avg_session_duration INTEGER DEFAULT 0, -- seconds
  bounce_rate DECIMAL(5,2) DEFAULT 0.00,

  -- Engagement
  conversions INTEGER DEFAULT 0,
  conversion_rate DECIMAL(5,2) DEFAULT 0.00,
  revenue_gbp DECIMAL(10,2) DEFAULT 0.00,

  -- SEO metrics
  organic_traffic INTEGER DEFAULT 0,
  organic_keywords_ranking INTEGER DEFAULT 0,
  average_rank DECIMAL(5,2),

  -- Backlinks
  new_backlinks INTEGER DEFAULT 0,
  lost_backlinks INTEGER DEFAULT 0,
  total_backlinks INTEGER DEFAULT 0,

  -- Technical SEO
  page_load_time INTEGER, -- milliseconds
  core_web_vitals_score INTEGER, -- 0-100
  mobile_usability_score INTEGER, -- 0-100

  -- Competitor comparison
  competitor_rank_comparison JSONB, -- {competitor: rank}

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique constraint
  UNIQUE(date, page_id)
);

-- Indexes
CREATE INDEX idx_seo_performance_date ON seo_performance(date DESC);
CREATE INDEX idx_seo_performance_page ON seo_performance(page_id);

-- =====================================================
-- 6. SEO AUTOMATION LOG TABLE
-- =====================================================
-- Logs for all automated SEO tasks
-- =====================================================

CREATE TABLE IF NOT EXISTS seo_automation_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Task identification
  task_type TEXT NOT NULL, -- content_generation, backlink_outreach, performance_check, etc.
  task_name TEXT NOT NULL,

  -- Execution details
  status TEXT NOT NULL, -- success, failed, partial
  started_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  duration INTEGER, -- seconds

  -- Results
  items_processed INTEGER DEFAULT 0,
  items_successful INTEGER DEFAULT 0,
  items_failed INTEGER DEFAULT 0,

  -- Details
  summary TEXT,
  error_message TEXT,
  metadata JSONB, -- Any additional data

  -- Scheduling
  scheduled_time TIMESTAMPTZ,
  triggered_by TEXT, -- cron, manual, api

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_seo_automation_log_task ON seo_automation_log(task_type);
CREATE INDEX idx_seo_automation_log_status ON seo_automation_log(status);
CREATE INDEX idx_seo_automation_log_date ON seo_automation_log(created_at DESC);

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================
-- SEO tables are admin-only access
-- =====================================================

ALTER TABLE seo_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_content_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_backlinks ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_automation_log ENABLE ROW LEVEL SECURITY;

-- Admin-only access policy
CREATE POLICY "seo_admin_all" ON seo_pages FOR ALL TO authenticated
  USING (auth.uid() IN (
    SELECT id FROM users WHERE id = ANY(string_to_array(current_setting('app.admin_user_ids', true), ',')::uuid[])
  ));

CREATE POLICY "seo_keywords_admin_all" ON seo_keywords FOR ALL TO authenticated
  USING (auth.uid() IN (
    SELECT id FROM users WHERE id = ANY(string_to_array(current_setting('app.admin_user_ids', true), ',')::uuid[])
  ));

CREATE POLICY "seo_content_queue_admin_all" ON seo_content_queue FOR ALL TO authenticated
  USING (auth.uid() IN (
    SELECT id FROM users WHERE id = ANY(string_to_array(current_setting('app.admin_user_ids', true), ',')::uuid[])
  ));

CREATE POLICY "seo_backlinks_admin_all" ON seo_backlinks FOR ALL TO authenticated
  USING (auth.uid() IN (
    SELECT id FROM users WHERE id = ANY(string_to_array(current_setting('app.admin_user_ids', true), ',')::uuid[])
  ));

CREATE POLICY "seo_performance_admin_all" ON seo_performance FOR ALL TO authenticated
  USING (auth.uid() IN (
    SELECT id FROM users WHERE id = ANY(string_to_array(current_setting('app.admin_user_ids', true), ',')::uuid[])
  ));

CREATE POLICY "seo_automation_log_admin_all" ON seo_automation_log FOR ALL TO authenticated
  USING (auth.uid() IN (
    SELECT id FROM users WHERE id = ANY(string_to_array(current_setting('app.admin_user_ids', true), ',')::uuid[])
  ));

-- Public read access for published SEO pages (for rendering)
CREATE POLICY "seo_pages_public_read" ON seo_pages FOR SELECT TO anon
  USING (status = 'published');

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_seo_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_seo_pages_updated_at
  BEFORE UPDATE ON seo_pages
  FOR EACH ROW
  EXECUTE FUNCTION update_seo_updated_at();

CREATE TRIGGER update_seo_keywords_updated_at
  BEFORE UPDATE ON seo_keywords
  FOR EACH ROW
  EXECUTE FUNCTION update_seo_updated_at();

CREATE TRIGGER update_seo_content_queue_updated_at
  BEFORE UPDATE ON seo_content_queue
  FOR EACH ROW
  EXECUTE FUNCTION update_seo_updated_at();

CREATE TRIGGER update_seo_backlinks_updated_at
  BEFORE UPDATE ON seo_backlinks
  FOR EACH ROW
  EXECUTE FUNCTION update_seo_updated_at();

-- =====================================================
-- INITIAL SEED DATA (Optional)
-- =====================================================

-- Insert some initial high-value keywords
INSERT INTO seo_keywords (keyword, search_volume, difficulty, intent, category, jurisdiction, priority) VALUES
  ('section 21 notice', 18000, 65, 'informational', 'eviction', 'england-wales', 10),
  ('section 8 notice', 8100, 62, 'informational', 'eviction', 'england-wales', 9),
  ('evict tenant uk', 5400, 68, 'transactional', 'eviction', 'england-wales', 9),
  ('AST tenancy agreement', 9900, 58, 'transactional', 'tenancy', 'england-wales', 8),
  ('landlord notice period', 6600, 55, 'informational', 'eviction', 'england-wales', 8),
  ('HMO license', 12100, 60, 'informational', 'hmo', 'england-wales', 7),
  ('notice to leave Scotland', 2400, 50, 'informational', 'eviction', 'scotland', 9),
  ('private residential tenancy', 1900, 45, 'informational', 'tenancy', 'scotland', 8)
ON CONFLICT (keyword) DO NOTHING;

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TABLE seo_pages IS 'SEO landing pages generated by automation system';
COMMENT ON TABLE seo_keywords IS 'Keyword research and ranking tracking';
COMMENT ON TABLE seo_content_queue IS 'Queue for automated content generation tasks';
COMMENT ON TABLE seo_backlinks IS 'Backlink opportunities and acquisition tracking';
COMMENT ON TABLE seo_performance IS 'Daily performance metrics for SEO pages';
COMMENT ON TABLE seo_automation_log IS 'Logs for all automated SEO tasks and cron jobs';
